import test from 'node:test';import assert from 'node:assert/strict';import {modelModules} from '../scripts/modules.mjs';
for(const name of modelModules)await import('../src/'+name+'.js');
if(!CSL.experiences.concurrencyReview)await import('../src/experiences-concurrency-review.js');
const D=CSL.experiences.concurrencyReview,copy=structuredClone;
const step=(s,actor)=>D.deadlock(s,{kind:'step',actor});
test('opposite order creates an explicit two-edge wait cycle',()=>{let s=D.deadlockStart();s=step(s,'P1');s=step(s,'P2');s=step(s,'P1');s=step(s,'P2');const v=D.deadlockView(s);assert.equal(v.deadlock,true);assert.deepEqual(v.holds,{P1:['A'],P2:['B']});assert.deepEqual(v.waits.map(e=>[e.from,e.to,e.resource]),[['P1','P2','B'],['P2','P1','A']]);});
test('same lock order produces waiting without circular wait and completes',()=>{let s=D.deadlockStart('same');s=step(s,'P1');s=step(s,'P2');assert.equal(D.deadlockView(s).deadlock,false);assert.equal(s.actors.P2.waiting,'A');s=step(s,'P1');s=step(s,'P1');s=step(s,'P2');s=step(s,'P2');s=step(s,'P2');assert.equal(D.deadlockView(s).deadlock,false);assert.equal(D.deadlockView(s).complete,true);});
test('blocked step cannot steal a resource or advance program counter',()=>{let s=D.deadlockStart('same');s=step(s,'P1');const before=copy(s);s=step(s,'P2');assert.equal(s.actors.P2.pc,0);assert.equal(s.holders.A,'P1');assert.deepEqual(before.holders,s.holders);});
test('abort is recovery: it releases only the selected owner and breaks the cycle',()=>{let s=D.deadlockStart();for(const id of ['P1','P2','P1','P2'])s=step(s,id);assert.equal(D.deadlockView(s).deadlock,true);s=D.deadlock(s,{kind:'abort',actor:'P1'});assert.equal(D.deadlockView(s).deadlock,false);assert.equal(s.holders.A,null);assert.equal(s.holders.B,'P2');assert.equal(s.actors.P1.status,'aborted');});
test('historical event selection does not rewind actual resource ownership',()=>{let s=D.deadlockStart();s=step(s,'P1');s=step(s,'P2');const held=copy(s.holders);s=D.deadlock(s,{kind:'event',actor:'P1',index:0});assert.deepEqual(s.holders,held);assert.equal(D.deadlockView(s).selected.kind,'acquire');});
test('invalid deadlock operations are atomic',()=>{const s=D.deadlockStart(),old=copy(s);for(const a of [{kind:'step',actor:'P3'},{kind:'event',actor:'P1',index:0},{kind:'mode',value:'random'}])assert.throws(()=>D.deadlock(s,a));assert.deepEqual(s,old);});

test('majority preset has two valid quorums whose overlap matches 2q-N bound or exceeds it',()=>{const s=D.quorumStart(),v=D.quorumView(s);assert.equal(v.validA,true);assert.equal(v.validB,true);assert.equal(v.guaranteed,true);assert.equal(v.minIntersection,1);assert.deepEqual(v.intersection,[2]);});
test('q=2 can form disjoint valid sets on five nodes',()=>{const v=D.quorumView(D.quorumStart('disjoint'));assert.equal(v.validA,true);assert.equal(v.validB,true);assert.equal(v.guaranteed,false);assert.deepEqual(v.intersection,[]);});
test('for every q, exhaustive pairs respect the independent pigeonhole lower bound',()=>{const n=5,sets=[];for(let mask=0;mask<1<<n;mask++)sets.push(Array.from({length:n},(_,i)=>!!(mask&(1<<i))));for(let q=1;q<=n;q++){const eligible=sets.filter(s=>s.filter(Boolean).length===q),bound=Math.max(0,2*q-n);for(const a of eligible)for(const b of eligible){const overlap=a.filter((v,i)=>v&&b[i]).length;assert.ok(overlap>=bound);}}});
test('failure changes liveness but not mathematical set intersection',()=>{let s=D.quorumStart(),before=D.quorumView(s);for(const i of [0,1,2])s=D.quorum(s,{kind:'failure',index:i});const v=D.quorumView(s);assert.deepEqual(v.intersection,before.intersection);assert.equal(v.available,false);assert.equal(v.live.length,2);});
test('membership edit and q edit are separate and can make a set temporarily invalid',()=>{let s=D.quorumStart();s=D.quorum(s,{kind:'member',index:0});let v=D.quorumView(s);assert.equal(v.a.length,2);assert.equal(v.validA,false);s=D.quorum(s,{kind:'q',value:2});v=D.quorumView(s);assert.equal(v.validA,true);assert.equal(v.guaranteed,false);});
test('quorum invalid actions do not partially mutate state',()=>{const s=D.quorumStart(),old=copy(s);for(const a of [{kind:'failure',index:5},{kind:'q',value:0},{kind:'active',value:'C'},{kind:'preset',value:'x'}])assert.throws(()=>D.quorum(s,a));assert.deepEqual(s,old);});
