import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const order=['core','network','foundations','security','git','missions','catalog','extensions','learning','pedagogy','player','visuals','app','pages','workbench','boot'];
const css=await readFile(path.join(root,'src/style.css'),'utf8');
const js=(await Promise.all(order.map(n=>readFile(path.join(root,`src/${n}.js`),'utf8')))).join('\n;\n').replace(/<\/script/gi,'<\\/script');
const html=`<!doctype html>\n<html lang="ja"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b0e13"><meta name="description" content="条件を変え、仕組みを理解する。情報科学・ネットワーク・セキュリティのインタラクティブ実験室。"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; connect-src 'none'; font-src 'none'; base-uri 'none'; form-action 'none'"><title>Visual CS Lab</title><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='7' fill='%23111a22'/%3E%3Cpath d='M12 6h8m-6 0v8l-7 11h18l-7-11V6M10 20h12' fill='none' stroke='%2391cdbf' stroke-width='1.7' stroke-linejoin='round'/%3E%3C/svg%3E"><style>${css}</style></head><body><div id="app"></div><noscript>この実験室にはJavaScriptが必要です。ブラウザのJavaScriptを有効にしてください。</noscript><script>${js}</script></body></html>`;
await writeFile(path.join(root,'index.html'),html);
console.log(`Built index.html (${(Buffer.byteLength(html)/1024).toFixed(1)} KB), ${order.length} source modules. No external dependencies.`);
