/* GAP-122..127. Small trainable models with deterministic data and explicit limits. */
(() => {
'use strict';
const L=CSL,K=L.curriculum,{define:D,f:F,result:out,r,s,t,codeInput:code,round:q}=K;
const sigmoid=x=>x>=0?1/(1+Math.exp(-x)):Math.exp(x)/(1+Math.exp(x));
const mean=a=>K.sum(a)/Math.max(1,a.length),median=a=>{const sorted=a.slice().sort((a,b)=>a-b),mid=Math.floor(sorted.length/2);return sorted.length%2?sorted[mid]:(sorted[mid-1]+sorted[mid])/2;};
function standardizer(rows){const center=rows[0].map((_,i)=>mean(rows.map(row=>row[i]))),scale=center.map((m,i)=>Math.sqrt(mean(rows.map(row=>(row[i]-m)**2)))||1);return {center,scale,apply:row=>row.map((x,i)=>(x-center[i])/scale[i])};}
function mlData(kind='linear',n=60,seed=42){const random=L.rng(seed);return Array.from({length:n},()=>{const x=random()*4-2,y=random()*4-2,label=kind==='xor'?Number(x*y>0):kind==='circle'?Number(x*x+y*y<1.8):Number(x+y>.1);return {x:[x,y],y:label};});}
function decisionTree(data,depth=3,random=null){
 const probability=mean(data.map(row=>row.y));if(depth===0||data.every(row=>row.y===data[0].y)||data.length<2)return {probability,count:data.length};
 const features=random?[Math.floor(random()*data[0].x.length)]:data[0].x.map((_,i)=>i);let best=null;
 const impurity=rows=>{if(!rows.length)return 0;const p=mean(rows.map(row=>row.y));return rows.length*2*p*(1-p);};
 for(const feature of features){const values=[...new Set(data.map(row=>row.x[feature]))].sort((a,b)=>a-b);for(let i=1;i<values.length;i++){const threshold=(values[i-1]+values[i])/2,left=data.filter(row=>row.x[feature]<=threshold),right=data.filter(row=>row.x[feature]>threshold),loss=impurity(left)+impurity(right);if(!best||loss<best.loss)best={feature,threshold,left,right,loss};}}
 if(!best)return {probability,count:data.length};return {probability,count:data.length,feature:best.feature,threshold:best.threshold,left:decisionTree(best.left,depth-1,random),right:decisionTree(best.right,depth-1,random)};
}
function treePredict(tree,x){let node=tree;while(node.left)node=x[node.feature]<=node.threshold?node.left:node.right;return node.probability;}
function fitClassifier(data,method,{epochs=80,rate=.1,depth=3,seed=42,regularization=.01}={}){
 const scaler=standardizer(data.map(row=>row.x)),train=data.map(row=>({x:scaler.apply(row.x),y:row.y})),trace=[];let predict,tree=null,weights=null;
 if(method==='tree'||method==='forest'){const random=L.rng(seed),trees=[];for(let i=0;i<(method==='forest'?5:1);i++){const samples=method==='forest'?train.map(()=>train[Math.floor(random()*train.length)]):train;trees.push(decisionTree(samples,depth,method==='forest'?random:null));trace.push({iteration:i+1,loss:mean(train.map(row=>(mean(trees.map(tree=>treePredict(tree,row.x)))-row.y)**2))});}tree=trees[0];predict=x=>mean(trees.map(tree=>treePredict(tree,scaler.apply(x))));}
 else{weights=Array(train[0].x.length+1).fill(0);for(let epoch=0;epoch<epochs;epoch++){const gradient=weights.map(()=>0);let loss=0;for(const row of train){const x=[1,...row.x],score=K.dot(weights,x);if(method==='svm'){const yy=row.y?1:-1,margin=yy*score;if(margin<1){for(let i=0;i<weights.length;i++)gradient[i]-=yy*x[i]/train.length;loss+=(1-margin)/train.length;}}else{const probability=sigmoid(score);loss-=row.y*Math.log(Math.max(probability,1e-12))/train.length+(1-row.y)*Math.log(Math.max(1-probability,1e-12))/train.length;for(let i=0;i<weights.length;i++)gradient[i]+=(probability-row.y)*x[i]/train.length;}}
  weights=weights.map((w,i)=>w-rate*(gradient[i]+(i?regularization*w:0)));if(epoch%Math.max(1,Math.floor(epochs/20))===0||epoch===epochs-1)trace.push({iteration:epoch+1,loss,weights:weights.slice()});}
  predict=x=>{const score=K.dot(weights,[1,...scaler.apply(x)]);return method==='svm'?(score>=0?1:0):sigmoid(score);};}
 return {predict,trace,tree,weights,scaler};
}
K.mlData=mlData;K.fitClassifier=fitClassifier;
function polynomialFit(xs,ys,degree,lambda){const rows=xs.map(x=>Array.from({length:degree+1},(_,i)=>x**i)),transpose=K.transpose(rows),gram=K.multiply(transpose,rows),target=transpose.map(col=>K.dot(col,ys));for(let i=1;i<gram.length;i++)gram[i][i]+=lambda;const solved=K.solve(gram,target);if(!solved.solution)throw Error('この入力では係数を求められません。');return {coefficients:solved.solution,status:solved.status,predict:x=>K.sum(solved.solution.map((a,i)=>a*x**i))};}
K.polynomialFit=polynomialFit;
D(122,{
 title:'欠損値・外れ値・尺度・カテゴリの前処理',question:'テストデータの平均で補完したら、何が漏れる？',
 scope:'8〜40行のJSONデータをtrain/testへ分け、trainだけから平均／中央値補完・標準化／min-max・カテゴリ辞書を推定して適用します。未知カテゴリを別欄に残します。',
 controls:[code('data','データJSON','[{"age":20,"income":10,"city":"A","label":0},{"age":25,"income":15,"city":"B","label":0},{"age":null,"income":20,"city":"A","label":1},{"age":30,"income":null,"city":"B","label":0},{"age":35,"income":30,"city":"A","label":1},{"age":40,"income":35,"city":"B","label":1},{"age":45,"income":200,"city":"C","label":1},{"age":50,"income":45,"city":"A","label":1}]'),r('trainCount','trainに使う先頭行数',6,4,7),s('impute','欠損補完','mean',['mean','median']),s('scale','尺度','standard',['standard','minmax']),K.b('leak','誤ってtestも前処理の推定に使う',false),K.b('clip','trainの四分位範囲で外れ値を抑える',false)],
 alt:['testも平均の推定に混ぜてしまう',{leak:true}],
 intro:['入力を数値へ整える処理にも、データから学ぶ値があります。評価用のデータを先に見て平均やカテゴリを決めると、学習と評価の境界を越えます。','前処理のfitはtrainだけで行い、そこで得た補完値や尺度をtestにも同じように適用します。testの未知カテゴリはtrainにない情報として扱います。','先頭6行をtrainにし、ageとincomeの欠損を補います。testには大きいincomeと未見のcity Cがあるので、trainの統計値が変わらないことを確認してください。','testを混ぜる条件では、補完値や尺度、カテゴリ辞書が変わります。平均と中央値、標準化とmin-max、外れ値の抑制を別々に比較できます。','外れ値を機械的に削除すれば正しいとは限りません。ここでは変換の影響を計算し、実際に測定ミスか重要な少数例かの判断は別だと明記します。'],
 topics:[['欠損補完','観測されたtrainの値だけから補完値を推定します。'],['標準化','平均と標準偏差はfitした集合のものを固定して使います。'],['カテゴリ','one-hotの辞書にない値を勝手に既知の種類へ混ぜません。'],['データ漏れ','前処理にも学習段階と評価段階があります。']],
 quiz:['testの平均でtrainの欠損を補うと？','評価用情報が学習処理へ混ざる','testを使っていないのと必ず同じ','ラベルを使わなければ絶対に漏れない','ラベル以外の分布を事前に知ることも評価条件に影響します。'],
 tests:[[{},{'ageの補完値':30}]]
},p=>{
 let rows;try{rows=JSON.parse(p.data);}catch{throw Error('行のJSON配列で入力してください。');}if(!Array.isArray(rows)||rows.length<8||rows.length>40||rows.some(row=>!row||['age','income'].some(k=>row[k]!==null&&!Number.isFinite(row[k]))||typeof row.city!=='string'))throw Error('age/incomeは数値かnull、cityは文字列、8〜40行です。');const split=Math.min(p.trainCount,rows.length-1),fit=p.leak?rows:rows.slice(0,split),columns=['age','income'],stats={};for(const col of columns){const values=fit.map(row=>row[col]).filter(x=>x!==null);if(!values.length)throw Error('fit側に観測された'+col+'がありません。');const fill=p.impute==='mean'?mean(values):median(values),sorted=values.slice().sort((a,b)=>a-b),q1=sorted[Math.floor((sorted.length-1)/4)],q3=sorted[Math.floor((sorted.length-1)*3/4)],low=q1-1.5*(q3-q1),high=q3+1.5*(q3-q1),filled=fit.map(row=>{const value=row[col]??fill;return p.clip?Math.max(low,Math.min(high,value)):value;}),center=p.scale==='standard'?mean(filled):Math.min(...filled),den=p.scale==='standard'?Math.sqrt(mean(filled.map(x=>(x-center)**2))):Math.max(...filled)-center;stats[col]={fill,center,den:den||1,low,high};}const categories=[...new Set(fit.map(row=>row.city))].sort(),transformed=rows.map((row,index)=>[index,index<split?'train':'test',...columns.map(col=>{const st=stats[col],value=row[col]??st.fill,clipped=p.clip?Math.max(st.low,Math.min(st.high,value)):value;return q((clipped-st.center)/st.den);}),...categories.map(c=>+(row.city===c)),+!categories.includes(row.city)]),frames=[];frames.push(F('fitした値を固定する','testへ適用するときに平均や尺度を計算し直しません。漏れの条件ではfit集合そのものが変わっています。',K.table(['列','補完','中心','尺度','外れ値下限','上限'],columns.map(col=>{const x=stats[col];return [col,q(x.fill),q(x.center),q(x.den),q(x.low),q(x.high)];}))));frames.push(F('同じ変換をtrainとtestへ適用する','未知カテゴリは専用のUNK欄に残します。既知カテゴリのone-hotが全部0でも区別できます。',K.table(['行','用途','age変換','income変換',...categories.map(c=>'city='+c),'UNK'],transformed)));return out(frames,{'ageの補完値':q(stats.age.fill),'incomeの補完値':q(stats.income.fill),'fit行数':fit.length,'カテゴリ数':categories.length,'未知カテゴリ行数':rows.filter(row=>!categories.includes(row.city)).length});
});
D(123,{
 title:'ロジスティック回帰・決定木・Random Forest・SVM',question:'同じ点でも、直線で分ける方法と木で分ける方法は違う？',
 scope:'2特徴・20〜100点の合成二値分類を実学習。batch logistic/linear hinge SVM、Gini分割の木、bootstrap＋1特徴選択の5本forestを比較。全方式の実用最適化は対象外です。',
 controls:[s('method','分類器','logistic',['logistic','tree','forest','svm']),s('dataset','点の配置','xor',['linear','xor','circle']),r('n','学習点数',60,20,100,20),r('seed','seed',42,1,50),r('epochs','反復数',80,20,200,20),r('depth','木の深さ',3,1,5),r('x','調べる点x',1,-2,2,.1),r('y','調べる点y',1,-2,2,.1)],
 alt:['同じ点集合を決定木で分類する',{method:'tree'}],
 intro:['データの配置に対してどんな境界を表せるかは、分類器の形で変わります。一つの方式の名前だけで、どんな問題にも良いとは判断できません。','ロジスティック回帰と線形SVMは直線的な境界を学びます。決定木は条件で空間を分け、forestは異なる標本や特徴で作った複数の木の予測を合わせます。','XOR型の点を同じseedで生成し、ロジスティック回帰で学習します。同じ符号の2つの離れた領域を、一つの直線で分けにくいことを確かめます。','決定木へ切り替えて境界を比較します。調べる点を動かす、木を深くする、点を増やす操作で、形の柔軟さと学習点への適合を観察できます。','ここに表示する正解率はtrain上の値です。未知データへの性能ではありません。forestの本数や最適化も小規模で、製品間の性能比較に使う値ではありません。'],
 topics:[['logistic','線形なscoreをsigmoidで二値の確率に写して学習します。'],['決定木','不純度を下げる特徴としきい値を選びます。'],['forest','標本を取り直した複数の木の出力を平均します。'],['SVM','marginが不足する点にhinge lossを与えます。'],['モデルの表現力','データを分ける境界の形と、trainへの適合を区別します。']],
 quiz:['train正解率が高いだけで、未知データにも良いといえる？','別の評価データで確かめる必要がある','必ずいえる','木の深さを無限にすれば保証できる','学習した点への適合と汎化は別です。']
},p=>{
 const data=mlData(p.dataset,p.n,p.seed),model=fitClassifier(data,p.method,p),prediction=model.predict([p.x,p.y]),accuracy=mean(data.map(row=>+(Number(model.predict(row.x)>=.5)===row.y))),surface=Array.from({length:13},(_,yi)=>Array.from({length:13},(_,xi)=>Number(model.predict([-2+xi/3,-2+yi/3])>=.5))),frames=[];frames.push(F('同じ学習点を各方式へ渡す','点の色の正解は合成データの規則から作っています。方式を変えても同じseedなら同じ点を使います。',K.plot([{name:'class0',scatter:true,points:data.filter(x=>x.y===0).map(row=>({x:row.x[0],y:row.x[1]}))},{name:'class1',scatter:true,points:data.filter(x=>x.y===1).map(row=>({x:row.x[0],y:row.x[1]}))},{name:'調べる点',scatter:true,points:[{x:p.x,y:p.y}]}],{xLabel:'特徴x',yLabel:'特徴y'})));
 frames.push(F('学習の途中を確かめる','木では追加した木の段階、勾配法では更新epochを表示します。異なる損失の数値をそのまま同じ尺度として比較しないでください。',K.table(['更新段階','この方式のtrain損失'],model.trace.map(x=>[x.iteration,q(x.loss)]))));
 frames.push(F('学んだ分類境界を格子で調べる','格子ごとの値は、実際に学習したモデルでその座標を評価したclassです。',K.matrix(surface,{rowLabels:Array.from({length:13},(_,i)=>q(-2+i/3,2)),colLabels:Array.from({length:13},(_,i)=>q(-2+i/3,2))})));
 if(model.tree){const nodes=[],edges=[];function walk(node,id){nodes.push({id,label:node.left?'x'+node.feature+' ≤ '+q(node.threshold,2):'葉 p='+q(node.probability,2),value:'n='+node.count});if(node.left){edges.push({from:id,to:id+'L',label:'yes'},{from:id,to:id+'R',label:'no'});walk(node.left,id+'L');walk(node.right,id+'R');}}walk(model.tree,'root');frames.push(F('学習した木の条件を見る','forestでは最初の一本を例として表示します。全体の予測は5本の出力の平均です。',K.graph(nodes,edges,{directed:true})));}
 return out(frames,{'train正解率':q(accuracy),'調べた点のclass':Number(prediction>=.5),'調べた点の出力':q(prediction),'方式':p.method,'学習点数':data.length});
});
D(124,{
 title:'過学習・正則化・交差検証・データ漏れ',question:'訓練誤差を小さくするほど、未知の点にも近づく？',
 scope:'sin(πx)＋seed雑音の回帰を多項式でfit。train/test分離、5-fold CV、係数のL2正則化、標本数によるlearning curveを実計算。目標値を特徴に混ぜる反例も用意します。',
 controls:[r('degree','多項式の次数',7,1,8),r('lambda','正則化λ',.1,0,5,.1),r('noise','雑音の大きさ',.25,0,1,.05),r('seed','seed',42,1,50),r('trainCount','train点数',20,10,40,5),K.b('leak','誤って目的値をそのまま特徴に混ぜる',false)],
 alt:['低い次数のモデルにする',{degree:2}],
 intro:['学習した点を細かく通る曲線が、次に現れる点にも良いとは限りません。モデルを選ぶための検証と、最後の評価を分けて考えます。','正則化は大きすぎる係数を抑えます。交差検証はtrain内部を分けてモデル選択に使い、testは最後まで別に残します。評価に答えを混ぜれば低い誤差でも意味がありません。','7次の多項式を20点へ合わせます。train・test・CVの誤差と曲線を並べ、学習点を通ることと元の滑らかな関係を近似することを比較します。','次数を2へ下げる、λを変える、train点を増やす操作で誤差の変化を見ます。目的値を漏らす条件では、実際には使えない情報で異常に良い評価を作る反例になります。','乱数の一例だけで最良の次数を断定しません。CVを繰り返し見て選んだ後のtestを、再びモデル選択へ使い続けることも避ける必要があります。'],
 topics:[['train/validation/test','学習・選択・最終評価の役割を分離します。'],['過学習と表現力','複雑なモデルが雑音まで追う場合があります。'],['L2正則化','係数の大きさにも費用を与えます。'],['learning curve','標本数によるtrainとtestの違いを見ます。'],['リーク','本来予測時に使えない情報を特徴に入れる反例を確認します。']],
 quiz:['testの誤差を何度も見て次数を選ぶと？','testも選択へ使ったことになり、別の最終評価が必要になる','testは永遠に独立である','trainデータが自動で増える','情報を見て意思決定したこと自体が役割を変えます。']
},p=>{
 const random=L.rng(p.seed),make=n=>Array.from({length:n},()=>{const x=random()*2-1;return {x,y:Math.sin(Math.PI*x)+K.normal(random)*p.noise};}),train=make(p.trainCount),test=make(60),fit=rows=>polynomialFit(rows.map(x=>x.x),rows.map(x=>x.y),p.degree,p.lambda),model=fit(train),predict=(m,row)=>p.leak?row.y:m.predict(row.x),mse=(m,rows)=>mean(rows.map(row=>(predict(m,row)-row.y)**2)),cv=[];
 for(let fold=0;fold<5;fold++){const a=train.filter((_,i)=>i%5!==fold),b=train.filter((_,i)=>i%5===fold),model=fit(a);cv.push([fold,a.length,b.length,q(mse(model,b))]);}
 const counts=[5,10,15,20,30,40].filter(n=>n<=train.length),curve=counts.map(n=>{const model=fit(train.slice(0,n));return {n,train:mse(model,train.slice(0,n)),test:mse(model,test)};}),frames=[];
 frames.push(F('trainと独立したtestを描く','同じ生成規則でも、別の乱数標本です。目的値を漏らす条件の曲線表示は本来の多項式のままとし、誤評価と区別します。',K.plot([{name:'train',scatter:true,points:train},{name:'test',scatter:true,points:test},{name:'多項式',points:Array.from({length:81},(_,i)=>{const x=-1+i/40;return {x,y:model.predict(x)};})}],{xLabel:'x',yLabel:'y'})));
 frames.push(F('train内部だけで5-fold検証する','各foldで学習し直し、除いた点の誤差を測ります。testはこの分割に入れません。',K.table(['fold','fit数','validation数','MSE'],cv)));
 frames.push(F('点数を変えて同じ評価を繰り返す','少ない点で高次数を使うと係数が不安定な場合があります。一意でない場合は消去法で自由変数を0とする教材解を用います。',K.plot([{name:'train MSE',points:curve.map(x=>({x:x.n,y:x.train}))},{name:'test MSE',points:curve.map(x=>({x:x.n,y:x.test}))}],{xLabel:'train点数',yLabel:'MSE'})));
 frames.push(F('係数と前提を読む','目的値をそのまま予測に使うleak条件は、未来の答えを知る誤った実装です。良い性能として採用しません。',K.table(['係数の次数','値'],model.coefficients.map((x,i)=>[i,q(x)]))));
 return out(frames,{'train MSE':q(mse(model,train)),'test MSE':q(mse(model,test)),'5-fold平均MSE':q(mean(cv.map(x=>x[3]))),'係数のL2ノルム':q(Math.hypot(...model.coefficients)),'答えの漏れ':p.leak,'係数解の状態':model.status});
});
function mlpInitial(hidden,seed){const random=L.rng(seed),weight=()=>random()*1.6-.8;return {W1:Array.from({length:hidden},()=>[weight(),weight()]),b1:Array(hidden).fill(0),W2:Array.from({length:hidden},weight),b2:0};}
function mlpForward(model,x){const z=model.W1.map((row,i)=>K.dot(row,x)+model.b1[i]),h=z.map(Math.tanh),score=K.dot(model.W2,h)+model.b2,y=sigmoid(score);return {z,h,score,y};}
function mlpGradient(model,data){const gradient={W1:model.W1.map(()=>[0,0]),b1:model.b1.map(()=>0),W2:model.W2.map(()=>0),b2:0};let loss=0;for(const row of data){const f=mlpForward(model,row.x),delta=f.y-row.y;loss-=row.y*Math.log(Math.max(f.y,1e-12))/data.length+(1-row.y)*Math.log(Math.max(1-f.y,1e-12))/data.length;gradient.b2+=delta/data.length;for(let j=0;j<model.W2.length;j++){gradient.W2[j]+=delta*f.h[j]/data.length;const inner=delta*model.W2[j]*(1-f.h[j]**2)/data.length;gradient.b1[j]+=inner;for(let i=0;i<2;i++)gradient.W1[j][i]+=inner*row.x[i];}}return {gradient,loss};}
K.mlp={initial:mlpInitial,forward:mlpForward,gradient:mlpGradient};
D(125,{
 title:'ニューラルネットワークの順伝播・損失・逆伝播',question:'出力の誤りを、前の層の重みへどう伝える？',
 scope:'XORの4点を2入力→tanh隠れ層→sigmoid出力で学習。batch交差エントロピーの解析勾配と有限差分を独立に照合します。最大6隠れunit、600更新の小モデルです。',
 controls:[r('hidden','隠れunit数',3,1,6),r('epochs','更新回数',200,20,600,20),r('rate','学習率',.5,.05,1,.05),r('seed','初期重みseed',7,1,50),r('example','詳しく見る入力番号',0,0,3)],
 alt:['隠れunitを1個にする',{hidden:1}],
 intro:['重みを少し変えると出力も変わります。その変化の向きを、最後の損失から前の層へ連鎖律でたどるのが逆伝播です。','順伝播で各層の入力・出力を計算し、損失の微分を掛け合わせて重みごとの勾配を求めます。更新はその勾配と学習率から行います。','XORの4入力を使います。初期重みと200回更新後の予測を比較し、同じ順伝播の値を逆伝播が再利用していることを確認してください。','隠れunit数、初期重み、学習率を変更します。解析勾配と、重みを実際に少し動かした有限差分の差も表示し、計算式の照合を行います。','小さい学習率や少ない更新では収束しない場合があります。train4点への適合は一般のAI性能を意味せず、有限差分もすべての入力に対する証明ではありません。'],
 topics:[['順伝播','線形変換と活性化で次の層へ値を渡します。'],['交差エントロピー','正しいlabelへ高い確率を与えるよう損失を計算します。'],['連鎖律と逆伝播','後ろの誤差を局所微分で前へ伝えます。'],['勾配検査','解析式と有限差分を別々に計算して照合します。']],
 quiz:['逆伝播が計算するのは？','各重みを変えたときの損失の変化率','未知データの正しい答えそのもの','必ず最良解へ一度で移る値','勾配は局所的な変化率で、最適化の保証全体とは別です。'],
 tests:[[{},{'勾配検査の最大差':0}]]
},p=>{
 const data=[{x:[0,0],y:0},{x:[0,1],y:1},{x:[1,0],y:1},{x:[1,1],y:0}],model=mlpInitial(p.hidden,p.seed),initial=data.map(row=>mlpForward(model,row.x).y),gradient=mlpGradient(model,data).gradient,epsilon=1e-5,checks=[];for(let j=0;j<model.W1.length;j++)for(let i=0;i<2;i++){const old=model.W1[j][i];model.W1[j][i]=old+epsilon;const plus=mlpGradient(model,data).loss;model.W1[j][i]=old-epsilon;const minus=mlpGradient(model,data).loss;model.W1[j][i]=old;const finite=(plus-minus)/(2*epsilon);checks.push(['W1['+j+']['+i+']',gradient.W1[j][i],finite,Math.abs(finite-gradient.W1[j][i])]);}const curve=[];for(let epoch=0;epoch<p.epochs;epoch++){const result=mlpGradient(model,data),g=result.gradient;model.W1=model.W1.map((row,j)=>row.map((w,i)=>w-p.rate*g.W1[j][i]));model.b1=model.b1.map((b,i)=>b-p.rate*g.b1[i]);model.W2=model.W2.map((w,i)=>w-p.rate*g.W2[i]);model.b2-=p.rate*g.b2;if(epoch%Math.max(1,Math.floor(p.epochs/30))===0||epoch===p.epochs-1)curve.push({x:epoch+1,y:mlpGradient(model,data).loss});}const selected=data[p.example],forward=mlpForward(model,selected.x),frames=[];
 frames.push(F('初期値から損失を下げる','同じ4点のbatch勾配を平均し、各重みを更新しています。横軸は画面の再生時間でなく更新回数です。',K.plot([{name:'交差エントロピー',points:curve}],{xLabel:'更新回数',yLabel:'損失'})));
 frames.push(F('選んだ入力の順伝播を追う','入力、線形和、tanh、出力score、sigmoidを別々に表示します。',K.table(['段階','値'],[['入力',selected.x.join(',')],['z1',forward.z.map(q).join(',')],['tanh(z1)',forward.h.map(q).join(',')],['出力score',q(forward.score)],['sigmoid',q(forward.y)],['正解',selected.y]])));
 frames.push(F('独立な有限差分で勾配を検査する','この検査は学習前の重みに対して行い、解析式と損失関数の数値差分を比較しています。',K.table(['重み','解析微分','有限差分','絶対差'],checks.map(row=>[row[0],q(row[1],8),q(row[2],8),q(row[3],10)]))));
 frames.push(F('4つの入力の予測を比較する','モデルの容量や初期値、更新数によって結果が違うことがあります。',K.table(['入力','label','初期確率','学習後確率'],data.map((row,i)=>[row.x.join(','),row.y,q(initial[i]),q(mlpForward(model,row.x).y)]))));
 return out(frames,{'最終損失':q(mlpGradient(model,data).loss),'train正解率':mean(data.map(row=>+(Number(mlpForward(model,row.x).y>=.5)===row.y))),'勾配検査の最大差':q(Math.max(...checks.map(x=>x[3])),8),'調べた入力番号':p.example});
});
D(126,{
 title:'A*・ゲーム探索・制約充足・知識からの計画',question:'先の見積りや制約を使うと、探索をどう減らせる？',
 scope:'5×5重み付き格子のA*とDijkstra照合、1〜3個取りゲームのminimax、4〜8Queensのbacktracking、鍵と扉の有限状態BFS計画を実行。一般AIの推論器ではありません。',
 controls:[s('mode','課題','astar',[['astar','A*経路探索'],['game','minimax'],['queens','N-Queens'],['planning','状態と行動の計画']]),s('heuristic','A*の見積り','manhattan',['zero','manhattan','over']),r('seed','配置seed',7,1,40),r('stones','ゲームの石数',8,1,16),r('queens','Queenの数',5,4,8),K.b('key','最初から鍵を持つ',false)],
 alt:['A*の見積りを0にする',{heuristic:'zero'}],
 intro:['単に全候補を順番に試すだけでなく、残りの距離、相手の応答、満たすべき制約、行動の前提を使うと探索の順番を工夫できます。','A*は到達コストと残りの見積りを足して選びます。ゲームでは相手の選択、CSPでは同時に満たす条件、計画では行動による状態変化を扱います。','5×5の格子で右下を目指します。重みは正で、Manhattan距離は最小1の移動を仮定した過小見積りです。展開した場所と最終経路を分けて見ます。','見積りを0にするとDijkstraと同じ基準になります。過大見積りは最短の保証を失いますが、今回の一例で必ず誤るとは限りません。他の課題でも判断の根拠を追えます。','小さい探索空間に上限を設けています。ある例が解けたことを、一般の難しい問題が常に速く解ける証拠とは扱いません。'],
 topics:[['A*','g+hの評価と、許容的な見積りの役割を確認します。'],['minimax','自分の利益と相手の最善応答を交互に考えます。'],['制約充足','部分的な配置で制約に違反したら枝を戻ります。'],['計画と知識','行動の前提・追加・削除から到達する状態を探索します。']],
 quiz:['A*で過大評価するheuristicを使うと？','最短経路を必ず返す保証は失われる','必ず間違った経路になる','探索しなくても必ず最短が分かる','保証がないことと、すべての例で失敗することは違います。']
},p=>{
 const frames=[];
 if(p.mode==='astar'){const random=L.rng(p.seed),n=5,costs=Array.from({length:25},()=>1+Math.floor(random()*4)),blocked=new Set([7,12,17]),neighbors=id=>[id%n>0?id-1:null,id%n<n-1?id+1:null,id>=n?id-n:null,id<n*(n-1)?id+n:null].filter(x=>x!==null&&!blocked.has(x));function search(kind){const dist=Array(25).fill(Infinity),open=new Set([0]),closed=new Set(),parent={},steps=[];dist[0]=0;const h=id=>kind==='zero'?0:(8-id%n-Math.floor(id/n))*(kind==='over'?5:1);while(open.size){const current=[...open].sort((a,b)=>dist[a]+h(a)-dist[b]-h(b)||a-b)[0];open.delete(current);closed.add(current);steps.push({current,dist:dist.slice(),closed:[...closed]});if(current===24)break;for(const next of neighbors(current)){const candidate=dist[current]+costs[next];if(candidate<dist[next]){dist[next]=candidate;parent[next]=current;open.add(next);closed.delete(next);}}}const path=[];if(Number.isFinite(dist[24]))for(let at=24;at!==undefined;at=parent[at])path.unshift(at);return {dist,path,steps};}const run=search(p.heuristic),reference=search('zero');for(const step of run.steps)frames.push(F('格子'+step.current+'を展開する','gは現在までの最小候補、hは残りの見積りです。親への参照から最終経路を復元します。',K.matrix(Array.from({length:5},(_,y)=>Array.from({length:5},(_,x)=>{const id=y*5+x;return blocked.has(id)?'壁':id===step.current?'現在':Number.isFinite(step.dist[id])?step.dist[id]:'未到達';})))));frames.push(F('最終経路を復元する','基準のDijkstraと経路コストを比較して、今回の結果が最短か確認します。',K.cells([{label:'経路',values:run.path}])));return out(frames,{'経路コスト':run.dist[24],'展開数':run.steps.length,'Dijkstraの最短コスト':reference.dist[24],'今回最短だった':run.dist[24]===reference.dist[24]});}
 if(p.mode==='game'){const memo=new Map([[0,-1]]),rows=[];function solve(stones){if(memo.has(stones))return memo.get(stones);const moves=Array.from({length:Math.min(3,stones)},(_,i)=>i+1),scores=moves.map(take=>-solve(stones-take)),value=Math.max(...scores);memo.set(stones,value);rows.push([stones,moves.join(','),scores.join(','),value===1?'勝てる':'相手が最善なら負ける']);return value;}const value=solve(p.stones),best=Array.from({length:Math.min(3,p.stones)},(_,i)=>i+1).find(take=>-solve(p.stones-take)===value);frames.push(F('相手に手番を渡した状態を評価する','最後の石を取った側が勝つ規則です。相手の良い結果は自分には悪い結果なので符号を反転します。',K.table(['残り石','取れる数','自分から見た評価','結論'],rows)));return out(frames,{'最初に取る数':best,'勝てる状態':value===1,'評価した状態数':memo.size,'heuristic比較設定':p.heuristic});}
 if(p.mode==='queens'){const positions=[],snapshots=[];let attempts=0;function solve(row){if(row===p.queens)return true;for(let col=0;col<p.queens;col++){attempts++;const valid=positions.every((c,r)=>c!==col&&Math.abs(c-col)!==row-r);if(snapshots.length<90)snapshots.push({row,col,valid,positions:positions.slice()});if(!valid)continue;positions.push(col);if(solve(row+1))return true;positions.pop();}return false;}const success=solve(0);for(const st of snapshots)frames.push(F(`行${st.row}・列${st.col}を試す`,st.valid?'これまでのQueenと列・対角線が重ならないので次へ進みます。':'制約違反なので、この候補の先は探索しません。',K.matrix(Array.from({length:p.queens},(_,row)=>Array.from({length:p.queens},(_,col)=>st.positions[row]===col?'Q':row===st.row&&col===st.col?'?':'·')))));frames.push(F('見つかった配置','最初に見つかった1解です。すべての解を列挙したわけではありません。',K.matrix(Array.from({length:p.queens},(_,row)=>Array.from({length:p.queens},(_,col)=>positions[row]===col?'Q':'·')))));return out(frames,{'解を発見':success,'試した候補数':attempts,'Queen数':positions.length,'heuristic比較設定':p.heuristic});}
 const initial={room:'hall',key:p.key,open:false},encode=x=>JSON.stringify(x),queue=[{state:initial,plan:[]}],seen=new Set([encode(initial)]),rows=[];let found=null;while(queue.length){const node=queue.shift();rows.push([node.state.room,node.state.key,node.state.open,node.plan.join(' → ')]);if(node.state.room==='goal'){found=node;break;}const options=[];if(node.state.room==='hall')options.push(['enter-study',{...node.state,room:'study'}]);if(node.state.room==='study'){options.push(['return-hall',{...node.state,room:'hall'}]);if(!node.state.key)options.push(['take-key',{...node.state,key:true}]);}if(node.state.room==='hall'&&node.state.key&&!node.state.open)options.push(['unlock-door',{...node.state,open:true}]);if(node.state.room==='hall'&&node.state.open)options.push(['enter-goal',{...node.state,room:'goal'}]);for(const [action,state]of options)if(!seen.has(encode(state))){seen.add(encode(state));queue.push({state,plan:[...node.plan,action]});}}frames.push(F('行動の前提と効果を使って計画する','unlockには鍵が必要、goalへ入るには扉が開いている必要があります。BFSで同じ状態への無駄な再探索を避けます。',K.table(['部屋','鍵','扉open','ここまでの行動'],rows)));return out(frames,{'目標へ到達':!!found,'計画の長さ':found?.plan.length||0,'行動列':found?.plan.join(' → ')||'なし','heuristic比較設定':p.heuristic});
});
D(127,{
 title:'強化学習・価値・探索と活用・Q学習',question:'正解を教わらず、報酬から次の行動をどう選ぶ？',
 scope:'4×4格子の有限MDPをtabular Q-learningで実学習。step報酬・goal・危険マス、ε-greedy、割引、確率的な行動ずれをseedで再現。1episode60step、最大300episodeです。',
 controls:[r('episodes','episode数',200,20,300,20),r('epsilon','探索する確率',20,0,100,5,'%'),r('alpha','更新率α',.3,.1,1,.1),r('gamma','割引γ',.9,0,1,.1),r('seed','seed',42,1,50),K.b('slip','時々別の方向へ動く',false)],
 alt:['探索する割合を0にする',{epsilon:0}],
 intro:['強化学習では行動の結果として報酬を受け、後から得る報酬も含めて選択を改善します。既に良さそうな行動と、まだ試していない行動の両方を考えます。','Q値は状態と行動の組の将来価値です。得た報酬と次状態の最大Qから目標を作り、現在の値へ少しずつ反映します。terminalでは先の価値を足しません。','左上から右下のgoalへ進みます。危険マスに入ると失敗で終了するため、stepごとの小さな費用と到達報酬を合わせて学びます。','探索を0にすると初期の選択に偏る場合があります。seed、γ、行動ずれを変え、同じ方策でも確率的な環境で結果が変わることを確認できます。','数百episodeの小例は収束の保証ではありません。表示するgreedyな経路は学習後の試行で、学習中に探索した全経路とは異なります。'],
 topics:[['状態・行動・報酬','何を観測して何を選び、どの値を受け取るかを定義します。'],['Bellman型の目標','rewardと割り引いた次の価値を組み合わせます。'],['探索と活用','未知の行動を試す割合を操作します。'],['方策と価値','Qの表と、その表から選ぶ行動を分けます。']],
 quiz:['terminalに到着した更新の目標値は？','その報酬を使い、次状態のQを足さない','必ず未来のQを無限に足す','終わったので学習しない','episodeの終端の扱いは価値の更新に影響します。']
},p=>{
 const random=L.rng(p.seed),Q=Array.from({length:16},()=>Array(4).fill(0)),hazards=new Set([5,10]),moves=[[-1,0],[0,1],[1,0],[0,-1]],step=(state,action)=>{const [dy,dx]=moves[action],y=Math.max(0,Math.min(3,Math.floor(state/4)+dy)),x=Math.max(0,Math.min(3,state%4+dx)),next=y*4+x,terminal=next===15||hazards.has(next);return {next,terminal,reward:next===15?1:hazards.has(next)?-1:-.03};},curve=[],updates=[];let successes=0;
 for(let episode=0;episode<p.episodes;episode++){let state=0,total=0,goal=false;for(let count=0;count<60;count++){let action=random()<p.epsilon/100?Math.floor(random()*4):Q[state].indexOf(Math.max(...Q[state]));if(p.slip&&random()<.15)action=Math.floor(random()*4);const outcome=step(state,action),old=Q[state][action],target=outcome.reward+(outcome.terminal?0:p.gamma*Math.max(...Q[outcome.next]));Q[state][action]+=p.alpha*(target-old);if(updates.length<18)updates.push([episode,state,action,q(old),q(outcome.reward),q(target),q(Q[state][action])]);total+=outcome.reward;state=outcome.next;if(outcome.terminal){goal=state===15;break;}}if(goal)successes++;curve.push({x:episode+1,y:total});}
 const path=[0],visited=new Set([0]);let state=0;for(let i=0;i<20;i++){const action=Q[state].indexOf(Math.max(...Q[state])),outcome=step(state,action);path.push(outcome.next);state=outcome.next;if(outcome.terminal||visited.has(state))break;visited.add(state);}const arrows=['↑','→','↓','←'],frames=[];frames.push(F('Q値の更新を1つずつ追う','旧値、受けたreward、更新目標、新しい値を同じ行で比較します。',K.table(['episode','state','action','旧Q','reward','target','新Q'],updates)));
 frames.push(F('episodeごとの合計報酬','探索中は遠回りや失敗も含まれます。各episodeは最大60stepで打ち切っています。',K.plot([{name:'合計reward',points:curve}],{xLabel:'episode',yLabel:'reward'})));
 frames.push(F('学んだgreedy方策を表にする','危険とgoalは環境の情報です。矢印は学習後のQの最大値から選んだ行動を表します。',K.matrix(Array.from({length:4},(_,y)=>Array.from({length:4},(_,x)=>{const id=y*4+x;return id===15?'GOAL':hazards.has(id)?'危険':arrows[Q[id].indexOf(Math.max(...Q[id]))];})))));
 frames.push(F('学習後に探索なしで進む','同じ場所へ戻ったら表示を止め、成功していない方策を成功したように演出しません。',K.cells([{label:'greedy経路',values:path}])));
 return out(frames,{'学習中のgoal到達数':successes,'学習後のgoal到達':state===15,'初期状態の最大Q':q(Math.max(...Q[0])),'episode数':p.episodes});
});
})();
