/* GAP-095..101. Virtual packets and protocol state; no actual network traffic. */
(() => {
'use strict';
const L=CSL,K=L.curriculum,{define:D,f:F,result:out,r,s,t,codeInput:code,round:q}=K;
const equalAddress=(a,b)=>L.ipInt(a)===L.ipInt(b);
K.internetChecksum=bytes=>{let sum=0;for(let i=0;i<bytes.length;i+=2)sum+=(bytes[i]<<8)|(bytes[i+1]||0);while(sum>>>16)sum=(sum&65535)+(sum>>>16);return (~sum)&65535;};
K.ipv4Bytes=({source='192.0.2.1',target='198.51.100.2',ttl=64,payload=20,id=1,offset=0,more=false,df=false,protocol=6}={})=>{const bytes=Array(20).fill(0),len=20+payload;bytes[0]=0x45;bytes[2]=len>>>8;bytes[3]=len&255;bytes[4]=id>>>8;bytes[5]=id&255;const flags=(df?0x4000:0)|(more?0x2000:0)|offset;bytes[6]=flags>>>8;bytes[7]=flags&255;bytes[8]=ttl;bytes[9]=protocol;source.split('.').forEach((x,i)=>bytes[12+i]=+x);target.split('.').forEach((x,i)=>bytes[16+i]=+x);const checksum=K.internetChecksum(bytes);bytes[10]=checksum>>>8;bytes[11]=checksum&255;return bytes;};
D(95,{
 title:'Ethernetフレーム・VLAN・MAC表の期限・STP',question:'スイッチを三角形につなぐと、どの線を使う？',
 scope:'3スイッチの三角形と3端末。収束後のSTPのroot/designated/alternate port、VLAN別MAC学習・期限、unknown unicastの転送を実行。ループ注入時は100転送で打ち切ります。',
 controls:[s('root','優先するroot bridge','S1',['S1','S2','S3']),K.b('stp','STPでループを避ける',true),K.b('learn','送信元MACを学習する',true),r('gap','返信後の待ち時間',5,0,90,5,'s'),r('cVlan','端末CのVLAN',20,10,20,10),code('flows','端末間の送信','A B\nB A\nA B\nA C')],
 alt:['MAC表の期限を越えてから送信する',{gap:90}],
 intro:['スイッチに冗長な道を作ると、障害に備えられる一方、知らない宛先への転送が回り続ける場合があります。線の形と転送規則を一緒に見ます。','STPはrootへの経路を基準に使うポートを選びます。MAC学習は送信元と入ってきたポートをVLANごとに記録し、宛先が不明なら同じVLANへ広げます。','AからBへ送り、Bから返信します。最初は不明だったBのMACが返信から学習され、次の送信先が絞られる様子を確認してください。','待ち時間を90秒にすると60秒の学習期限を越えます。rootを変える、CのVLANを合わせる、STPを外す条件も比較できます。','このSTP表示は3台の収束後の役割選択です。実規格の全タイマーは省略しています。ループは安全のため有限回で止め、正常な配送完了とは扱いません。'],
 topics:[['フレームと802.1Q','宛先・送信元MACと、trunkを通るVLANタグを区別します。'],['MAC学習','送信元が来た場所をVIDと一緒に覚えます。'],['エージング','以前の接続情報を期限後に使い続けないようにします。'],['BPDUとroot選出','bridgeの優先順位とrootへのコストを比較します。'],['ポート役割','root・designatedを使い、alternateを待機させます。']],
 quiz:['宛先のMACを学習するとき、主に見るのは？','受信フレームの送信元MACと入ったポート','存在しない宛先を推測した値','IPのポート番号だけ','返信も新しい送信フレームであり、送信元の位置を学習できます。']
},p=>{const switches=['S1','S2','S3'],links=[['S1','S2'],['S2','S3'],['S1','S3']],cost=Object.fromEntries(switches.map(x=>[x,x===p.root?0:1])),idOrder=[p.root,...switches.filter(x=>x!==p.root)],rootPort=Object.fromEntries(switches.filter(x=>x!==p.root).map(x=>[x,p.root])),roles=links.map(([a,b])=>{const designated=cost[a]<cost[b]||cost[a]===cost[b]&&idOrder.indexOf(a)<idOrder.indexOf(b)?a:b,other=designated===a?b:a,forward=other===p.root||rootPort[other]===designated;return {a,b,designated,other,forward};}),hosts={A:{switch:'S1',vlan:10,mac:'02:00:00:00:00:0A'},B:{switch:'S2',vlan:10,mac:'02:00:00:00:00:0B'},C:{switch:'S3',vlan:p.cVlan,mac:'02:00:00:00:00:0C'}},tables=Object.fromEntries(switches.map(x=>[x,new Map()])),frames=[],rows=[],delivered={};let transfers=0,time=0,limited=false;
 frames.push(F('BPDUの優先情報から役割を決める','rootのpath costは0、他は直接rootへ1です。同コストのdesignatedはbridge ID順で決めます。',K.table(['リンク','designated側','反対側の役割','データ転送'],roles.map(e=>[e.a+'—'+e.b,e.designated,e.forward?'root port':'alternate',p.stp?e.forward:true]))));
 const flows=p.flows.split('\n').filter(x=>x.trim());if(!flows.length||flows.length>10)throw Error('送信は A B の形式で1〜10行です。');for(const [index,line]of flows.entries()){const [from,to,...rest]=line.trim().split(/\s+/);if(rest.length||!hosts[from]||!hosts[to])throw Error('端末はA/B/Cです。');time+=index===2?p.gap:1;for(const table of Object.values(tables))for(const [key,e]of table)if(time-e.seen>=60)table.delete(key);const source=hosts[from],target=hosts[to],queue=[{sw:source.switch,ingress:from,depth:0}],frameId=index+1;delivered[frameId]=0;const frameRows=[];
 while(queue.length&&frameRows.length<100){const event=queue.shift(),table=tables[event.sw],key=source.vlan+':'+source.mac;if(p.learn)table.set(key,{port:event.ingress,seen:time});const destination=table.get(source.vlan+':'+target.mac),ports=[...links.filter(link=>link.includes(event.sw)).map(link=>link.find(x=>x!==event.sw)),...Object.keys(hosts).filter(id=>hosts[id].switch===event.sw)],selected=destination?[destination.port]:ports;for(const port of selected){if(port===event.ingress)continue;if(switches.includes(port)){const edge=roles.find(e=>[e.a,e.b].includes(event.sw)&&[e.a,e.b].includes(port));if(p.stp&&!edge.forward)continue;queue.push({sw:port,ingress:event.sw,depth:event.depth+1});frameRows.push([frameId,event.sw,port,source.vlan,'trunk: 802.1Qタグ',destination?'unicast':'flood']);transfers++;}else if(hosts[port].vlan===source.vlan){if(port===to)delivered[frameId]++;frameRows.push([frameId,event.sw,port,source.vlan,port===to?'宛先が受信':'MAC不一致で破棄',destination?'unicast':'flood']);}}}
 if(queue.length){limited=true;queue.length=0;}rows.push(...frameRows);frames.push(F(`${from} → ${to} / 時刻${time}s`,'access portでは端末のVLANへ所属させ、trunkではVIDをタグで運びます。受信側端末は自分宛てでないフレームを捨てます。',K.table(['frame','送信switch','出力port','VID','区間の扱い','選択'],frameRows)));frames.push(F('送信後のMAC転送表','IPアドレスではなく、VIDとMACの組から出力ポートを引きます。',K.table(['switch','VID:MAC','port','残り秒'],switches.flatMap(sw=>[...tables[sw]].map(([key,e])=>[sw,key,e.port,60-(time-e.seen)])))));}
 const nodes=[...switches.map(id=>({id,label:id,value:id===p.root?'root':'bridge'})),...Object.entries(hosts).map(([id,x])=>({id,label:'端末 '+id,value:'VLAN '+x.vlan}))],edges=[...roles.map(e=>({from:e.a,to:e.b,off:p.stp&&!e.forward,label:p.stp&&!e.forward?'待機':'trunk'})),...Object.entries(hosts).map(([id,x])=>({from:id,to:x.switch,label:'access '+x.vlan}))];frames.push(F('転送できる構成を確認する','同じVLANであること、STPで使える経路があること、宛先のMACが一致することは別の条件です。',K.graph(nodes,edges)));return out(frames,{'スイッチ間転送回数':transfers,'宛先への到着合計':K.sum(Object.values(delivered)),'重複到着':K.sum(Object.values(delivered).map(n=>Math.max(0,n-1))),'安全上限で停止':limited,'最終時刻s':time});});
D(96,{
 title:'ARP・NDP・DHCP・SLAACの状態と有効期間',question:'一度取得したアドレスや近隣情報を、いつまで使える？',
 scope:'単一クライアントのDHCP DORA・T1/T2・期限切れ、ARP cache、IPv6 DAD・preferred/valid lifetime、NDP reachabilityの時間イベントを計算。実端末の設定は変更しません。',
 controls:[s('mode','仕組み','dhcp',[['dhcp','DHCP'],['arp','ARP'],['slaac','SLAACとDAD'],['ndp','IPv6近隣到達性']]),r('elapsed','観測する時刻',100,0,240,5,'s'),r('lifetime','有効期間',60,30,180,30,'s'),K.b('serverDown','更新・確認の応答が返らない',false),K.b('duplicate','同じアドレスの端末がいる',false)],
 alt:['更新の応答が返らない条件にする',{serverDown:true}],
 intro:['ネットワークに接続したときの情報は、いつまでも正しいとは限りません。アドレスの利用期限と、相手へ届くかの確認を別に考えます。','DHCPは貸出しを更新し、ARPやNDPは近隣の対応や到達性を管理します。SLAACでは同じアドレスがないかを確認し、利用を優先する期間と有効な期間を分けます。','DHCPで取得した後、半分の時点T1で更新を試みます。応答がない場合はT2、さらに期限切れへ進み、古いアドレスを使い続けません。','応答なしへ切り替え、時刻を前後させて状態を比較します。SLAACでは重複が見つかった場合と、期限でdeprecatedになる場合を分けて見られます。','時間値は教材用です。ARPのキャッシュ方針やNDPのタイマーは実装・設定で異なり、表示する秒数を普遍的な規格定数とは扱いません。'],
 topics:[['DHCP T1/T2','unicast更新とbroadcast再束縛を別時点で行います。'],['ARPの期限','IPv4→MACの対応を再確認する必要があります。'],['DAD','使用前に重複がないか調べます。'],['preferred/valid','新規通信へ推奨しない状態と、使用できない状態を分けます。'],['NDP状態','REACHABLEからSTALE・DELAY・PROBEへ進み確認します。']],
 quiz:['SLAACでpreferred lifetimeだけが切れた場合は？','deprecatedになり、valid期限までは既存利用が可能な場合がある','ただちに全情報が必ず消える','アドレスが別の値へ自動で変わる','利用の優先度と有効性は別の期限です。']
},p=>{const events=[],add=(time,state,message)=>events.push({time,state,message});let state='未開始',address='なし';if(p.mode==='dhcp'){add(0,'INIT','DISCOVERをbroadcast');add(1,'SELECTING','OFFERを受信');add(2,'REQUESTING','選んだserverへREQUEST');if(p.duplicate){add(3,'DECLINED','重複を検出しDECLINE、利用しない');}else{let start=3;add(start,'BOUND','ACKからlease開始');for(let cycle=0;cycle<20&&start<=p.elapsed;cycle++){const t1=start+p.lifetime*.5,t2=start+p.lifetime*.875,expiry=start+p.lifetime;add(t1,'RENEWING','元serverへunicast更新');if(!p.serverDown){add(t1+1,'BOUND','更新ACKでleaseを再開始');start=t1+1;}else{add(t2,'REBINDING','どのserverでもよいbroadcast更新');add(expiry,'INIT','期限切れ。アドレスの利用を停止');break;}}}}else if(p.mode==='arp'){add(0,'EMPTY','対応をまだ知らない');add(1,'INCOMPLETE','誰が192.0.2.20かbroadcast');if(!p.serverDown){add(2,'VALID',p.duplicate?'異なるMACから複数の応答。矛盾を報告':'応答からMAC対応を保存');add(2+p.lifetime,'EXPIRED','教材のcache期限で再確認が必要');}else add(4,'FAILED','応答が得られず未解決');}else if(p.mode==='slaac'){add(0,'TENTATIVE','RA prefixから候補を作る');add(1,'DAD','送信元::のNSで重複を確認');if(p.duplicate)add(2,'DUPLICATE','既存端末から応答。使用しない');else{add(2,'PREFERRED','重複なし。優先利用可能');add(2+p.lifetime/2,'DEPRECATED','preferred期限切れ、新規の選択では避ける');add(2+p.lifetime,'INVALID','valid期限切れ、利用停止');}}else{add(0,'INCOMPLETE','NSで近隣を解決');if(p.serverDown)add(3,'FAILED','NAがなく解決失敗');else{add(1,'REACHABLE','NAでMACと到達性を確認');add(1+p.lifetime/2,'STALE','確認済み期間を越える');add(2+p.lifetime/2,'DELAY','データ送信時に上位層の確認を待つ');add(7+p.lifetime/2,'PROBE','NSで再確認');add(8+p.lifetime/2,'REACHABLE','NAで再確認できた');}}const visible=events.filter(e=>e.time<=p.elapsed).sort((a,b)=>a.time-b.time);state=visible.at(-1)?.state||'未開始';if(p.mode==='dhcp'&&['BOUND','RENEWING','REBINDING'].includes(state))address='192.0.2.10';if(p.mode==='slaac'&&['PREFERRED','DEPRECATED'].includes(state))address='2001:db8::10';const frames=visible.map((e,i)=>F(`${q(e.time)}s: ${e.state}`,e.message+'。観測時刻に達したイベントだけを反映しています。',K.table(['時刻s','状態','発生したこと'],visible.slice(0,i+1).map(x=>[q(x.time),x.state,x.message]))));if(!frames.length)frames.push(F('まだ動作していません','時刻を進めて問い合わせや有効期間を確認してください。',K.cells([{label:'状態',values:[state]}])));frames.push(F('観測時点の状態','同じアドレスを持つことと、今そのアドレスを使用してよいことを区別します。',K.table(['仕組み','時刻s','現在状態','利用するアドレス'],[[p.mode,p.elapsed,state,address]])));return out(frames,{'状態':state,'利用アドレス':address,'経過s':p.elapsed,'発生イベント数':visible.length,'重複条件':p.duplicate});});
D(97,{
 title:'IPヘッダー・TTL・ICMP・断片化・経路MTU',question:'小さな回線を通れないパケットは、どうやって送る？',
 scope:'3ルーター経路でIPv4/IPv6のサイズとTTL/Hop Limitを検査。IPv4の8byte単位断片化とchecksum、DF時のICMP、IPv6 PTB後の送信元分割を計算します。',
 sources:['rfc8200','rfc9293'],
 controls:[s('version','IPの版',4,[4,6]),r('payload','IPに渡すデータ量',2000,100,6000,100,'byte'),r('mtu','途中のMTU',1280,80,1500,20,'byte'),r('ttl','TTL / Hop Limit',4,1,8),K.b('df','IPv4のDFを立てる',true),K.b('discover','ICMPを受けて送信元で調整',true)],
 alt:['送信元の経路MTU調整を止める',{discover:false}],
 intro:['送信元の回線で送れる大きさでも、途中の回線では通れない場合があります。どの機器が分割し、誰がサイズを学ぶかを区別します。','TTL/Hop Limitは中継ごとに減り、0なら破棄します。IPv4では条件によりルーターが断片化できますが、IPv6のルーターは断片化せずPTBを返します。','2000byteを途中MTU1280の経路へ送ります。DFを立てるとそのまま通せず、通知を受けた送信元が送るサイズを調整します。','調整を止める条件と、IPv4でDFを外す条件を比べます。TTLを1にすると大きさ以前に中継回数の制限で止まります。','IPv6のMTUは規格上の下限1280を考慮し、それ未満の設定はリンク層側の分割が必要な異常設定として報告します。ICMPが届かない問題は別の障害です。'],
 topics:[['IPヘッダー','長さ、プロトコル、識別、TTL、宛先などの役割を分けます。'],['ICMP','配送不能やTTL超過を送信元へ通知します。'],['断片化','IPv4のoffsetは8byte単位で、元のデータの位置を表します。'],['PMTUD','途中の上限を通知から学び、送信元がサイズを調整します。']],
 quiz:['IPv6ルーターでMTUを越えた場合は？','その場でIP断片化せず、送信元へPTBで知らせる','すべてのルーターが必ず半分に切る','Hop Limitを増やして送る','断片化する主体とエラー通知を区別します。']
},p=>{const header=Number(p.version)===4?20:40,frames=[],hops=[1500,p.mtu,1400];let ttl=p.ttl,outcome='配送可能',size=header+p.payload,fragments=[],notifications=[];if(Number(p.version)===6&&p.mtu<1280)outcome='IPv6リンクMTUの前提を満たさない';else for(let i=0;i<hops.length;i++){ttl--;frames.push(F(`ルーター${i+1}: 残り${ttl}`,'受信したパケットの上限と中継回数を確認します。TTLを0にして転送し続けることはありません。',K.table(['IP長','リンクMTU','TTL/Hop Limit'],[[size,hops[i],ttl]])));if(ttl===0){outcome='ICMP Time Exceeded';notifications.push('TTL超過');break;}if(size>hops[i]){if(Number(p.version)===4&&!p.df){const unit=Math.floor((hops[i]-20)/8)*8;fragments=[];for(let start=0;start<p.payload;start+=unit){const bytes=Math.min(unit,p.payload-start),more=start+bytes<p.payload,packet=K.ipv4Bytes({ttl,payload:bytes,id:0x42,offset:start/8,more});fragments.push([fragments.length+1,start/8,bytes,more,packet.slice(10,12).map(x=>x.toString(16).padStart(2,'0')).join('')]);}size=20+Math.min(unit,p.payload);outcome='IPv4を断片化して配送';}else{notifications.push(Number(p.version)===4?'Destination Unreachable / Fragmentation Needed':'Packet Too Big');if(!p.discover){outcome='サイズ調整なしで停止';break;}const minimum=Math.min(...hops),unit=minimum-header;fragments=[];for(let start=0;start<p.payload;start+=unit)fragments.push([fragments.length+1,'別のIPパケット',Math.min(unit,p.payload-start),false,'送信元で再構成']);size=header+Math.min(unit,p.payload);outcome='送信元が小さい単位へ調整して配送';}}}if(fragments.length)frames.push(F('分割した単位と元データの位置','IPv4断片のoffsetと、送信元で別パケットに分けた場合を区別します。ここではIPに渡すデータ全体を扱い、TCPのMSS計算は別表示にします。',K.table(['番号','offset(8byte単位)','データ長','MF','checksum/扱い'],fragments)));if(Number(p.version)===4){const bytes=K.ipv4Bytes({ttl:p.ttl,payload:p.payload,id:0x42,df:p.df});frames.push(F('20byteのIPv4ヘッダーを読む','checksumはこのヘッダーから1の補数和で計算しています。値を変えると実際のビット列も変わります。',K.bits([{label:'ヘッダー各byte(16進)',values:bytes.map(x=>x.toString(16).padStart(2,'0'))}])));}return out(frames.length?frames:[F('前提を確認してください',outcome,K.cells([{label:'判定',values:[outcome]}]))],{'結果':outcome,'残りTTL':ttl,'分割した単位数':fragments.length||1,'通知':notifications.join(' / ')||'なし','TCP用MSS上限':Math.max(0,Math.min(...hops)-header-20)});});
const dnsRecords=[{name:'www.example.test',type:'CNAME',value:'app.example.test',ttl:60},{name:'app.example.test',type:'A',value:'192.0.2.10',ttl:60},{name:'app.example.test',type:'AAAA',value:'2001:db8::10',ttl:90},{name:'example.test',type:'MX',value:'10 mail.example.test',ttl:120},{name:'mail.example.test',type:'A',value:'192.0.2.20',ttl:120},{name:'example.test',type:'TXT',value:'classroom example',ttl:30}];
function resolveTeachingDNS(records,query,type){const chain=[],answers=[],seen=new Set();let name=query.toLowerCase().replace(/\.$/,'');for(let i=0;i<10;i++){if(seen.has(name))throw Error('CNAMEが循環しています。');seen.add(name);if(name!=='example.test'&&!name.endsWith('.example.test'))return {status:'REFUSED（教材のzone外）',answers:[],chain,ttl:0};const list=records.filter(r=>r.name.toLowerCase().replace(/\.$/,'')===name),matched=list.filter(r=>r.type.toUpperCase()===type);if(matched.length){answers.push(...matched);return {status:'NOERROR',answers,chain,ttl:Math.min(...answers.map(x=>x.ttl))};}const cname=list.find(r=>r.type.toUpperCase()==='CNAME');if(cname){answers.push(cname);chain.push([name,'CNAME',cname.value]);name=cname.value.toLowerCase().replace(/\.$/,'');continue;}return {status:list.length?'NOERROR / NODATA':'NXDOMAIN',answers,chain,ttl:30};}throw Error('CNAMEの段数が教材上限を超えました。');}
K.resolveTeachingDNS=resolveTeachingDNS;
D(98,{
 title:'DNSの委任・権威・CNAME・否定応答のキャッシュ',question:'レコードを書き換えても、すぐ新しい答えにならないのは？',
 scope:'root→test→example.testの委任と、編集可能なzone内のA/AAAA/MX/TXT/CNAMEを解決。再帰resolverの正・負キャッシュを時刻で比較します。外部DNSは問い合わせません。',
 sources:['rfc1034'],
 controls:[t('query','問い合わせる名前','www.example.test'),s('type','レコード種別','A',['A','AAAA','MX','TXT','CNAME']),code('records','権威サーバーのレコードJSON',JSON.stringify(dnsRecords,null,2)),r('time','2回目の問い合わせ時刻',20,0,180,5,'s'),K.b('change','最初の問い合わせ後にAを変更する',true),K.b('missing','存在しない名前を問い合わせる',false)],
 alt:['キャッシュ期限後の80秒に問い合わせる',{time:80}],
 intro:['名前解決は一台の表だけを見るのではなく、担当するサーバーをたどります。一度得た答えを再利用するため、更新が見える時点にも差が生まれます。','親zoneは子の担当を委任し、権威サーバーが答えを持ちます。resolverはTTLの間だけ答えを使い、存在しないという応答にも期限を持たせます。','wwwからappへCNAMEをたどりAを得ます。その直後に権威側のAを変えても、20秒後は有効なcacheが残っています。','80秒へ進め、新しい権威側の値が使われるか確認します。存在しない名前ではNXDOMAIN、名前はあって種別がないときはNODATAを区別します。','委任と再帰は別の役割です。この教材はexample.testの小さなzoneに限定し、実際のインターネットへ問い合わせない安全な環境です。'],
 topics:[['再帰と反復','クライアントは解決を依頼し、resolverは担当先を順に問い合わせます。'],['委任と権威','親が子の担当を示し、子がzone内の答えを管理します。'],['レコードとCNAME','別名をたどる場合と、求めた種別の値を返す場合を分けます。'],['正・負キャッシュ','有効な値と存在しないという情報のどちらにも期限があります。']],
 quiz:['NXDOMAINとNODATAの違いは？','名前がない場合と、その名前に求めた種別がない場合','どちらも常にネットワーク切断','どちらも必ずAレコードを返す','DNS応答の意味と通信障害を分けて読みます。']
},p=>{let records;try{records=JSON.parse(p.records);}catch{throw Error('レコードはJSON配列です。');}if(!Array.isArray(records)||records.length>40||records.some(x=>!x||typeof x.name!=='string'||typeof x.type!=='string'||typeof x.value!=='string'||!Number.isFinite(x.ttl)||x.ttl<0))throw Error('name/type/value/非負ttlを持つ40件以下のレコードです。');const query=p.missing?'absent.example.test':p.query,first=resolveTeachingDNS(records,query,p.type),changed=records.map(x=>p.change&&x.type.toUpperCase()==='A'?{...x,value:'192.0.2.99'}:{...x}),hit=p.time<first.ttl,second=hit?first:resolveTeachingDNS(changed,query,p.type),frames=[F('担当するzoneをたどる','この3段は小さな教材DNSの委任です。resolverが反復的に担当先を問い合わせます。',K.table(['問い合わせ元','問い合わせ先','答えの役割'],[['client','resolver','再帰的な解決を依頼'],['resolver','root','.testの委任'],['resolver','.test','example.testの委任'],['resolver','example.test権威','レコードまたは否定応答']])),F('最初の解決結果','CNAMEを含めてたどった先の値を保存します。複数段の実装を簡単化し、この結果集合には最短TTLを使います。',K.table(['名前','種別','値','TTL'],first.answers.length?first.answers.map(x=>[x.name,x.type,x.value,x.ttl]):[[query,p.type,first.status,first.ttl]])),F(`${p.time}sの問い合わせ: ${hit?'cache':'権威へ再確認'}`,'cacheが有効なら権威の新しい値をこの時点では読みません。期限切れなら更新後のレコードを使います。',K.table(['名前','種別','値'],second.answers.length?second.answers.map(x=>[x.name,x.type,x.value]):[[query,p.type,second.status]]))];return out(frames,{'2回目はcache':hit,'応答状態':second.status,'最終回答':second.answers.map(x=>x.value).join(' → ')||second.status,'cache残り秒':Math.max(0,first.ttl-p.time),'問い合わせ名':query});});
function tcpFlow(options){
 const bytes=options.bytes,mss=options.mss,window=options.window*mss,rtt=options.rtt,initialRTO=options.rto,segments=[];for(let offset=0;offset<bytes;offset+=mss)segments.push({index:segments.length+1,seq:1001+offset,len:Math.min(mss,bytes-offset),sent:0,retransmitted:false});
 const events=[],trace=[],received=new Map(),sacked=new Set();let time=0,una=1001,next=0,expected=1001,dups=0,retx=0,lossUsed=false,ackLoss=false,timerGeneration=0,rto=initialRTO,srtt=null,variation=null,state='SYN_SENT';
 const record=(from,to,flags,seq,ack,note,sack='')=>trace.push({time:q(time),from,to,flags,seq,ack,note,sack,una,expected,rto:q(rto),state});
 record('client','server','SYN',1000,0,options.loss==='syn'?'最初のSYNを失う':'接続を要求');if(options.loss==='syn'){time+=rto;record('client','server','SYN',1000,0,'同じSYNを再送');retx++;}time+=rtt/2;record('server','client','SYN,ACK',7000,1001,'server: SYN_RECEIVED');time+=rtt/2;state='ESTABLISHED';record('client','server','ACK',1001,7001,'SYNも順序番号を1消費する');
 const schedule=(at,type,data)=>events.push({at,type,data});
 function arm(){if(una>=1001+bytes)return;const generation=++timerGeneration;schedule(time+rto,'timer',{generation,una});}
 function send(segment,retransmission=false){segment.sent=time;if(retransmission){segment.retransmitted=true;retx++;}record('client','server','ACK,DATA',segment.seq,7001,(retransmission?'再送 ':'')+segment.len+' byte');if(options.loss==='data'&&!lossUsed&&segment.index===options.lossSegment){lossUsed=true;record('network','—','DROP',segment.seq,0,'このデータだけを1回落とす');}else schedule(time+rtt/2,'data',{segment});}
 function pump(){while(next<segments.length&&segments[next].seq+segments[next].len<=una+window){send(segments[next]);next++;}}
 pump();arm();let work=0;
 while(events.length&&una<1001+bytes&&work++<600){events.sort((a,b)=>a.at-b.at);const event=events.shift();time=event.at;
  if(event.type==='data'){const segment=event.data.segment;if(segment.seq>=expected)received.set(segment.seq,segment.len);while(received.has(expected)){const size=received.get(expected);received.delete(expected);expected+=size;}const blocks=[...received].sort((a,b)=>a[0]-b[0]).map(([seq,len])=>[seq,seq+len]),sack=options.sack?blocks.map(x=>x.join('–')).join(','):'';record('server','client','ACK',7001,expected,'次に必要なbyte位置を返す',sack);if(options.loss==='ack'&&!ackLoss){ackLoss=true;record('network','—','DROP ACK',7001,expected,'応答だけを1回落とす');}else schedule(time+rtt/2,'ack',{ack:expected,blocks:options.sack?blocks:[]});}
  else if(event.type==='ack'){const {ack,blocks}=event.data;for(const segment of segments)if(blocks.some(([a,b])=>segment.seq>=a&&segment.seq+segment.len<=b))sacked.add(segment.seq);if(ack>una){const sample=segments.slice(0,next).find(s=>s.seq+s.len===ack&&!s.retransmitted);if(options.adaptive&&sample){const measured=time-sample.sent;if(srtt===null){srtt=measured;variation=measured/2;}else{variation=.75*variation+.25*Math.abs(srtt-measured);srtt=.875*srtt+.125*measured;}rto=Math.max(200,srtt+4*variation);}una=ack;dups=0;pump();arm();}else if(ack===una){dups++;if(dups===3){const missing=segments.find(s=>s.seq===una);if(missing){send(missing,true);arm();}}}record('client','—','ACK処理',0,ack,'累積ACKと未確認範囲を更新');}
  else if(event.data.generation===timerGeneration&&event.data.una===una){const missing=segments.find(s=>s.seq===una);if(missing){rto=Math.min(rto*2,16000);send(missing,true);arm();record('client','—','RTO',missing.seq,0,'最古の未確認データを再送しRTOを伸ばす');}}
 }
 if(una===1001+bytes){timerGeneration++;if(options.close==='reset'){state='CLOSED';record('client','server','RST',una,7001,'接続を中止する');}else{state='FIN_WAIT_1';record('client','server','FIN,ACK',una,7001,'送信方向を閉じる');time+=rtt/2;record('server','client','ACK',7001,una+1,'server: CLOSE_WAIT');time+=rtt/2;state='FIN_WAIT_2';if(options.close==='graceful'){record('server','client','FIN,ACK',7001,una+1,'server: LAST_ACK');time+=rtt/2;state='TIME_WAIT';record('client','server','ACK',una+1,7002,'遅れたsegmentに備えTIME_WAIT');}}}
 return {trace,bytesDelivered:expected-1001,acknowledged:una-1001,retransmissions:retx,state,work,rto,srtt,complete:una===1001+bytes};
}
K.tcpFlow=tcpFlow;
D(99,{
 title:'TCPのbyte番号・SACK・再送タイマー・接続終了',question:'ACKの番号は、届いたパケットの個数？',
 scope:'最大2400byteの離散イベントTCP教材。SYN/FIN、byte単位SEQ/ACK、window、1回の損失、重複ACK、SACK範囲、RTO・Karn条件つきRTT推定を計算。輻輳制御は別単元です。',
 controls:[r('bytes','送るbyte数',1200,200,2400,200),r('mss','1segmentのデータ量',200,100,400,100),r('window','送信window(segment)',4,1,6),r('rtt','往復時間',100,20,200,20,'ms'),r('rto','最初のRTO',400,200,1000,100,'ms'),s('loss','1回だけ落とすもの','data',[['none','落とさない'],['data','データ'],['ack','ACK'],['syn','SYN']]),r('lossSegment','落とすデータ番号',2,1,6),K.b('sack','SACKの到着範囲を返す',true),K.b('adaptive','RTTからRTOを更新する',true),s('close','終わり方','graceful',[['graceful','両方向を閉じる'],['half','片方向だけ閉じる'],['reset','RSTで中止']])],
 alt:['損失なしの通信と比較する',{loss:'none'}],
 intro:['TCPはアプリにbyte列を順番どおり渡します。途中を失っても後ろだけ届くことがあり、受信した範囲とアプリへ渡せる範囲を分ける必要があります。','SEQは先頭byteの位置、累積ACKは次に必要なbyteの位置です。SACKはその先で受信済みの範囲を知らせ、送信側は未確認のデータと再送時刻を管理します。','200byteずつ送る例で2番目だけを落とします。後ろが届いても累積ACKは欠けた先頭へ留まる様子と、SACKの範囲を確認してください。','損失をなくすと同じデータが少ない再送で届きます。ACKやSYNだけの喪失、window、RTT、終了方式を切り替えて状態も比較できます。','RTOの下限200msなどは教材用の選択です。実機実装や全RFCオプション、番号のwrap、輻輳制御の詳細を再現したものではありません。'],
 topics:[['SEQ・累積ACK','番号はpacket個数でなくbyte位置です。SYN/FINも1を消費します。'],['SACK','累積ACKより先の到着範囲を示します。'],['RTT・RTO','再送で曖昧になった標本を避け、変動も含めてタイマーを更新します。'],['fast retransmit','同じACKが続くことから失われた先頭の再送を試みます。'],['half-close・TIME_WAIT','送信方向の終了と両方向の終了を区別します。']],
 quiz:['先頭SEQ1001から200byteが順番に届いた後のACKは？','1201','1002','200','次に必要なbyte位置なので1001+200になります。'],
 tests:[[{},{'アプリへ届いたbyte':1200,'全byte確認済み':true}],[{loss:'none'},{'再送回数':0}]]
},p=>{const run=tcpFlow(p),sample=run.trace.filter((_,i)=>i<10||i%2===0||i===run.trace.length-1),frames=sample.map((e,i)=>F(`${e.time}ms: ${e.flags}`,e.note+'。受信側の次の必要位置と送信側の未確認先頭は、ACKが届くまで同じとは限りません。',K.table(['時刻ms','from→to','flags','SEQ','ACK','SACK','意味'],run.trace.slice(0,run.trace.indexOf(e)+1).map(x=>[x.time,x.from+'→'+x.to,x.flags,x.seq||'—',x.ack||'—',x.sack||'—',x.note])),{'送信側UNA':e.una,'受信側NEXT':e.expected,'RTO':e.rto,'状態':e.state})));return out(frames,{'アプリへ届いたbyte':run.bytesDelivered,'全byte確認済み':run.complete,'再送回数':run.retransmissions,'終了時のclient状態':run.state,'最終RTOms':q(run.rto),'SRTTms':run.srtt===null?'標本なし':q(run.srtt)});});
D(100,{
 title:'受信window・輻輳window・送信量の制約',question:'送れない理由は、受信側が遅いから？ 回線が混んでいるから？',
 scope:'30ラウンドのsegment粒度モデル。受信バッファとアプリの読出し、cwndのslow start/AIMD、有限リンク容量での損失、再送待ち、zero-window確認を分離して計算します。',
 controls:[r('count','送るsegment数',20,8,40),r('capacity','受信バッファ(segment)',6,2,12),r('drain','1ラウンドでアプリが読む量',1,0,4),r('link','1ラウンドの回線処理量',3,1,6),r('initialWindow','初期cwnd',4,1,8),K.b('resume','途中から受信アプリを速くする',false)],
 alt:['受信アプリの読出しを止める',{drain:0}],
 intro:['送信量には少なくとも2つの上限があります。相手が保存できる余裕と、途中のネットワークへ多く送り過ぎないための制御を分けます。','rwndは受信側の空き、cwndは送信側が混雑に合わせて決める量です。未確認のデータも差し引き、両方の制約を満たす範囲で送ります。','受信側は1ラウンドに1segmentしか読みません。回線容量を増やしても受信バッファが詰まる場合があることを観察してください。','読出しを0にするとrwndが閉じます。途中から再開する設定や、小さい回線に大量に送る設定を比べ、cwndが減る原因を区別します。','これは一定RTTを1ラウンドとする粒度の粗いモデルです。全TCP状態や正確なバイトごとのwindow更新は前のイベント教材と区別します。'],
 topics:[['フロー制御','受信アプリが消費できる量と空き領域を管理します。'],['輻輳制御','途中の損失を受けてcwndを調整します。'],['in flight','未確認のデータが既に上限を占めています。'],['zero window','相手の受入れ余裕が戻ることを確認します。']],
 quiz:['rwnd=0でも回線帯域だけ増やせば送れる？','受信側の空きが戻らなければ解決しない','帯域が増えれば必ず送れる','cwndを無限にすれば解決する','受信容量とネットワークの混雑は異なる制約です。']
},p=>{let next=1,ack=1,app=1,cwnd=p.initialWindow,ssthresh=8,losses=0,retransmits=0,probes=0;const buffer=new Set(),flight=new Map(),rows=[],frames=[];for(let round=0;round<30;round++){const consume=p.resume&&round>=10?4:p.drain;for(let k=0;k<consume&&buffer.has(app)&&app<ack;k++){buffer.delete(app);app++;}const rwnd=p.capacity-buffer.size,oldAck=ack,send=[],expired=[...flight].filter(([,time])=>round-time>=3).sort((a,b)=>a[0]-b[0]);if(expired.length){const [seq]=expired[0];ssthresh=Math.max(2,Math.floor(cwnd/2));cwnd=1;flight.set(seq,round);send.push(seq);retransmits++;}let allowance=Math.max(0,Math.floor(Math.min(cwnd,rwnd))-flight.size);while(allowance-->0&&next<=p.count){send.push(next);flight.set(next,round);next++;}if(rwnd===0)probes++;const accepted=send.slice(0,p.link);losses+=Math.max(0,send.length-p.link);for(const seq of accepted)if(seq<ack)flight.delete(seq);else if(buffer.size<p.capacity)buffer.add(seq);while(buffer.has(ack))ack++;for(const seq of [...flight.keys()])if(seq<ack)flight.delete(seq);const newly=ack-oldAck;if(newly>0)cwnd=cwnd<ssthresh?cwnd+newly:cwnd+newly/cwnd;cwnd=Math.min(cwnd,32);rows.push([round,send.join(',')||'—',Math.max(0,send.length-p.link),ack,buffer.size,rwnd,q(cwnd),flight.size,app-1]);frames.push(F(`ラウンド${round}: ${rwnd===0?'受信windowが0':'送信可能量を確認'}`,'rwnd、cwnd、flightを別々に示します。アプリが読んだbyte相当量と、通信として順番に届いた範囲も分離しています。',K.table(['round','送ったSEQ','回線損失','次ACK','buffer','通知rwnd','cwnd','flight','アプリ読了'],rows.slice())));if(app>p.count)break;}frames.push(F('2つのwindowの変化','同じ軸で受信側の空きと送信側の混雑制御を比較します。低下の理由が同じとは限りません。',K.plot([{name:'rwnd',points:rows.map(x=>({x:x[0],y:x[5]}))},{name:'cwnd',points:rows.map(x=>({x:x[0],y:x[6]}))}],{xLabel:'round',yLabel:'segment'})));return out(frames,{'順番に到着':ack-1,'アプリが読んだ数':app-1,'回線の損失':losses,'再送数':retransmits,'zero-window確認':probes,'送信完了':app>p.count});});
D(101,{
 title:'RIP・リンク状態・BGPの情報伝播と経路選択',question:'回線が切れたことを、全ルーターが同時に知る？',
 scope:'最大8頂点の同期ラウンドの距離ベクトル、sequence付きLSA flood＋SPF、AS-path-vectorを比較。RIPは上限16、OSPFは単一areaの基本動作、BGPは単一prefixの方針選択です。',
 controls:[code('graph','リンク（A B cost）','A B 1\nA C 2\nB C 1\nB D 4\nC D 1'),s('protocol','方式','linkstate',[['rip','距離ベクトル・RIP'],['linkstate','リンク状態・OSPFの基礎'],['bgp','path vector・BGP']]),t('destination','宛先','D'),t('failed','収束後に切るリンク','C D'),K.b('poison','RIPでpoison reverse',true),r('preference','AからBへのlocal preference',100,50,250,50)],
 alt:['同じ変更を距離ベクトルで伝える',{protocol:'rip'}],
 intro:['パケットを転送するための経路表と、その経路情報を集める通信は別です。障害を近くで知った機器から、他の機器へ情報が届く過程を見ます。','距離ベクトルは宛先までの距離を隣へ知らせ、リンク状態は接続情報を広げて各自でSPFを計算します。BGPはAS経路と方針を基に候補を選びます。','Dへの経路が安定してからC-Dを切ります。各ラウンドのA/B/Cの次ホップと、障害後に情報が変わる順番を比較してください。','RIPへ変えると距離情報を繰り返し交換します。poison reverseやBGPのlocal preferenceを変更し、最短だけでない選択も確認できます。','OSPFのarea間要約やBGPの全属性を完全実装するものではありません。ここでは基本交換を計算し、複雑な規模では別の階層化・方針が必要なことも説明します。'],
 topics:[['距離ベクトル','隣の距離へ自分からのコストを足し、古い情報による問題を考えます。'],['LSAとSPF','新しいsequenceの接続情報を広げてから経路を再計算します。'],['隣接・障害検出','経路変更が届くまで、各機器が異なる知識を持ちます。'],['BGP','AS_PATHのループを拒否し、local preference等の方針で選びます。'],['階層化','OSPFのareaとABRの要約は、広げる詳細情報の範囲を分ける考え方です。']],
 quiz:['リンク状態方式では、誰がSPFを計算する？','接続情報を受け取った各ルーター','rootのDNSサーバーだけ','宛先端末が全経路を直接書き込む','接続情報の共有と、各機器での計算を分けます。']
},p=>{const g=K.graphInput(p.graph,false);if(g.nodes.length>8||g.edges.some(e=>e.cost<=0))throw Error('最大8頂点、正のリンクコストです。');if(!g.nodes.includes(p.destination))throw Error('宛先をグラフ内の頂点名にしてください。');const failure=p.failed.trim().split(/\s+/);if(failure.length!==2)throw Error('切るリンクはC Dのように両端を指定します。');const frames=[],allRows=[],ids=g.nodes;let edges=g.edges.slice(),vectors=Object.fromEntries(ids.map(id=>[id,{distance:id===p.destination?0:16,next:null,path:id===p.destination?[id]:[]} ])),lsa=Object.fromEntries(ids.map(id=>[id,new Map([[id,{seq:1,edges:edges.filter(e=>e.a===id||e.b===id)}]])]));
 const neighbors=id=>edges.filter(e=>e.a===id||e.b===id).map(e=>({id:e.a===id?e.b:e.a,cost:e.cost}));
 const routeRound=()=>{if(p.protocol==='linkstate'){const next=Object.fromEntries(ids.map(id=>[id,new Map(lsa[id]) ]));for(const id of ids)for(const neighbor of neighbors(id))for(const [origin,record]of lsa[neighbor.id])if(!next[id].has(origin)||next[id].get(origin).seq<record.seq)next[id].set(origin,record);lsa=next;const out={};for(const id of ids){const known=[];for(const [origin,record]of lsa[id])for(const e of record.edges){const other=e.a===origin?e.b:e.a,back=lsa[id].get(other);if(back?.edges.some(x=>(x.a===e.a&&x.b===e.b)||(x.a===e.b&&x.b===e.a))&&!known.some(x=>[x.a,x.b].includes(e.a)&&[x.a,x.b].includes(e.b)))known.push(e);}const r=L.shortest(ids,known,id,p.destination);out[id]={distance:Number.isFinite(r.dist[p.destination])?r.dist[p.destination]:'∞',next:r.path[1]||'—',path:r.path};}return out;}const old=vectors,next={};for(const id of ids){if(id===p.destination){next[id]={distance:0,next:null,path:[id]};continue;}const candidates=neighbors(id).flatMap(n=>{const v=old[n.id];if(p.protocol==='rip'){const advertised=p.poison&&v.next===id?16:v.distance;return [{distance:Math.min(16,advertised+1),next:n.id,path:[]}];}if(!v.path.length||v.path.includes(id))return [];return [{distance:v.path.length,next:n.id,path:[id,...v.path],pref:id==='A'&&n.id==='B'?p.preference:100}];});candidates.sort((a,b)=>p.protocol==='bgp'?(b.pref-a.pref)||a.path.length-b.path.length||a.next.localeCompare(b.next):a.distance-b.distance||a.next.localeCompare(b.next));next[id]=candidates[0]||{distance:16,next:null,path:[]};if(p.protocol==='rip'&&next[id].distance>=16)next[id]={distance:16,next:null,path:[]};}vectors=next;return next;};
 let final={};for(let round=0;round<24;round++){if(round===8){edges=edges.filter(e=>!([e.a,e.b].includes(failure[0])&&[e.a,e.b].includes(failure[1])));for(const id of failure)if(lsa[id])lsa[id].set(id,{seq:2,edges:edges.filter(e=>e.a===id||e.b===id)});}const routes=routeRound();final=routes;const rows=ids.map(id=>[round,id,routes[id].distance,routes[id].next||'—',routes[id].path.join(' → ')||'—',p.protocol==='linkstate'?[...lsa[id]].map(([id,r])=>id+':'+r.seq).join(','):'隣接交換']);allRows.push(...rows);if(round<4||round>=8&&round<16||round===23)frames.push(F(`ラウンド${round}${round===8?'：リンクを切断':''}` ,round<8?'最初は自分と隣の情報から収束へ向かいます。':'変更を知った近隣から情報が伝わります。RIPの16は到達不能を表し、実際のコスト16と区別します。',K.table(['round','router','宛先までの距離','next hop','AS/path','知っているLSA'],rows)));}
 frames.push(F('最終的な経路を比較する','方針による選択とリンクの短さを同じ基準だと思わないでください。',K.graph(ids.map(id=>({id,label:id,value:'next '+(final[id]?.next||'—')})),edges.map(e=>({from:e.a,to:e.b,label:e.cost})))));return out(frames,{'方式':p.protocol,'Aの次ホップ':final.A?.next||'なし','Aからの距離':final.A?.distance??'Aなし','更新ラウンド数':24,'local preference':p.preference});});
})();
