/* GAP-074..081. Discrete operating-system state, isolated from the host OS. */
(() => {
'use strict';
const L=CSL,K=L.curriculum,{define:D,f:F,result:out,r,s,t,codeInput:code,round:q}=K;
D(74,{
 title:'プロセス・スレッド・システムコール',question:'同じプログラムでも、別の実行は何を共有する？',
 scope:'仮想的なfork・thread・exec・read/write・wait・exitを最大40操作で追跡。レジスタ、PC、アドレス空間、カーネルへの入出を分離した機能モデルです。',
 controls:[s('create','子の作り方','fork',[['fork','新しいプロセス'],['thread','同じプロセスのスレッド']]),r('initial','最初の共有値',5,0,30),r('childValue','子が書く値',9,0,30),K.b('exec','子の実行イメージを置き換える',false)],
 alt:['スレッドとして作り、書込みの共有を比較する',{create:'thread'}],
 intro:['プログラムのファイルと、それを今動かしている実行主体は別です。複数の主体を切り替えるとき、何を保存し、何を共有するかを調べます。','プロセスはアドレス空間などの資源を持ちます。スレッドは実行位置やレジスタを別に持ちながら同じプロセスのメモリを共有します。','親の変数x=5から子を作り、子がx=9を書きます。親へ戻ったときのxと、各主体のPC・レジスタの違いを見てください。','作り方をthreadへ変更します。execを有効にすると実行イメージが置き換わり、プロセスIDは残る一方でメモリとプログラムが変わります。','これはOSの機能モデルです。forkの実装を物理メモリの全コピーと断定せず、実際のCopy-on-Writeは別単元で扱います。'],
 topics:[['プロセス','独立したアドレス空間と資源を持つ実行の単位です。'],['スレッド','実行位置は別でも同じプロセスのメモリを共有します。'],['システムコール','ユーザーの要求でカーネル処理へ入り、結果を受け取って戻ります。'],['コンテキストスイッチ','PC・レジスタを保存し、別の実行主体の状態を復元します。'],['fork・exec・wait','生成、イメージ置換、子の終了待ちは別の操作です。']],
 quiz:['同じプロセスの2スレッドで通常共有されるのは？','プロセスのアドレス空間','それぞれのPCの値そのもの','すべてのスレッドの実行順序','各スレッドの実行状態と、プロセスの共有資源を分けます。'],
 tests:[[{},{'親が最後に読むx':5}],[{create:'thread'},{'親が最後に読むx':9}]]
},p=>{
 const memory1={id:'M1',x:p.initial},parent={tid:'T1',pid:1,pc:0,reg:0,state:'実行中',memory:memory1},tasks=[parent],frames=[];let child;
 const snapshot=(title,explain,mode='user')=>frames.push(F(title,explain,K.table(['TID','PID','PC','レジスタ','状態','メモリID','x'],tasks.map(x=>[x.tid,x.pid,x.pc,x.reg,x.state,x.memory.id,x.memory.x])),{'実行モード':mode}));
 snapshot('親が実行を始める','プログラムを読む位置PCと、メモリにある変数xを分けて表示します。');parent.pc++;
 snapshot('生成のシステムコールへ入る','ユーザープログラムが生成を要求し、カーネル側で実行主体と資源を準備します。','kernel');
 child={tid:'T2',pid:p.create==='thread'?1:2,pc:parent.pc,reg:0,state:'実行可能',memory:p.create==='thread'?memory1:{id:'M2',x:p.initial}};tasks.push(child);parent.reg=child.pid;
 snapshot('戻り値と資源を分ける','forkの子には戻り値0、親には子のPIDを返す教材です。threadでは同じメモリIDを参照します。');
 parent.state='終了待ち';child.state='実行中';snapshot('親を待機させ、子へ切り替える','親のPCとレジスタを保存したまま、子の状態を復元します。','kernel');
 child.pc++;child.memory.x=p.childValue;snapshot('子がxへ書き込む','同じメモリIDを持つ主体からは同じ変更が見えます。コピーされた別の空間なら影響しません。');
 if(p.exec){const pid=child.pid;const replacement={id:'EXEC'+pid,x:0};for(const task of tasks.filter(x=>x.pid===pid)){task.memory=replacement;task.pc=0;if(task!==child)task.state='execで終了';}snapshot('実行イメージを置き換える','PIDは維持し、プログラムとアドレス空間を置き換えます。同じプロセスの他スレッドは終了するモデルです。','kernel');}
 child.state='終了';snapshot('子がexitを呼ぶ','終了情報を記録し、待っている親が再開できる状態へ移します。','kernel');
 if(parent.state!=='execで終了'){parent.state='実行中';parent.pc++;parent.reg=parent.memory.x;snapshot('親がwaitから戻る','保存した実行位置から再開します。終了待ちの間にCPUを占有し続けるわけではありません。');}
 return out(frames,{'親が最後に読むx':parent.memory.x,'プロセス数':new Set(tasks.map(x=>x.pid)).size,'メモリ空間数':new Set(tasks.map(x=>x.memory.id)).size,'親の状態':parent.state});
});
function parseJobs(source){
 const jobs=String(source).trim().split('\n').filter(x=>x.trim()).map(line=>{const [id,a,bursts,pr='0',...rest]=line.trim().split(/\s+/),arrival=Number(a),priority=Number(pr),parts=(bursts||'').split('/').map(Number);if(rest.length||!/^[A-Za-z0-9_]{1,8}$/.test(id||'')||!Number.isInteger(arrival)||arrival<0||arrival>40||!Number.isInteger(priority)||priority<0||priority>9||!parts.length||parts.length>7||parts.length%2===0||parts.some(n=>!Number.isInteger(n)||n<1||n>20))throw Error('P1 0 4/3/2 1 の形式です。CPU/I/O/CPU、到着0〜40、優先度0〜9（小さい方が優先）。');return {id,arrival,priority,parts,status:'未到着',part:0,left:parts[0],wake:null,wait:0,first:null,finished:null,readyOrder:0};});if(!jobs.length||jobs.length>6||new Set(jobs.map(x=>x.id)).size!==jobs.length)throw Error('一意の仕事名を1〜6個指定してください。');return jobs;
}
function scheduleJobs(source,{policy='RR',quantum=2,cost=0,aging=false}={}){
 const jobs=parseJobs(source),timeline=[];let time=0,current=null,slice=0,order=0,last=null,switches=0;
 const awaken=()=>jobs.forEach(j=>{if(j.status==='未到着'&&j.arrival<=time||j.status==='I/O待ち'&&j.wake<=time){j.status='実行可能';j.readyOrder=order++;}});
 const tick=(label,selected=null)=>{jobs.forEach(j=>{if(j.status==='実行可能'&&j!==selected)j.wait++;});timeline.push({time,label,states:jobs.map(j=>({id:j.id,status:j===selected?'実行中':j.status,left:j.left,wait:j.wait,part:j.part}))});time++;};
 while(jobs.some(j=>j.finished===null)&&time<600){awaken();if(current&&(current.status!=='実行可能'||policy==='RR'&&slice>=quantum)){if(current.status==='実行可能')current.readyOrder=order++;current=null;slice=0;}
  const candidates=jobs.filter(j=>j.status==='実行可能');let selected=current;
  if(!current||['SRTF','Priority'].includes(policy))selected=candidates.sort((a,b)=>policy==='SJF'||policy==='SRTF'?a.left-b.left||a.readyOrder-b.readyOrder:policy==='Priority'?(a.priority-(aging?Math.floor(a.wait/5):0))-(b.priority-(aging?Math.floor(b.wait/5):0))||a.readyOrder-b.readyOrder:a.readyOrder-b.readyOrder)[0]||null;
  if(!selected){tick('idle');current=null;last=null;continue;}
  if(current!==selected)slice=0;current=selected;
  if(last!==null&&last!==selected.id){switches++;for(let k=0;k<cost;k++){tick('switch');awaken();}}
  if(selected.first===null)selected.first=time;selected.left--;slice++;tick(selected.id,selected);last=selected.id;
  if(selected.left===0){if(selected.part+1>=selected.parts.length){selected.status='終了';selected.finished=time;}else{selected.status='I/O待ち';selected.wake=time+selected.parts[selected.part+1];selected.part+=2;selected.left=selected.parts[selected.part];}current=null;slice=0;}
 }
 return {jobs,timeline,time,switches,complete:jobs.every(j=>j.finished!==null)};
}
K.scheduleJobs=scheduleJobs;
D(75,{
 title:'到着時刻・I/O・優先度を含むCPUスケジューリング',question:'後から短い仕事が来たら、途中の仕事を止める？',
 scope:'最大6仕事のFCFS/SJF/SRTF/RR/優先度方式を離散時間で実行。到着、I/O待機、切替えコスト、優先度のagingを含み、600tickで中断します。',
 controls:[code('jobs','仕事（名前 到着 CPU/IO/CPU 優先度）','P1 0 5/3/2 2\nP2 1 3 0\nP3 2 6 1'),s('policy','割当方式','RR',['FCFS','SJF','SRTF','RR','Priority']),r('quantum','RRの時間片',2,1,6),r('cost','切替えコスト',0,0,2),K.b('aging','待った時間で優先度を上げる',false)],
 alt:['最短残り時間で割り当てる',{policy:'SRTF'}],
 intro:['全ての仕事が同時に来るとは限らず、CPU以外の機器を待つ時間もあります。実行できる仕事だけを候補にして順番を決めます。','SJFは次のCPU仕事が短いものを選び、SRTFは途中でも残りが短いものを優先します。RRは時間片で交代し、交代そのものにも手間が掛かります。','P1の実行中にP2とP3が到着します。P1のI/O待ちの間は別の仕事を動かせるので、待ち時間の種類を状態表で分けてください。','SRTFへ変更し、最初の応答と完了までの時間を比較します。切替えコストを増やすと、頻繁に交代する方式がどのような影響を受けるか確認します。','この教材ではCPU・I/Oの所要時間を事前に与えます。現実のOSが将来の実行時間を完全に知っているという意味ではありません。'],
 topics:[['到着とready','まだ到着していない仕事やI/O待ちはCPU候補にしません。'],['プリエンプション','途中の実行を保存して別の仕事へ切り替えます。'],['応答・待ち・ターンアラウンド','最初に動くまで、readyで待つ時間、完了までを別集計します。'],['優先度とaging','長い待ちを反映して選ばれやすさを調整します。']],
 quiz:['I/O待ちの時間をCPUのready待ちに全て含めてよい？','実行できない待機なので別に数える','同じ待ちなので必ず同じ値','I/O待ちの仕事は常にCPUを使う','何を待っているかで資源と状態を分けます。'],
 tests:[[{jobs:'A 0 3 0\nB 1 2 0',policy:'FCFS'},{'完了時刻':5,'平均ready待ち':1}]]
},p=>{const run=scheduleJobs(p.jobs,p),frames=run.timeline.filter((_,i)=>i<8||i%Math.max(1,Math.ceil(run.timeline.length/40))===0||i===run.timeline.length-1).map(e=>F(`時刻${e.time}: ${e.label}`,'ready待ちは実行可能なのに割り当てられなかったtickです。I/Oと切替えも別の状態で表示します。',K.table(['仕事','状態','CPU残り','CPU/I/O列の位置','累積ready待ち'],e.states.map(x=>[x.id,x.status,x.left,x.part,x.wait]))));frames.push(F('割当の全時系列','switchは切替え、idleは実行可能な仕事がない時刻です。CPUとI/Oの待ちを混同しないでください。',K.cells([{label:'時刻0から',values:run.timeline.map(x=>x.label)}])));frames.push(F('各仕事を別々に評価する','完了時刻から到着時刻を引いた値がターンアラウンドです。最初の応答だけを見る場合とは評価が変わります。',K.table(['仕事','到着','初回','完了','応答時間','ready待ち','turnaround'],run.jobs.map(j=>[j.id,j.arrival,j.first??'未実行',j.finished??'未完了',j.first===null?'—':j.first-j.arrival,j.wait,j.finished===null?'—':j.finished-j.arrival]))));return out(frames,{'完了時刻':run.time,'平均ready待ち':q(K.mean(run.jobs.map(j=>j.wait))),'切替え回数':run.switches,'全仕事が完了':run.complete});});
D(76,{
 title:'パイプ・ファイル記述子・共有メモリ・シグナル',question:'空のパイプを読むことと、EOFを読むことは同じ？',
 scope:'容量4〜12文字の仮想パイプ、dup/close、blocking read/write、通知によるEINTRを実行。別モードでは共有メモリとメッセージのコピーの違いを扱います。',
 controls:[s('mode','通信方式','pipe',[['pipe','パイプ'],['shared','共有メモリ'],['message','メッセージのコピー']]),code('events','操作列','P2 read 3 2\nP1 write 4 abcd\nP2 read 3 4\nP1 close 4\nP2 read 3 1'),r('capacity','パイプ容量',4,4,12),K.b('interrupt','待機中にシグナルを入れる',false)],
 alt:['待機中にシグナルを送る',{interrupt:true}],
 intro:['別々のプロセスは、単に同じ変数名を書いても値を共有しません。OSが提供する通信の入口と、データがどこに置かれるかを確認します。','パイプはバイト列を順に渡します。空でも書き手が残るなら待機し、書き手が全て閉じた空のパイプならEOFになります。記述子はその入口を指す番号です。','P2が先にreadし、P1が後から文字を書きます。最初のreadが止まっていても、P1のwriteで再開する様子を追います。','シグナルを有効にすると、ここでは待機readをEINTRで戻す設定です。共有メモリとメッセージでは、送信後に値を変更した影響を比較できます。','パイプの1回のwriteと1回のreadが同じ区切りになるとは限りません。この教材のシグナルはreadを再開しない設定で、全OS設定の一般則ではありません。'],
 topics:[['ファイル記述子','小さな番号から、開いている通信・ファイルの入口を参照します。'],['パイプ・EOF','空で待つ条件と、もう届かないことを知らせるEOFを分けます。'],['共有とコピー','同じ保存場所を参照する場合と、送信時の内容を複製する場合を比べます。'],['シグナル','通常のデータとは別の通知で、待機が中断される場合があります。']],
 quiz:['空のパイプでEOFになる条件は？','開いている書き手がなく、残るデータもない','readする文字数が1である','一度でもreadが待機した','将来書き込める入口が残っているかが重要です。']
},p=>{if(p.mode!=='pipe'){const a={value:5},sent=p.mode==='shared'?a:{...a},frames=[F('送信時の状態','同じ物を参照するか、内容をコピーするかを区別します。',K.cells([{label:'送信側',values:[a.value]},{label:'受信側',values:[sent.value]}]))];a.value=9;frames.push(F('送信後に元の値を変更する','共有なら受信側からも同じ変更が見え、コピーなら送信時の値が残ります。',K.cells([{label:'送信側',values:[a.value]},{label:'受信側',values:[sent.value]}])));return out(frames,{'受信側の値':sent.value,'方式':p.mode,'シグナル設定':p.interrupt});}
 const fd={P1:new Map([[4,'W']]),P2:new Map([[3,'R']])},blocked=new Map(),buffer=[],outputs={P1:[],P2:[]},rows=[],frames=[];let turn=0;
 const writers=()=>Object.values(fd).reduce((n,m)=>n+[...m.values()].filter(x=>x==='W').length,0),readers=()=>Object.values(fd).reduce((n,m)=>n+[...m.values()].filter(x=>x==='R').length,0);
 function attempt(pid,op){if(op.kind==='read'){if(buffer.length){const data=buffer.splice(0,op.n).join('');outputs[pid].push(data);rows.push([turn,pid,'read再開',data]);return true;}if(!writers()){outputs[pid].push('EOF');rows.push([turn,pid,'read','EOF']);return true;}return false;}if(!readers()){rows.push([turn,pid,'write','EPIPE: 読み手なし']);return true;}while(op.text.length&&buffer.length<p.capacity)buffer.push(op.text.shift());if(op.text.length===0){rows.push([turn,pid,'write完了','全て渡した']);return true;}return false;}
 function service(){for(let k=0;k<8;k++){let progress=false;for(const [pid,op]of [...blocked])if(attempt(pid,op)){blocked.delete(pid);progress=true;}if(!progress)break;}}
 const lines=p.events.split('\n').filter(x=>x.trim());if(!lines.length||lines.length>40)throw Error('操作は1〜40行です。');for(const line of lines){turn++;const [pid,action,arg,value,...rest]=line.trim().split(/\s+/);if(!fd[pid]||rest.length)throw Error('P1/P2 と read/write/dup/close を指定します。');const number=Number(arg);if(blocked.has(pid)){rows.push([turn,pid,action,'このプロセスは待機中']);}else if(action==='read'||action==='write'){if(fd[pid].get(number)!==(action==='read'?'R':'W'))rows.push([turn,pid,action,'EBADF: 入口がない／向きが違う']);else{const op=action==='read'?{kind:'read',n:Number(value)}:{kind:'write',text:[...(value||'')]};if(action==='read'&&(!Number.isInteger(op.n)||op.n<1||op.n>20))throw Error('readの個数は1〜20です。');if(!attempt(pid,op)){blocked.set(pid,op);rows.push([turn,pid,action,'待機']);}}}else if(action==='close'){fd[pid].delete(number);rows.push([turn,pid,'close','残る書き手 '+writers()]);}else if(action==='dup'){const next=Number(value);if(!fd[pid].has(number)||!Number.isInteger(next)||next<0||next>10)throw Error('dupは存在する記述子と、新しい0〜10の番号です。');fd[pid].set(next,fd[pid].get(number));rows.push([turn,pid,'dup',number+' → '+next]);}else throw Error('操作はread / write / dup / closeです。');if(p.interrupt&&turn===1&&blocked.has('P2')){blocked.delete('P2');outputs.P2.push('EINTR');rows.push([turn,'P2','signal','readを中断']);}service();frames.push(F(`操作${turn}: ${line}`,'入口を閉じるときは参照数を減らします。dupした別番号が残っていれば書き手はまだ存在します。',K.table(['順','主体','操作／再開','結果'],rows.slice()),{'パイプ内容':buffer.join(''),'待機': [...blocked.keys()].join(',')||'なし','開いた書き手':writers()}));}return out(frames,{'P2の受信':outputs.P2.join(' | '),'残る文字数':buffer.length,'待機プロセス数':blocked.size,'書き手数':writers()});});
D(77,{
 title:'mutex・条件変数・waitと再確認',question:'起こされたら、欲しいデータが必ず残っている？',
 scope:'有界バッファのput/getと条件変数を操作列で実行。wait時のmutex解放、signal後の再獲得、述語while再確認と誤ったif、虚偽のwakeを比較します。',
 controls:[code('events','操作列','C1 get\nwake C1\nP put 7\nC2 get\nC1 resume\nP put 8\nC1 resume'),r('capacity','バッファ容量',1,1,4),s('guard','待つ条件の確認','while',['while','if']),K.b('release','waitでmutexを解放する',true)],
 alt:['whileをifにして再確認を省く',{guard:'if'}],
 intro:['通知を受けたことと、自分が必要な条件が満たされていることは別です。通知後に別の利用者が先にデータを取る場合もあります。','条件変数は条件そのものを記憶しません。mutexを持って条件を確認し、waitでは解放して眠り、再び獲得した後に条件を確認します。','C1が空のバッファを待つ途中でwakeを入れます。Pが7を入れてもC2が先に取るため、C1が再開するときにもう一度確認する必要があります。','ifへ切り替えると、再開時に空なのに取り出す誤りが起きます。waitでmutexを保持したままにする誤った設定も比較してください。','wakeはOSが実際に理由なく起こすことの全モデルではなく、再確認の必要性を示す注入操作です。正しい側は条件をwhileで守ります。'],
 topics:[['mutex','共有状態を見る・変更する範囲を排他的にします。'],['条件変数','状態が変化した可能性を通知し、述語自体は別途確認します。'],['atomic release-and-wait','通知との隙間を作らずに解放と待機へ移ります。'],['while再確認','起床やmutex獲得の後に条件をもう一度調べます。']],
 quiz:['条件変数のwaitから戻った直後は？','mutexを持って述語を再確認する','通知があるので無条件にデータを取る','mutexを二度と使わない','通知時点と再開時点の間に状態が変わり得ます。'],
 tests:[[{guard:'while'},{'不正な取出し':0}],[{guard:'if'},{'不正な取出し':1}]]
},p=>{const states={},buffer=[],rows=[],frames=[];let owner=null,invalid=0;const lines=p.events.split('\n').filter(x=>x.trim());if(lines.length>40)throw Error('40操作以内です。');function state(id){return states[id]||(states[id]={status:'実行可能',waiting:false,received:[]});}for(const [i,line]of lines.entries()){const a=line.trim().split(/\s+/);let message='';if(a[0]==='wake'){const st=state(a[1]);if(st.waiting)st.status='起床・mutex待ち';message='通知だけではデータは増えない';}else{const [id,action,raw]=a,st=state(id);if(!/^[PC]\d?$/.test(id))throw Error('主体はP/C1/C2のように指定してください。');if(owner&&owner!==id)message=`mutexは${owner}が保持中`;else{owner=id;if(action==='put'){const value=Number(raw);if(!Number.isFinite(value))throw Error('putには数値が必要です。');if(buffer.length>=p.capacity)message='満杯なのでputを待つ';else{buffer.push(value);message=value+'を入れて通知';for(const other of Object.values(states))if(other.waiting)other.status='起床・mutex待ち';}owner=null;}else if(['get','resume'].includes(action)){if(action==='resume'&&!st.waiting){message='待機していないので何もしない';owner=null;}else{const skip=action==='resume'&&p.guard==='if';if(!buffer.length&&!skip){st.waiting=true;st.status='条件待ち';message='空なのでwait'+(p.release?'しmutexを解放':'するがmutexを保持（誤り）');if(p.release)owner=null;}else{if(!buffer.length){invalid++;message='空のまま取出しを試みた';}else{const value=buffer.shift();st.received.push(value);message=value+'を受信';}st.waiting=false;st.status='実行可能';owner=null;}}}else throw Error('操作はput 数値 / get / resume / wake C1です。');}}
 rows.push([i+1,line,message,buffer.join(',')||'空',owner||'なし']);frames.push(F(`操作${i+1}: ${message}`,'起床、mutex獲得、条件の再確認、データの取出しは別の段階です。',K.table(['順','要求','判断','バッファ','mutex保持者'],rows.slice())));}
 return out(frames,{'不正な取出し':invalid,'条件待ちの数':Object.values(states).filter(x=>x.waiting).length,'C1受信':states.C1?.received.join(',')||'なし','C2受信':states.C2?.received.join(',')||'なし','mutex保持者':owner||'なし'});
});
function banker(allocation,maximum,available){const work=available.slice(),finished=allocation.map(()=>false),sequence=[],trace=[];for(let change=true;change;){change=false;allocation.forEach((row,i)=>{if(finished[i]||row.some((v,j)=>maximum[i][j]-v>work[j]))return;const before=work.slice();row.forEach((v,j)=>work[j]+=v);finished[i]=true;sequence.push(i);trace.push({process:i,before,work:work.slice()});change=true;});}return {safe:finished.every(Boolean),sequence,finished,trace};}
K.banker=banker;
D(78,{
 title:'複数資源のデッドロック検出と銀行家の算法',question:'今は渡せる資源でも、渡した後に全員が終われる？',
 scope:'最大6プロセス×4資源のallocation/maximum/availableを入力。安全系列、要求の仮割当、待ち要求による検出を計算します。安全でない状態を現在のデッドロックと混同しません。',
 controls:[code('allocation','現在の割当','1 0\n0 1\n1 1'),code('maximum','最大要求','2 1\n1 2\n2 2'),t('available','空き資源','1 1'),r('process','要求するプロセス',0,0,2),t('request','追加要求','1 0'),s('mode','判定','avoid',[['avoid','最大要求から安全性'],['detect','未処理要求として検出']])],
 alt:['空き資源を0にする',{available:'0 0'}],
 intro:['資源を1つ渡せるからといって、その後すべての仕事が完了できるとは限りません。誰かが終わって資源を返す順番を考えます。','安全性判定では各プロセスが今後必要とする最大残量を使います。検出では実際に待っている要求を使います。この2つは同じ判定ではありません。','空き1,1と3つの割当を使い、完了できるプロセスを1つずつ探します。その資源を仮に返した後のworkを表で追ってください。','空きを0,0へ変え、完了できる順番があるか比べます。追加要求はまず残り必要数と空きに収まるかを確認し、仮に渡してから再判定します。','安全でないことは、この瞬間に必ずデッドロックしていることを意味しません。最大要求は将来の上限で、現時点の待ちそのものではありません。'],
 topics:[['成立条件','排他、保持待ち、非横取り、循環待ちを区別します。'],['複数インスタンス','資源の個数をベクトルで管理します。'],['安全系列','誰かの完了と返却を仮定し、全員が終わる順番を探します。'],['要求の審査','現在の空きだけでなく、仮割当後の安全性も調べます。'],['検出と回避','現在の要求と将来の最大要求では意味が異なります。']],
 quiz:['安全系列が見つからない状態は？','将来の全要求に備えた完了保証がない','必ずこの瞬間に全プロセスが停止している','空き資源が必ず0','銀行家の算法は最大要求に基づく予防的な安全性を評価します。'],
 tests:[[{},{'最初の状態は安全':true}],[{available:'0 0'},{'最初の状態は安全':false}]]
},p=>{const a=K.readMatrix(p.allocation,6),m=K.readMatrix(p.maximum,6),v=K.numbers(p.available,1,4),request=K.numbers(p.request,1,4);if(a.length!==m.length||a[0].length!==v.length||m[0].length!==v.length||request.length!==v.length||[...a.flat(),...m.flat(),...v,...request].some(x=>!Number.isInteger(x)||x<0)||p.process>=a.length)throw Error('割当と最大要求は同じ行列サイズ、空きと要求は同じ資源数の非負整数です。');if(p.mode==='avoid'&&a.some((row,i)=>row.some((x,j)=>x>m[i][j])))throw Error('現在の割当は最大要求以下にしてください。');const maximum=p.mode==='detect'?m.map((row,i)=>row.map((x,j)=>x+a[i][j])):m,initial=banker(a,maximum,v),frames=[F(p.mode==='detect'?'現在の未処理要求を読む':'残り必要数を計算する','表のneedと空きworkを成分ごとに比較します。合計だけで判断しません。',K.table(['プロセス','allocation','need'],a.map((row,i)=>['P'+i,row.join(','),maximum[i].map((x,j)=>x-row[j]).join(',')])) )];initial.trace.forEach((x,i)=>frames.push(F(`P${x.process}が完了できる`,'仮にこの仕事が終わると、既に保持していた資源が空きへ返ります。',K.table(['順','process','work変更前','work変更後'],initial.trace.slice(0,i+1).map((s,j)=>[j+1,'P'+s.process,s.before.join(','),s.work.join(',')])))));let answer='現在の要求だけを検出';if(p.mode==='avoid'){const fitsNeed=request.every((x,j)=>x<=m[p.process][j]-a[p.process][j]),fitsAvailable=request.every((x,j)=>x<=v[j]);if(!fitsNeed)answer='最大要求を越えるため拒否';else if(!fitsAvailable)answer='空き不足なので待機';else{const aa=a.map(row=>row.slice()),vv=v.map((x,j)=>x-request[j]);request.forEach((x,j)=>aa[p.process][j]+=x);answer=banker(aa,m,vv).safe?'仮割当後も安全なので受理':'仮割当後は安全でないため保留';}frames.push(F('追加要求を評価する',answer,K.table(['対象','要求','判定'],[['P'+p.process,request.join(','),answer]])));}if(frames.length===1)frames.push(F('完了候補がない','現在のworkで必要な資源を満たすプロセスがありません。判定モードによる意味の違いに注意します。',K.cells([{label:'未完了',values:initial.finished.flatMap((x,i)=>x?[]:['P'+i])}])));return out(frames,{'最初の状態は安全':initial.safe,'完了系列':initial.sequence.map(x=>'P'+x).join(' → ')||'なし','残るプロセス数':initial.finished.filter(x=>!x).length,'要求の判定':answer});});
D(79,{
 title:'パス・リンク・openとunlink・ジャーナル',question:'ファイル名を消したのに、開いたファイルは読める？',
 scope:'仮想ディレクトリの名前→inode、ハードリンク、最大8段のsymlink解決、open fdの参照数を計算。journalモードは名前変更の原子性を故障位置で比較します。',
 controls:[s('mode','実験','files',[['files','名前・inode・fd'],['journal','名前変更のクラッシュ']]),code('events','操作列','open /doc\nlink /doc /copy\nsymlink /copy /shortcut\nunlink /doc\nread 3\nopen /shortcut\nunlink /copy\nread 3\nclose 3\nclose 4'),s('crash','故障位置','middle',[['before','開始前'],['middle','変更途中'],['after','確定後']]),K.b('journal','名前変更をjournalで守る',true)],
 alt:['ハードリンクを作らず名前を消す',{events:'open /doc\nunlink /doc\nread 3\nclose 3'}],
 intro:['ファイル名と、ファイルの内容を保存している物は同じではありません。名前を消す操作が、すでに開いている入口へどう影響するかを調べます。','ディレクトリは名前からinodeを引く表です。ハードリンクは同じinodeへの別名、シンボリックリンクは別のパス文字列を保存する物です。','/docを開いてfd3を作った後、別名/copyも作ります。元の名前を消しても、別名や開いた入口が残る間は内容を参照できます。','別名を作らない条件でも、開いたfdから読める期間を追います。journalモードでは名前変更の途中で電源が切れた場合を比較できます。','実際のファイルシステムには多くの永続化規則があります。ここでは名前変更のメタデータを対象にし、データ全体の耐久性とは区別します。'],
 topics:[['パス探索','名前の表をたどり、リンク先を必要に応じて解決します。'],['ハードリンクとsymlink','inodeの共有とパスの参照は違います。'],['openとunlink','名前の参照と開いたfdの参照を別に数えます。'],['ジャーナリング','確定を記録してから原子的に反映し、中間状態で復旧しないようにします。']],
 quiz:['最後の名前をunlinkしてもopen fdが残っている場合は？','fdから参照する内容が残る場合がある','即座にすべてのreadが必ず失敗する','同名の新しいファイルが自動でできる','名前の寿命と開いた参照の寿命は別です。']
},p=>{if(p.mode==='journal'){const before={'/old':1},after={'/new':1},partial={'/old':1,'/new':1},recovered=p.crash==='before'?before:p.crash==='after'?after:p.journal?before:partial;return out([F('名前変更を2つの操作に分けてみる','単に新名追加と旧名削除を別々に保存すると、中間状態が残る恐れがあります。',K.table(['段階','名前'],[['前','/old'],['途中','/old, /new'],['後','/new']])),F('確定記録を基準に復旧する','この教材は確定前の変更を捨て、確定後は全体をredoするメタデータ方式です。',K.table(['journal','故障位置','復旧後'],[[p.journal,p.crash,Object.keys(recovered).join(',')]]))],{'名前の数':Object.keys(recovered).length,'中間状態が残る':Object.keys(recovered).length===2});}
 const entries=new Map([['/doc',{kind:'file',inode:1}]]),inodes=new Map([[1,{text:'hello',links:1,opens:0}]]),fds=new Map(),rows=[],frames=[];let nextfd=3;
 const path=raw=>{if(!raw?.startsWith('/'))throw Error('パスは/から始めてください。');const parts=[];for(const x of raw.split('/')){if(!x||x==='.')continue;if(x==='..')parts.pop();else parts.push(x);}return '/'+parts.join('/');};
 function resolve(raw){let name=path(raw);for(let i=0;i<8;i++){const e=entries.get(name);if(!e)throw Error('ENOENT: '+name);if(e.kind==='file')return e.inode;name=path(e.target);}throw Error('ELOOP: リンクが循環しています');}
 const gc=id=>{const x=inodes.get(id);if(x&&x.links===0&&x.opens===0)inodes.delete(id);};
 const lines=p.events.split('\n').filter(x=>x.trim());if(lines.length>40)throw Error('操作は40行以内です。');for(const [i,line]of lines.entries()){const [op,a,b]=line.trim().split(/\s+/);let result='';try{if(op==='open'){const id=resolve(a),fd=nextfd++;fds.set(fd,id);inodes.get(id).opens++;result='fd '+fd+' → inode '+id;}else if(op==='read'){const id=fds.get(Number(a));if(!id)throw Error('EBADF');result=inodes.get(id).text;}else if(op==='close'){const fd=Number(a),id=fds.get(fd);if(!id)throw Error('EBADF');fds.delete(fd);inodes.get(id).opens--;gc(id);result='fdを閉じる';}else if(op==='unlink'){const name=path(a),e=entries.get(name);if(!e)throw Error('ENOENT');entries.delete(name);if(e.kind==='file'){inodes.get(e.inode).links--;gc(e.inode);}result='名前を外す';}else if(op==='link'||op==='symlink'){const target=path(b);if(entries.has(target))throw Error('EEXIST');if(op==='link'){const id=resolve(a);entries.set(target,{kind:'file',inode:id});inodes.get(id).links++;}else entries.set(target,{kind:'symlink',target:path(a)});result='別名を追加';}else throw Error('対応操作はopen/read/close/unlink/link/symlinkです。');}catch(e){result=e.message;}rows.push([i+1,line,result]);frames.push(F(`操作${i+1}: ${line}`,'inodeの名前数とopen数の両方が0になったときだけ内容を解放します。symlinkはリンク先inodeの名前数を増やしません。',K.table(['順','操作','結果'],rows.slice()),{'名前数':entries.size,'inode数':inodes.size,'open fd数':fds.size}));frames.push(F('名前と内容の参照を確認','同じinode番号は同じ内容です。壊れたsymlinkは名前としては存在してもリンク先を開けません。',K.table(['種別','名前／番号','参照先','名前数','open数'],[...[...entries].map(([n,e])=>[e.kind,n,e.inode??e.target,'—','—']),...[...inodes].map(([id,x])=>['inode',id,x.text,x.links,x.opens]),...[...fds].map(([fd,id])=>['fd',fd,id,'—','—'])])));}if(!frames.length)throw Error('操作を入力してください。');return out(frames,{'残るinode':inodes.size,'名前数':entries.size,'開いたfd':fds.size,'成功したread':rows.filter(x=>x[2]==='hello').length});});
D(80,{
 title:'仮想マシン・コンテナ・名前空間・資源制限',question:'同じPIDや同じパスでも、別の環境から何が見える？',
 scope:'2ゲストのPID・ファイル名前空間、共有カーネル／別カーネルの構成、CPU quotaとメモリ上限を仮想的に計算します。実環境への侵入や隔離の実装を行いません。',
 controls:[s('kind','実行環境','container',[['process','隔離しないプロセス'],['container','コンテナ'],['vm','仮想マシン']]),K.b('privateFiles','別のファイル名前空間',true),r('limit','ゲストAのメモリ上限',4,1,12),r('request','Aが確保する量',6,1,12),r('quota','10tickあたりのCPU quota',4,1,10)],
 alt:['VMにしてカーネルの境界を比較する',{kind:'vm'}],
 intro:['コンテナと仮想マシンはいずれも別環境のように使えますが、共有する部品が違います。名前が同じでも見える物が別になる仕組みを調べます。','名前空間は見える名前を分け、資源制限は使える量を制御します。コンテナはホストカーネルを共有し、VMはゲストカーネルを別に持つ構成です。','2つのゲストがそれぞれPID1と/dataを使います。ホスト側の対応と、Aのメモリ確保が上限で止まるかを確認してください。','VMへ変更するとどこに境界が増えるかを見ます。ファイル名前空間を共有させた場合は、同じパスの変更が他方からどう見えるかも比較します。','名前空間と資源制限を付けただけで完全な安全性を認定しません。VMにも共有するホスト資源があり、ここで示すのは構成と割当のモデルです。'],
 topics:[['仮想化','仮想ハードウェア上にゲストカーネルを置きます。'],['コンテナ','ホストカーネルを共有しながら見える資源を分けます。'],['名前空間','同じ名前を各環境の別の対象へ対応付けます。'],['CPU・メモリ制限','名前を分けることと消費量を制限することは別です。']],
 quiz:['コンテナで一般に共有する部品は？','ホストのカーネル','すべてのプロセスのPID番号空間','すべてのファイルへの読み書き権限','カーネル共有と、見える名前・権限の分離を混同しません。']
},p=>{const isolated=p.kind!=='process',own=isolated&&p.privateFiles,frames=[],pages=[],nodes=p.kind==='vm'?[{id:'host',label:'ホスト／ハイパーバイザ'},{id:'ka',label:'ゲストカーネルA'},{id:'kb',label:'ゲストカーネルB'},{id:'a',label:'アプリA'},{id:'b',label:'アプリB'}]:[{id:'host',label:'共有ホストカーネル'},{id:'a',label:'アプリA'},{id:'b',label:'アプリB'}],edges=p.kind==='vm'?[{from:'host',to:'ka'},{from:'host',to:'kb'},{from:'ka',to:'a'},{from:'kb',to:'b'}]:[{from:'host',to:'a'},{from:'host',to:'b'}];frames.push(F('共有している層を確認する','図の境界の数だけで安全性の点数を付けず、どの主体がどの資源を管理するかを見ます。',K.graph(nodes,edges,{directed:true})));for(let i=1;i<=p.request;i++){const accepted=!isolated||i<=p.limit;pages.push([i,accepted?'確保':'上限で拒否',Math.min(i,isolated?p.limit:i)]);}frames.push(F('見える名前をホストの対象へ対応させる','/dataの内容をAが変更する例です。別の名前空間ならBの内容は保持されます。',K.table(['環境','見えるPID','ホストPID','/dataの参照先','A書込み後の値'],[['A',isolated?1:101,101,own?'A専用':'共有',9],['B',isolated?1:202,202,own?'B専用':'共有',own?5:9]])));frames.push(F('メモリの割当要求を順番に行う','上限に達した後の要求を受理しない教材です。実際のOOM処理などは方式に依存します。',K.table(['要求','判定','確保済み'],pages)));frames.push(F('CPU quotaとスケジューリング','ここでは10tickのうちquotaだけAを実行し、残りをBへ割り当てます。割当は性能の保証ではありません。',K.cells([{label:'CPUの10tick',values:Array.from({length:10},(_,i)=>i<(isolated?p.quota:10)?'A':'B')}])));return out(frames,{'カーネル数':p.kind==='vm'?3:1,'A確保量':isolated?Math.min(p.request,p.limit):p.request,'Bが読むdata':own?5:9,'AのCPU tick':isolated?p.quota:10});});
D(81,{
 title:'仕事の分割・スレッドプール・並列集約・SIMD',question:'同じ個数ずつ分ければ、全員同時に終わる？',
 scope:'最大24仕事の静的分割・動的work queue・SIMD幅ごとの遅いlaneの待機を計算。集約は木構造と逐次の操作数を比較し、barrierを省いた早期読出しも表示します。',
 controls:[t('times','各仕事の時間','1,1,8,8,2,2,3,3'),r('workers','実行資源の数',4,1,8),s('strategy','割り振り','static',[['static','連続範囲で静的分割'],['dynamic','空いたworkerへ次の仕事'],['simd','同時laneのグループ']]),K.b('barrier','全員の終了を待って集約',true)],
 alt:['動的な仕事キューに切り替える',{strategy:'dynamic'}],
 intro:['要素の数を同じに分けても、各要素の仕事量が違うと一部のworkerだけが長く残ります。仕事の分割と、最後の集約を別に考えます。','静的分割は担当を先に決め、動的分割は空いた資源が次を取ります。SIMDでは同じグループのlaneが足並みをそろえるため、分岐や長い仕事が影響します。','8個の仕事には時間1のものと8のものがあります。同じ個数で分けた場合の各workerの終了時刻を比べてください。','動的キューへ変更すると終了時刻の偏りがどう変わるか見ます。barrierを外すと、一番早く終わった時点の不完全な合計を読んでしまいます。','実機のスレッド生成や通信の手間は0と仮定しています。モデル上の速度向上を、そのままGPUやCPUの実測性能として扱いません。'],
 topics:[['静的・動的分割','担当を先に決めるか、空いたworkerへ割り当てるかを選びます。'],['スレッドプール','限られたworkerが複数の仕事を順に処理します。'],['並列reduction','部分結果を木状に結合して依存の深さを減らします。'],['SIMD・GPU','laneのグループ内で同期し、遅いlaneや分岐の影響を受けます。'],['barrier','全結果が揃う時刻と、早期に読む時刻を分けます。']],
 quiz:['部分結果を合計する前に必要なことは？','対象の仕事が終わり、結果を参照できる状態か確認する','最初のworkerだけ終わればよい','worker数を必ず仕事数と同じにする','計算を分けることと、結果が揃ったことは別です。'],
 tests:[[{},{'全結果の合計':36}]]
},p=>{const times=K.numbers(p.times,1,24);if(times.some(x=>x<=0||x>40))throw Error('各仕事の時間は0より大きく40以下です。');const workers=Array(p.workers).fill(0),jobs=[];if(p.strategy==='simd'){let time=0;for(let i=0;i<times.length;i+=p.workers){const group=times.slice(i,i+p.workers),duration=Math.max(...group);group.forEach((x,j)=>jobs.push({i:i+j,worker:j,start:time,end:time+duration,active:x}));time+=duration;}workers.fill(time);}else times.forEach((duration,i)=>{const worker=p.strategy==='static'?Math.min(p.workers-1,Math.floor(i/Math.ceil(times.length/p.workers))):workers.indexOf(Math.min(...workers)),start=workers[worker];workers[worker]+=duration;jobs.push({i,worker,start,end:workers[worker],active:duration});});const complete=Math.max(...workers),early=Math.min(...workers.filter((_,i)=>jobs.some(j=>j.worker===i))),readAt=p.barrier?complete:early,computed=K.sum(jobs.filter(j=>j.end<=readAt).map(j=>j.i+1)),levels=[];let partial=Array.from({length:times.length},(_,i)=>i+1);while(partial.length>1){const next=[];for(let i=0;i<partial.length;i+=2)next.push(partial[i]+(partial[i+1]??0));levels.push(next);partial=next;}const frames=[F('各workerの担当と開始・終了を計算する','同じ仕事量を、担当する順番と場所だけ変えて比較しています。',K.table(['仕事','worker','開始','終了','実作業時間','値'],jobs.map(j=>[j.i,j.worker,q(j.start),q(j.end),j.active,j.i+1]))),F('最も遅いworkerを待つ','全体の完了は最後の担当が終わった時刻です。SIMDのlaneが待った時間も区別します。',K.table(['worker','終了時刻','待たされる時間'],workers.map((x,i)=>[i,q(x),q(complete-x)])))];levels.forEach((values,i)=>frames.push(F(`集約の段${i+1}`,'隣り合う2つの部分和を足します。全ての加算回数は減らなくても、依存する段数を減らせます。',K.cells([{label:'部分和',values}]))));frames.push(F('いつ結果を読むか確認','barrierなしの表示は意図的に早く読む反例です。未完了の値を0として読む教材モデルです。',K.table(['読出し時刻','その時点の合計','正しい全合計'],[[q(readAt),computed,times.length*(times.length+1)/2]])));return out(frames,{'完了時間':q(complete),'全結果の合計':times.length*(times.length+1)/2,'実際に読んだ合計':computed,'理想逐次との倍率':q(K.sum(times)/complete),'集約の段数':levels.length});});
})();
