/* GAP-128..132. Transparent, bounded NLP models. No remote models or APIs. */
(() => {
'use strict';
const L=CSL,K=L.curriculum,{define:D,f:F,result:out,r,s,t,codeInput:code,round:q}=K;
const mean=K.mean;
const tokenize=text=>String(text).toLowerCase().match(/[\p{L}\p{N}_]+/gu)||[];
K.tokenizeWords=tokenize;
function segmentJapanese(text,source,unknown=8,context=true){
 const chars=Array.from(text);if(!chars.length||chars.length>60)throw Error('文は1〜60文字です。');const dictionary=source.split('\n').filter(x=>x.trim()).map(line=>{const [word,pos,cost,...rest]=line.trim().split(/\s+/);if(rest.length||!word||!pos||!Number.isFinite(Number(cost))||Number(cost)<0)throw Error('辞書は 語 品詞 非負コスト の形式です。');return {word,pos,cost:Number(cost),length:Array.from(word).length};});if(dictionary.length>60)throw Error('辞書は60語以内です。');const dp=Array.from({length:chars.length+1},()=>new Map()),lattice=[];dp[0].set('START',{cost:0,path:[]});const transition=(a,b)=>!context?0:a==='NOUN'&&b==='NOUN'?3:a==='PRT'&&b==='PRT'?4:a==='VERB'&&b==='VERB'?3:0;
 for(let at=0;at<chars.length;at++){const suffix=chars.slice(at).join(''),candidates=dictionary.filter(e=>suffix.startsWith(e.word)).concat([{word:chars[at],pos:'UNK',cost:unknown,length:1}]);for(const [previous,state]of dp[at])for(const entry of candidates){const end=at+entry.length,cost=state.cost+entry.cost+transition(previous,entry.pos),old=dp[end].get(entry.pos),token={start:at,end,word:entry.word,pos:entry.pos,cost:entry.cost,transition:transition(previous,entry.pos)};lattice.push({from:at,to:end,word:entry.word,pos:entry.pos,cost,selected:!old||cost<old.cost});if(!old||cost<old.cost)dp[end].set(entry.pos,{cost,path:[...state.path,token]});}}
 const best=[...dp[chars.length].values()].sort((a,b)=>a.cost-b.cost)[0];return {tokens:best.path,cost:best.cost,lattice,dp,chars};
}
K.segmentJapanese=segmentJapanese;
const japaneseDictionary='私 NOUN 1\nは PRT 1\n通信 NOUN 1\n通 NOUN 3\n信 NOUN 3\nを PRT 1\n学ぶ VERB 1\n学 VERB 4\nぶ END 4';
D(128,{
 title:'日本語の単語分割・形態素解析・最小コスト経路',question:'空白のない文の、どこを一つの語にする？',
 scope:'最大60文字・60辞書語のlatticeを作り、語コストと品詞遷移コストからViterbiで最小経路を求めます。未知語は1文字候補。実用辞書や統計形態素解析器の全体ではありません。',
 sources:['slp'],
 controls:[t('sentence','日本語の文','私は通信を学ぶ'),code('dictionary','辞書（語 品詞 cost）',japaneseDictionary),r('unknown','未知語1文字の費用',8,1,12),K.b('context','品詞のつながりも費用に入れる',true)],
 alt:['辞書から通信という語を外す',{dictionary:'私 NOUN 1\nは PRT 1\n通 NOUN 3\n信 NOUN 3\nを PRT 1\n学ぶ VERB 1'}],
 intro:['日本語では空白がなくても単語を区別して読みます。機械には辞書の候補とつながりの規則を与え、どの分割を選ぶかを計算させます。','文字位置を頂点、語の候補を辺にしたlatticeを作ります。前の品詞を状態に含めて、語コストと遷移コストの合計が最小になる道を選びます。','私は通信を学ぶを辞書で分けます。通信という2文字の候補と、通・信という1文字ずつの候補を比べ、選択の費用を追ってください。','辞書から通信を外すと最適経路が変わります。未知語の費用や品詞遷移を変えると、辞書だけの最長一致とは違う結果を作ることもできます。','小さい辞書と手で決めた費用の教材です。結果が日本語として常に正しいわけではなく、未知語・表記ゆれ・文脈の限界を残して表示します。'],
 topics:[['単語境界','文字列の位置と候補の長さを区別します。'],['品詞','同じ位置に到着しても直前の品詞が違えば次の費用が変わります。'],['lattice','複数候補を同時に残して全体の経路を選びます。'],['Viterbi','位置と状態ごとの最小費用を再利用し、選んだ経路を戻ります。'],['未知語','辞書にない部分も明示的な候補と費用で扱います。']],
 quiz:['局所的に最も安い単語を毎回選べば、文全体も必ず最小？','後のつながりの費用によっては違う','常に必ず最小','品詞の情報は絶対に役立たない','全体の経路費用には後続の遷移も含まれます。']
},p=>{
 const run=segmentJapanese(p.sentence,p.dictionary,p.unknown,p.context),frames=[];for(let at=0;at<run.dp.length;at++)if(run.dp[at].size)frames.push(F(`文字位置${at}までの候補`,'同じ位置でも前の品詞ごとに候補を残します。最小値を更新した根拠を各状態の経路から確認できます。',K.table(['直前の品詞','累積費用','ここまでの語'],[...run.dp[at]].map(([pos,state])=>[pos,q(state.cost),state.path.map(x=>x.word).join(' | ')]))));
 frames.push(F('選んだ語と費用を対応させる','語自身の費用と、前の品詞からの遷移費用を別々に足します。',K.table(['開始','終了','語','品詞','語費用','遷移費用'],run.tokens.map(x=>[x.start,x.end,x.word,x.pos,x.cost,x.transition]))));
 frames.push(F('位置と候補のlatticeを見る','辺は実際に一致した辞書候補です。最終的に使った語はactiveとして示します。',K.graph(Array.from({length:run.chars.length+1},(_,i)=>({id:String(i),label:i+' '+(run.chars[i]||'終端')})),[...new Map(run.lattice.map(x=>[x.from+':'+x.to+':'+x.word,{from:String(x.from),to:String(x.to),label:x.word,active:run.tokens.some(t=>t.start===x.from&&t.end===x.to&&t.word===x.word)}])).values()],{directed:true})));
 return out(frames,{'選んだ分割':run.tokens.map(x=>x.word).join(' | '),'合計費用':q(run.cost),'未知語の数':run.tokens.filter(x=>x.pos==='UNK').length,'語数':run.tokens.length});
});
function documentVectors(documents){const words=documents.map(tokenize),vocabulary=[...new Set(words.flat())].sort();if(vocabulary.length>120)throw Error('単語種類は120以下です。');const count=tokens=>vocabulary.map(word=>tokens.filter(x=>x===word).length),counts=words.map(count),idf=vocabulary.map((_,j)=>Math.log((documents.length+1)/(counts.filter(row=>row[j]>0).length+1))+1),vectors=counts.map(row=>row.map((x,i)=>x*idf[i]));return {words,vocabulary,counts,idf,vectors,query:text=>count(tokenize(text)).map((x,i)=>x*idf[i])};}
const cosine=(a,b)=>K.norm(a)&&K.norm(b)?K.dot(a,b)/(K.norm(a)*K.norm(b)):0;
K.documentVectors=documentVectors;K.cosine=cosine;
D(129,{
 title:'TF-IDF・n-gram・共起ベクトル・文書類似度',question:'単語を数値にしたら、何の似ている度合いになる？',
 scope:'2〜12文書のTF-IDFとcosine、add-α bigram確率、最大24語のPPMI共起ベクトルを実計算。PPMIの2次元表示は射影であり、事前学習済み埋め込みではありません。',
 sources:['slp'],
 controls:[s('mode','表現','tfidf',[['tfidf','TF-IDF'],['ngram','bigram言語モデル'],['embedding','共起ベクトル']]),code('documents','文書（1行1文書）','network security protects data\nnetwork routing sends packets\nsecure software protects data\nfood and music are enjoyable'),t('query','調べる文','network protects data'),r('alpha','bigramの平滑化α',.5,0,1,.1),r('window','共起を数える左右の幅',2,1,4)],
 alt:['異なる話題の文と比較する',{query:'food music enjoyable'}],
 intro:['文字列のままでは計算しにくいため、単語の数や周囲との関係を数値へ変換します。どんな数値にするかで、似ているという意味も変わります。','TF-IDFは文書内の頻度と全体での珍しさを組み合わせます。n-gramは前の語から次の語の確率を見積もり、共起表現は近くに出る語の分布を使います。','network protects dataを4文書と比較します。すべての文書に多い語と、限られた文書だけに出る語の重みの違いを確認してください。','queryを食べ物と音楽の文へ変えます。bigramではαを変え、未知の組合せの確率を調べます。共起では近さの幅を変えてベクトルが変わる様子を見ます。','小さい文書集合の頻度から作るモデルです。意味を完全に理解したことにはならず、cosineの値も人間の意味的な同一性を保証しません。'],
 topics:[['bag of words','単語の出現回数を列にし、基本形では順序を捨てます。'],['TF-IDF','ここではidf=log((N+1)/(df+1))+1を使います。'],['n-gram','前の語の条件を付け、平滑化で未観測の組も扱います。'],['分布的表現','周囲の語の分布から同じ文脈に現れる語を近づけます。'],['cosine','ベクトルの長さではなく方向の近さを計算します。']],
 quiz:['同じ単語回数でも語順が逆の2文は、単純なBoWでは？','同じベクトルになる場合がある','必ず異なるベクトルになる','構文木が自動で保存される','選んだ表現が保持する情報と捨てる情報を区別します。']
},p=>{
 const documents=p.documents.split('\n').filter(x=>x.trim());if(documents.length<2||documents.length>12||documents.some(x=>tokenize(x).length>80))throw Error('2〜12文書、各80語以内です。');const model=documentVectors(documents),frames=[];
 if(p.mode==='tfidf'){const query=model.query(p.query),scores=model.vectors.map(vector=>cosine(query,vector));frames.push(F('文書頻度とidfを計算する','ここではtfを単純な出現数にしています。実際に使ったidfの式と値を表示します。',K.table(['単語','文書頻度df','idf'],model.vocabulary.map((word,j)=>[word,model.counts.filter(row=>row[j]>0).length,q(model.idf[j])]))));frames.push(F('重み付きベクトルと方向を比べる','queryにだけある未知語は、この学習語彙の次元には追加しません。',K.table(['文書','cosine','TF-IDFベクトル'],documents.map((doc,i)=>[doc,q(scores[i]),model.vectors[i].map(x=>q(x,2)).join(',')]))));return out(frames,{'最も近い文書番号':scores.indexOf(Math.max(...scores))+1,'最大cosine':q(Math.max(...scores)),'語彙数':model.vocabulary.length,'queryの既知語数':tokenize(p.query).filter(x=>model.vocabulary.includes(x)).length});}
 if(p.mode==='ngram'){const counts=new Map(),totals=new Map(),vocabulary=new Set([...model.vocabulary,'</s>','<unk>']);for(const words of model.words){const sequence=['<s>',...words,'</s>'];for(let i=1;i<sequence.length;i++){const previous=sequence[i-1],word=sequence[i],key=previous+'\t'+word;counts.set(key,(counts.get(key)||0)+1);totals.set(previous,(totals.get(previous)||0)+1);}}const query=['<s>',...tokenize(p.query).map(x=>vocabulary.has(x)?x:'<unk>'),'</s>'],rows=[];let log=0;for(let i=1;i<query.length;i++){const count=counts.get(query[i-1]+'\t'+query[i])||0,total=totals.get(query[i-1])||0,den=total+p.alpha*vocabulary.size,probability=den?(count+p.alpha)/den:0;log+=probability?Math.log(probability):-Infinity;rows.push([query[i-1],query[i],count,total,q(probability)]);}const perplexity=Math.exp(-log/(query.length-1));frames.push(F('条件付きの語の回数を数える','同じ語でも前の語が違えば別の条件付き確率です。未知語は<unk>として扱います。',K.table(['前の語','次の語','組の回数','前の語の総数','条件付き確率'],rows)));frames.push(F('文全体の予測の難しさを計算する','perplexityはこのtoken化と語彙・平滑化の条件に依存します。異なる条件の値を直接優劣にしません。',K.table(['予測token数','平均負log確率','perplexity'],[[query.length-1,Number.isFinite(log)?q(-log/(query.length-1)):'∞',Number.isFinite(perplexity)?q(perplexity):'∞']])));return out(frames,{'perplexity':Number.isFinite(perplexity)?q(perplexity):'∞','予測token数':query.length-1,'平滑化α':p.alpha});}
 const frequency=new Map();model.words.flat().forEach(word=>frequency.set(word,(frequency.get(word)||0)+1));const words=[...frequency].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,24).map(([w])=>w),matrix=words.map(()=>words.map(()=>0));for(const document of model.words)for(let i=0;i<document.length;i++){const a=words.indexOf(document[i]);if(a<0)continue;for(let j=Math.max(0,i-p.window);j<=Math.min(document.length-1,i+p.window);j++){const b=words.indexOf(document[j]);if(i!==j&&b>=0)matrix[a][b]++;}}const rowTotals=matrix.map(K.sum),colTotals=K.transpose(matrix).map(K.sum),total=K.sum(rowTotals),ppmi=matrix.map((row,i)=>row.map((x,j)=>x>0&&rowTotals[i]&&colTotals[j]?Math.max(0,Math.log(x*total/(rowTotals[i]*colTotals[j]))):0)),queryTokens=tokenize(p.query),query=words.map((_,j)=>K.sum(queryTokens.map(word=>{const i=words.indexOf(word);return i<0?0:ppmi[i][j];}))),scores=words.map((word,i)=>({word,score:cosine(query,ppmi[i])})).sort((a,b)=>b.score-a.score);frames.push(F('語の周囲を数えてPPMIにする','共起が独立な期待より多いと正の値になります。上限24語の共起ベクトルであり、外部モデルを読み込んでいません。',K.matrix(ppmi.map(row=>row.map(x=>q(x,2))),{rowLabels:words,colLabels:words})));frames.push(F('同じ周囲に出る語を比較する','queryの既知語のPPMIベクトルを足し、各語とのcosineを計算します。',K.table(['語','queryとのcosine'],scores.map(x=>[x.word,q(x.score)]))));return out(frames,{'最も近い語':scores[0]?.word||'なし','最大cosine':q(scores[0]?.score||0),'共起語彙数':words.length,'共起窓幅':p.window});
});
function ckyParse(sentence,source){
 const words=tokenize(sentence);if(!words.length||words.length>12)throw Error('構文解析は1〜12語です。');const rules=source.split('\n').filter(x=>x.trim()).map(line=>{const m=line.match(/^\s*([A-Z][A-Z0-9_]*)\s*->\s*(.+?)(?:\s+@\s*([0-9.]+))?\s*$/);if(!m)throw Error('文法は S -> NP VP または N -> "cat" の形式です。');const parts=m[2].match(/"[^"]*"|'[^']*'|\S+/g),probability=m[3]?Number(m[3]):1;if(parts.length<1||parts.length>2||!(probability>0&&probability<=1))throw Error('右辺は1または2項、重みは0より大きく1以下です。');return {lhs:m[1],rhs:parts.map(x=>x.replace(/^['"]|['"]$/g,'')),terminal:parts.length===1&&/^['"]/.test(parts[0]),score:Math.log(probability)};});if(rules.length>50)throw Error('文法規則は50個以内です。');const n=words.length,chart=Array.from({length:n},()=>Array.from({length:n+1},()=>new Map())),update=(cell,symbol,node)=>{if(!cell.has(symbol)||cell.get(symbol).score<node.score-1e-12){cell.set(symbol,node);return true;}return false;},unary=cell=>{for(let round=0;round<50;round++){let changed=false;for(const rule of rules.filter(r=>!r.terminal&&r.rhs.length===1))if(cell.has(rule.rhs[0])){const child=cell.get(rule.rhs[0]);changed=update(cell,rule.lhs,{symbol:rule.lhs,score:child.score+rule.score,children:[child]})||changed;}if(!changed)break;}};
 const trace=[];for(let i=0;i<n;i++){for(const rule of rules.filter(r=>r.terminal&&r.rhs[0].toLowerCase()===words[i]))update(chart[i][i+1],rule.lhs,{symbol:rule.lhs,score:rule.score,children:[{symbol:words[i],score:0,children:[]}]});unary(chart[i][i+1]);trace.push([i,i+1,[...chart[i][i+1].keys()].join(',')||'候補なし']);}
 for(let length=2;length<=n;length++)for(let start=0;start+length<=n;start++){const end=start+length,cell=chart[start][end];for(let middle=start+1;middle<end;middle++)for(const rule of rules.filter(r=>r.rhs.length===2)){const left=chart[start][middle].get(rule.rhs[0]),right=chart[middle][end].get(rule.rhs[1]);if(left&&right)update(cell,rule.lhs,{symbol:rule.lhs,score:left.score+right.score+rule.score,children:[left,right]});}unary(cell);trace.push([start,end,[...cell.keys()].join(',')||'候補なし']);}
 return {words,chart,trace,tree:chart[0][n].get('S')||null};
}
K.ckyParse=ckyParse;
const grammar='S -> NP VP\nNP -> N\nNP -> DET N\nVP -> V NP\nVP -> V PP\nPP -> P NP\nN -> "time"\nN -> "flies"\nN -> "arrow"\nV -> "flies"\nV -> "like"\nP -> "like"\nDET -> "an"';
D(130,{
 title:'構文木・係り受け・HMMと系列の推定',question:'単語ごとに最もありそうな品詞を選べば、文全体も最適？',
 scope:'12語以内の重み付きCKY＋単項閉包、4状態HMMのViterbi、手動arc-standard依存構文遷移を実行。英語の小辞書・手作り文法を使う形式モデルです。',
 sources:['slp'],
 controls:[s('mode','方式','hmm',[['hmm','HMMの系列推定'],['cky','文法から構文木'],['dependency','係り受け遷移']]),t('sentence','解析する文','time flies like an arrow'),code('grammar','小さな文法',grammar),t('depSentence','係り受け用の文','I see birds'),code('actions','遷移列','SHIFT\nSHIFT\nLEFT nsubj\nSHIFT\nRIGHT obj\nRIGHT root')],
 alt:['別の語順を解析する',{sentence:'like time flies'}],
 intro:['同じ語でも文脈によって役割が変わります。語の候補を独立に選ぶだけでなく、列としてのつながりや階層的な構造を考えます。','HMMは隠れた品詞の遷移と語の出やすさを使います。構文解析は部分区間から大きな構造を作り、係り受けはどの語がどの語を支配するかを辺で表します。','time flies like an arrowの品詞候補を計算します。Viterbiで前の候補を保持し、最後の最適な状態から品詞列を戻します。','語順を変えると候補と得点も変わります。CKYでは文法を編集し、依存構文ではSHIFT・LEFT・RIGHTを操作してstackとbufferを確認できます。','ここでの辞書と確率は説明用です。自然な文を常に解析できるわけではありません。候補なしや未完了の遷移は、そのまま示して成功と扱いません。'],
 topics:[['系列と局所判断','各語だけでなく、前後の状態の得点を含めます。'],['HMMとViterbi','状態列の最大得点を動的計画法で求めます。'],['CKY','短い区間から二分の構文を組み合わせます。'],['依存構造','head→dependentの辺とラベルを操作します。']],
 quiz:['構文解析器が候補を見つけられなかったら？','入力が不自然とは限らず、辞書・文法の範囲も確認する','その文は必ず誤文である','自動で一つの正解が存在したことにする','モデルの表現範囲と自然言語そのものを区別します。']
},p=>{
 const frames=[];
 if(p.mode==='cky'){const run=ckyParse(p.sentence,p.grammar);frames.push(F('区間ごとの構文候補を組み合わせる','startは含み、endは含まない語位置です。単項規則も閉包として反映します。',K.table(['start','end','作れた非終端'],run.trace)));const nodes=[],edges=[];function walk(node,id){nodes.push({id,label:node.symbol});node.children.forEach((child,i)=>{const next=id+'-'+i;edges.push({from:id,to:next});walk(child,next);});}if(run.tree)walk(run.tree,'S');else nodes.push({id:'none',label:'Sの解析候補なし'});frames.push(F('最良の構文木を取り出す','同じ区間・非終端の候補では最大log重みを残します。重みはこの文法の値で、確信度の一般的な尺度ではありません。',K.graph(nodes,edges,{directed:true})));return out(frames,{'Sとして解析できた':!!run.tree,'語数':run.words.length,'最良log重み':run.tree?q(run.tree.score):'候補なし'});}
 if(p.mode==='dependency'){const words=p.depSentence.trim().split(/\s+/);if(!words.length||words.length>12)throw Error('係り受けの語は1〜12個です。');const stack=[0],buffer=words.map((_,i)=>i+1),edges=[],rows=[];for(const line of p.actions.split('\n').filter(x=>x.trim())){if(rows.length>=40)throw Error('遷移は40個以内です。');const [action,label='dep']=line.trim().split(/\s+/);let result;if(action==='SHIFT'){if(buffer.length){stack.push(buffer.shift());result='buffer先頭をstackへ';}else result='拒否: bufferが空';}else if(['LEFT','RIGHT'].includes(action)&&stack.length>=2){const top=stack.at(-1),second=stack.at(-2),head=action==='LEFT'?top:second,dependent=action==='LEFT'?second:top;if(dependent===0||edges.some(e=>e.to===String(dependent)))result='拒否: ROOTまたはheadが既にある';else{edges.push({from:String(head),to:String(dependent),label});if(action==='LEFT')stack.splice(stack.length-2,1);else stack.pop();result=head+'→'+dependent;}}else result='拒否: 遷移の前提を満たさない';rows.push([line,result,stack.join(','),buffer.join(',')]);}frames.push(F('stackとbufferを操作する','ROOTは0です。各語は一つのheadを持ち、遷移で取り除いた語へ戻って二重にheadを付けません。',K.table(['操作','結果','stack','buffer'],rows)));frames.push(F('作られた係り受けを読む','入力した遷移から辺を作る教材です。正しい文法的な依存を自動で学習したという意味ではありません。',K.graph([{id:'0',label:'ROOT'},...words.map((word,i)=>({id:String(i+1),label:word}))],edges,{directed:true})));return out(frames,{'遷移が完了':buffer.length===0&&stack.length===1,'作った辺数':edges.length,'残るbuffer語数':buffer.length,'系列比較入力':p.sentence});}
 const words=tokenize(p.sentence);if(!words.length||words.length>20)throw Error('系列は1〜20語です。');const states=['N','V','P','D'],start=[.6,.2,.1,.1],transition=[[.15,.5,.3,.05],[.3,.1,.3,.3],[.25,.05,.05,.65],[.85,.05,.05,.05]],weights={N:{time:8,flies:3,arrow:8,like:1,an:.1},V:{time:1,flies:8,like:4,arrow:.1,an:.1},P:{time:.1,flies:.1,like:9,arrow:.1,an:.1},D:{time:.1,flies:.1,like:.1,arrow:.1,an:10}},emission=(state,word)=>{const row=weights[state],sum=K.sum(Object.values(row))+.2;return (row[word]??.2)/sum;},dp=[],back=[];
 for(let i=0;i<words.length;i++){const row=[],previous=[];for(let state=0;state<4;state++){const candidates=i?states.map((_,j)=>dp[i-1][j]+Math.log(transition[j][state])):start.map(x=>Math.log(x));const best=i?candidates.indexOf(Math.max(...candidates)):state;row[state]=(i?candidates[best]:Math.log(start[state]))+Math.log(emission(states[state],words[i]));previous[state]=best;}dp.push(row);back.push(previous);frames.push(F(`語${i+1}: ${words[i]}`,'各状態へ到達する最良の前状態を保存します。最後から逆にたどるまで、局所的に一つの品詞へ決めません。',K.table(['品詞候補','最大log得点','前の状態'],states.map((state,j)=>[state,q(row[j]),i?states[previous[j]]:'START']))));}
 const sequence=Array(words.length);sequence[words.length-1]=dp.at(-1).indexOf(Math.max(...dp.at(-1)));for(let i=words.length-1;i>0;i--)sequence[i-1]=back[i][sequence[i]];frames.push(F('最後から品詞列を復元する','それぞれの語で単独の最大値を選んだ列とは、違う場合があります。',K.table(['語','最良の系列品詞','語だけでの最大emission'],words.map((word,i)=>[word,states[sequence[i]],states[states.map(s=>emission(s,word)).indexOf(Math.max(...states.map(s=>emission(s,word))))]]))));return out(frames,{'推定した品詞列':sequence.map(i=>states[i]).join(' '),'最良log得点':q(Math.max(...dp.at(-1))),'語数':words.length});
});
const multiply=K.multiply;
D(131,{
 title:'Self-Attention・位置情報・Multi-Head・Transformer',question:'ある語の出力に、どの語の情報がどれだけ入る？',
 scope:'最大8token×8特徴の単一toy Transformer block。Q/K/V、scaled dot-product attention、causal mask、multi-head結合、残差・LayerNorm・2層ReLUを計算。未学習の公開seed重みで、文章生成モデルではありません。',
 sources:['d2l','slp'],
 controls:[t('tokens','空白区切りのtoken','私 は 通信 を 学ぶ'),code('vectors','各tokenの4次元特徴','1 0 0 1\n0 1 0 1\n1 1 0 0\n0 0 1 1\n1 0 1 0'),s('heads','head数',2,[1,2,4]),r('focus','注目するtoken番号',2,0,4),r('seed','重みseed',7,1,50),K.b('position','位置情報を加える',true),K.b('causal','未来のtokenをmaskする',true),K.b('normalization','残差後にLayerNorm',true)],
 alt:['未来のtokenへのmaskを外す',{causal:false}],
 intro:['Attentionは、現在のtokenが他のtokenの情報をどれだけ参照するかを数値で決めます。似ている語を説明するだけでなく、実際の重み付き和を追います。','入力からQuery・Key・Valueを作り、QとKの内積を尺度調整してsoftmaxにします。得た重みでVを混ぜ、複数headを結合して残差と次の変換へ渡します。','通信というtokenの行へ注目します。causal maskありでは後ろのを・学ぶへ重みを与えません。行の重みが1に足し合わさることを確認してください。','maskを外すと将来tokenの情報も入ります。位置情報、head数、正規化を切り替え、出力が実際に変わる場所を数値で確認できます。','この重みは学習していません。Attentionの重みだけから、人間の理由説明や因果的な重要度を断定しません。機構を理解するための一つのblockです。'],
 topics:[['Q/K/V','何を探すか、何を持つか、どの値を渡すかを別の変換にします。'],['softmaxとmask','候補の重みを正規化し、使えない位置を0にします。'],['位置情報','順序を明示的に入力へ加えます。'],['Multi-Head','別の部分空間の重み付き和を組み合わせます。'],['残差・LayerNorm・FFN','混合した後の表現を元入力と合わせ、さらに変換します。']],
 quiz:['causal maskを付けた位置iが参照できるのは？','その位置以前のtoken','必ず未来のtokenだけ','すべての重みが必ず同じ値','学習時にも予測対象より先の情報を混ぜないための制約です。'],
 tests:[[{},{'Attention行和の最大誤差':0}]]
},p=>{
 const tokens=p.tokens.trim().split(/\s+/),features=K.readMatrix(p.vectors,8);if(tokens.length!==features.length||tokens.length<1||tokens.length>8||features[0].length%Number(p.heads)!==0)throw Error('token数と行数を一致させ、特徴次元をhead数で割り切れる数にしてください。');const n=tokens.length,d=features[0].length,heads=Number(p.heads),dk=d/heads,random=L.rng(p.seed),weight=(a,b)=>Array.from({length:a},()=>Array.from({length:b},()=>random()-.5)),input=features.map((row,pos)=>row.map((x,i)=>x+(p.position?(i%2?Math.cos(pos/10000**(2*Math.floor(i/2)/d)):Math.sin(pos/10000**(2*Math.floor(i/2)/d))):0))),all=[],combined=Array.from({length:n},()=>[]);let maxError=0;
 for(let head=0;head<heads;head++){const Q=multiply(input,weight(d,dk)),Key=multiply(input,weight(d,dk)),V=multiply(input,weight(d,dk)),scores=Q.map((row,i)=>Key.map((key,j)=>p.causal&&j>i?-Infinity:K.dot(row,key)/Math.sqrt(dk))),attention=scores.map(row=>K.softMax(row)),output=multiply(attention,V);attention.forEach(row=>maxError=Math.max(maxError,Math.abs(K.sum(row)-1)));output.forEach((row,i)=>combined[i].push(...row));all.push({Q,Key,V,attention,output});}
 const projected=multiply(combined,weight(d,d)),residual=projected.map((row,i)=>row.map((x,j)=>x+input[i][j])),normalize=row=>{if(!p.normalization)return row;const m=mean(row),variance=mean(row.map(x=>(x-m)**2));return row.map(x=>(x-m)/Math.sqrt(variance+1e-5));},normalized=residual.map(normalize),hidden=multiply(normalized,weight(d,2*d)).map(row=>row.map(x=>Math.max(0,x))),feedForward=multiply(hidden,weight(2*d,d)),output=feedForward.map((row,i)=>normalize(row.map((x,j)=>x+normalized[i][j]))),focus=Math.min(p.focus,n-1),frames=[];
 frames.push(F('tokenと入力ベクトルを対応させる','数値は利用者が指定した特徴と位置情報から作っています。事前学習済みの語の意味ではありません。',K.matrix(input.map(row=>row.map(x=>q(x,3))),{rowLabels:tokens})));
 for(const [i,head]of all.entries()){frames.push(F(`Head ${i+1}: QとKの内積から重みを作る`,'行が問い合わせるtoken、列が参照するtokenです。maskした位置は0になります。',K.matrix(head.attention.map(row=>row.map(x=>q(x,4))),{rowLabels:tokens,colLabels:tokens,activeRow:focus})));frames.push(F(`Head ${i+1}: ${tokens[focus]}の重み付き和`,'各列のValueへそのtokenの重みを掛けて足します。head出力は文字列ではなくベクトルです。',K.table(['参照token','Attention重み','Value','重み×Value'],tokens.map((token,j)=>[token,q(head.attention[focus][j]),head.V[j].map(x=>q(x,3)).join(','),head.V[j].map(x=>q(x*head.attention[focus][j],3)).join(',')]))));}
 frames.push(F('head結合・残差・FFN後の値','Multi-Headの結果を結合・射影し、残差とLayerNorm、ReLUを含むFFNを計算しています。',K.matrix(output.map(row=>row.map(x=>q(x,4))),{rowLabels:tokens})));
 return out(frames,{'Attention行和の最大誤差':q(maxError,10),'head数':heads,'注目token':tokens[focus],'未来への重み':q(K.sum(all[0].attention[focus].slice(focus+1))),'出力ベクトル':output[focus].map(x=>q(x,4)).join(',')});
});
function naiveBayes(training){const labels=[...new Set(training.map(x=>x.label))],vocabulary=new Set(training.flatMap(x=>tokenize(x.text))),stats=Object.fromEntries(labels.map(label=>[label,{documents:0,counts:new Map(),tokens:0}]));for(const row of training){const stat=stats[row.label];stat.documents++;for(const word of tokenize(row.text)){stat.counts.set(word,(stat.counts.get(word)||0)+1);stat.tokens++;}}return {labels,predict:text=>{const words=tokenize(text),scores=labels.map(label=>{const stat=stats[label];return {label,score:Math.log(stat.documents/training.length)+K.sum(words.map(word=>Math.log(((stat.counts.get(word)||0)+1)/(stat.tokens+vocabulary.size+1))))};}).sort((a,b)=>b.score-a.score);return {label:scores[0].label,scores};}};}
const parseLabelled=source=>source.split('\n').filter(x=>x.trim()).map(line=>{const m=line.match(/^(\S+)\s+(.+)$/);if(!m)throw Error('行頭のlabelと、その後の文を空白で区切ってください。');return {label:m[1],text:m[2]};});
const grams=(words,n)=>{const map=new Map();for(let i=0;i+n<=words.length;i++){const key=words.slice(i,i+n).join('\u0001');map.set(key,(map.get(key)||0)+1);}return map;};
function generationMetrics(candidate,reference,smooth=true){const a=tokenize(candidate),b=tokenize(reference);if(!a.length||!b.length||a.length>80||b.length>80)throw Error('比較する文は1〜80語です。');const orders=Math.min(4,a.length),rows=[];let log=0;for(let n=1;n<=orders;n++){const x=grams(a,n),y=grams(b,n),matched=K.sum([...x].map(([key,count])=>Math.min(count,y.get(key)||0))),total=K.sum([...x.values()]),precision=smooth?(matched+1)/(total+1):matched/total;rows.push([n,matched,total,precision]);log+=precision?Math.log(precision):-Infinity;}const bp=Math.min(1,Math.exp(1-b.length/a.length)),bleu=bp*Math.exp(log/orders),lcs=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0)),distance=Array.from({length:a.length+1},(_,i)=>Array.from({length:b.length+1},(_,j)=>i===0?j:j===0?i:0));for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++){lcs[i][j]=a[i-1]===b[j-1]?lcs[i-1][j-1]+1:Math.max(lcs[i-1][j],lcs[i][j-1]);distance[i][j]=Math.min(distance[i-1][j]+1,distance[i][j-1]+1,distance[i-1][j-1]+(a[i-1]===b[j-1]?0:1));}const common=lcs[a.length][b.length],precision=common/a.length,recall=common/b.length;return {bleu,bp,rows,rouge:precision+recall?2*precision*recall/(precision+recall):0,wer:distance[a.length][b.length]/b.length,common,candidate:a,reference:b};}
K.generationMetrics=generationMetrics;K.naiveBayes=naiveBayes;
D(132,{
 title:'文書分類・検索・生成文を評価する',question:'正解率やBLEUが高ければ、どんな目的にも良い？',
 scope:'小さいMultinomial Naive Bayes分類器を実学習し混同行列を計算。別モードでTF-IDF検索のP@k/R@k/AP、単一参照sentence BLEU・ROUGE-L・WERを計算します。',
 sources:['slp'],
 controls:[s('mode','課題','classification',[['classification','文書分類'],['retrieval','文書検索'],['generation','生成文の比較']]),code('training','labelと学習文','net network routes packets\nnet secure network protects data\nfood fresh fruit tastes good\nfood food and fruit are enjoyable'),code('test','labelと評価文','net network packets\nfood fresh fruit\nnet secure data\nfood enjoyable food'),t('query','検索する文','network data'),r('topk','返す件数k',2,1,4),t('relevant','正解関連文書の番号','1,2'),t('candidate','生成された文','the cat is on the mat'),t('reference','参照文','the cat sat on the mat'),K.b('smooth','sentence BLEUを加一平滑化',true)],
 alt:['未知の表現を評価文に含める',{test:'net network packets\nfood tasty dinner\nnet secure data\nfood enjoyable food'}],
 intro:['自然言語処理の課題は、分類、検索、抽出、生成などで成功の意味が違います。同じ数字だけを見ず、何を正解としてどう数えたかを確認します。','分類はlabelの一致、検索は必要な文書を返した割合、生成は参照との語の一致などを測ります。目的に合う評価を選び、誤りの種類も読む必要があります。','4つの学習文でNaive Bayesを作り、別の4文を分類します。実際に推定したlabelから混同行列と各classのprecision・recallを求めます。','未知の表現を含む文へ変えると語彙外の扱いが影響します。検索のk、生成文の語順や長さも変えて、それぞれの指標が何を見ているか比較できます。','小さい固定データの値は実用システムの性能ではありません。参照との一致が低くても正しい言い換えはあり、指標だけで事実性や有害性を評価し切れません。'],
 topics:[['分類評価','precision、recall、F1をclassごとに分けます。'],['検索評価','上位kだけの評価と全順位でのAPを区別します。'],['生成評価','n-gram一致、長さ、最長共通部分列、編集操作を別々に測ります。'],['評価の限界','少数の参照と単語一致だけでは意味・事実の全てを確認できません。']],
 quiz:['参照文と異なるが意味の正しい言い換えは？','単語一致の指標が低く出る場合がある','BLEUが必ず1になる','指標が低ければ必ず誤りである','評価指標がどの性質を測るかと、利用目的を照合します。'],
 tests:[[{mode:'generation',candidate:'the cat sat',reference:'the cat sat'},{'BLEU':1,'ROUGE-L F1':1}]]
},p=>{
 const frames=[];
 if(p.mode==='generation'){const x=generationMetrics(p.candidate,p.reference,p.smooth);frames.push(F('n-gramの重複数をclipして数える','同じ語を繰り返すだけでは参照にある回数以上の一致を得られません。短い文では存在するn-gramの次数まで使う実効次数の設定です。',K.table(['n','clip一致数','候補総数','precision'],x.rows.map(row=>[...row.slice(0,3),q(row[3])]))));frames.push(F('異なる観点の指標を並べる','BLEUには短すぎる文へのpenaltyを掛けます。ROUGE-Lは順序を保つ共通部分列、WERは語の編集回数を参照長で割ります。',K.table(['観点','値'],[['brevity penalty',q(x.bp)],['BLEU',q(x.bleu)],['LCS語数',x.common],['ROUGE-L F1',q(x.rouge)],['WER',q(x.wer)]])));return out(frames,{'BLEU':q(x.bleu),'ROUGE-L F1':q(x.rouge),'WER':q(x.wer),'分類比較入力':p.test.length});}
 const training=parseLabelled(p.training);if(training.length<2||training.length>30)throw Error('学習文は2〜30行です。');
 if(p.mode==='retrieval'){const model=documentVectors(training.map(x=>x.text)),query=model.query(p.query),rank=training.map((row,i)=>({id:i+1,text:row.text,score:cosine(query,model.vectors[i])})).sort((a,b)=>b.score-a.score||a.id-b.id),relevant=new Set(K.numbers(p.relevant,1,30));if([...relevant].some(id=>!Number.isInteger(id)||id<1||id>training.length))throw Error('関連文書番号を範囲内で指定してください。');const k=Math.min(p.topk,rank.length),hits=rank.slice(0,k).filter(x=>relevant.has(x.id)).length;let cumulative=0,ap=0;rank.forEach((row,i)=>{if(relevant.has(row.id)){cumulative++;ap+=cumulative/(i+1);}});frames.push(F('同じqueryで文書を順位付けする','文書番号は学習文入力の行番号です。関連かどうかの正解は利用者が別に指定しています。',K.table(['順位','文書番号','cosine','関連','文'],rank.map((row,i)=>[i+1,row.id,q(row.score),relevant.has(row.id),row.text]))));return out(frames,{'P@k':q(hits/k),'R@k':q(hits/relevant.size),'AP':q(ap/relevant.size),'返す件数':k,'分類比較入力':p.test.length});}
 const model=naiveBayes(training),test=parseLabelled(p.test);if(!test.length||test.length>40||test.some(row=>!model.labels.includes(row.label)))throw Error('評価は1〜40行で、学習にあるlabelを指定してください。');const matrix=model.labels.map(()=>model.labels.map(()=>0)),rows=test.map(row=>{const predicted=model.predict(row.text);matrix[model.labels.indexOf(row.label)][model.labels.indexOf(predicted.label)]++;return [row.text,row.label,predicted.label,row.label===predicted.label];}),metrics=model.labels.map((label,i)=>{const tp=matrix[i][i],fp=K.sum(matrix.map(row=>row[i]))-tp,fn=K.sum(matrix[i])-tp,precision=tp+fp?tp/(tp+fp):0,recall=tp+fn?tp/(tp+fn):0,f1=precision+recall?2*precision*recall/(precision+recall):0;return [label,precision,recall,f1];});frames.push(F('別の文を実際に分類する','単語ごとの条件付き頻度とclass事前確率から、最も高いlog得点のclassを選びます。',K.table(['評価文','正解','推定','一致'],rows)));frames.push(F('正解と推定を別の軸にする','行は正解、列は推定です。どのclassへ誤分類したかを確認します。',K.matrix(matrix,{rowLabels:model.labels,colLabels:model.labels})));frames.push(F('classごとの評価を計算する','予測が一度もないclassのprecisionはここでは0と定めています。macro平均と全体の正解率を区別します。',K.table(['class','precision','recall','F1'],metrics.map(row=>[row[0],...row.slice(1).map(q)]))));return out(frames,{'評価正解率':q(rows.filter(row=>row[3]).length/rows.length),'macro F1':q(K.sum(metrics.map(row=>row[3]))/metrics.length),'評価文数':rows.length});
});
})();
