/* Direct objects rather than a precomputed movie: click a bit, push a value,
 * call a method or decide which process performs its next instruction. */
(() => {
'use strict';
const L=CSL,X=L.experiences,h=L.h,F=X.format,B=X.html.button,T=X.html.table;
X.registerWidget('bits',(root,a,c)=>{
 const s=X.scope(root,c),distance=a.variant==='distance';let value=42,other=35;
 const paint=()=>{
  const bitrow=(n,name)=>Array.from({length:8},(_,i)=>{const k=7-i,on=!!(n&(1<<k));return `<button class="ex-bit${on?' on':''}" type="button" data-bit-row="${name}" data-bit-index="${k}" aria-pressed="${on}" aria-label="${name}の2の${k}乗の桁を反転"><strong>${+on}</strong><small>${2**k}</small></button>`;}).join('');
  root.innerHTML=`<p class="ex-operation-hint">上段の0／1を押してください。下の小さな数は、その桁の重みです。</p><div class="ex-bit-row" aria-label="最初のビット列">${bitrow(value,'X')}</div>${distance?`<div class="ex-bit-row" aria-label="比較するビット列">${bitrow(other,'Y')}</div>`:''}<div class="ex-bit-readout">${distance?`<h4>違う位置だけを数える</h4><div class="ex-bit-row">${Array.from({length:8},(_,i)=>`<div class="ex-bit${((value^other)>>(7-i))&1?' on':''}">${((value^other)>>(7-i))&1}</div>`).join('')}</div><p>XORが1の列は${L.bits(value^other).split('').filter(x=>x==='1').length}個。これがハミング距離です。桁の数値の重みは掛けません。</p>`:`<h4>同じビットを二通りに読む</h4>${X.html.formula('符号なし：'+Array.from({length:8},(_,i)=>((value>>(7-i))&1)?2**(7-i):null).filter(x=>x!==null).join(' + ')+' = '+value)}${X.html.formula('2の補数：'+((value&128)?'−128 + '+(value&127):String(value))+' = '+(value&128?value-256:value))}<p>2の補数では最上位桁の重みを−128として読みます。単に「負の印を付けて、残りを絶対値として読む」方式とは違います。</p>`}</div><div class="ex-actions">${B('全て0にする','data-bit-zero')}${B('11111111にする','data-bit-all')}</div><p data-ex-status role="status"></p>`;
  c.completed.add(s.id);
 };
 s.on(root,'click',e=>{const b=e.target.closest('[data-bit-index]');if(b){const mask=1<<Number(b.dataset.bitIndex);if(b.dataset.bitRow==='X')value^=mask;else other^=mask;const selector=`[data-bit-row="${b.dataset.bitRow}"][data-bit-index="${b.dataset.bitIndex}"]`;paint();root.querySelector(selector).focus({preventScroll:true});}else if(e.target.closest('[data-bit-zero]')){value=0;other=0;paint();}else if(e.target.closest('[data-bit-all]')){value=255;paint();}});paint();
});
X.registerWidget('utf8',(root,a,c)=>{
 const s=X.scope(root,c);let text='Aあ🔒',selected=0;
 root.innerHTML=`<form class="ex-inputs"><label>符号化する文字列<input name="text" type="text" value="Aあ🔒" maxlength="40"></label><button type="submit" class="ex-button">文字とバイトを並べる</button></form><div data-utf-items></div><div data-utf-details></div>`;
 function paint(){const points=Array.from(text),bytes=new TextEncoder().encode(text),offsets=[];let n=0;for(const p of points){offsets.push(n);n+=new TextEncoder().encode(p).length;}selected=Math.max(0,Math.min(selected,points.length-1));
  root.querySelector('[data-utf-items]').innerHTML=`<p>${points.length}コードポイント、${bytes.length}byte。見た目の文字の数とコードポイント数は、結合文字などで異なる場合があります。</p><div class="ex-character-strip">${points.map((p,i)=>`<button type="button" class="ex-character" data-utf-select="${i}" aria-pressed="${i===selected}"><strong>${h(p)}</strong><small>U+${p.codePointAt(0).toString(16).toUpperCase()}</small><code>${[...new TextEncoder().encode(p)].map(b=>b.toString(16).padStart(2,'0')).join(' ')}</code></button>`).join('')}</div>`;
  const p=points[selected];if(!p){root.querySelector('[data-utf-details]').textContent='空文字列のバイト数は0です。';return;}
  const code=p.codePointAt(0),bs=[...new TextEncoder().encode(p)],prefixes=bs.length===1?[1]:[bs.length+1,...bs.slice(1).map(()=>2)];
  root.querySelector('[data-utf-details]').innerHTML=`<h4>「${h(p)}」の番号をバイトへ分ける</h4>${X.html.formula('U+'+code.toString(16).toUpperCase()+' = '+code+' = '+code.toString(2)+'₂')}<div class="ex-byte-strip">${bs.map((b,i)=>{const str=b.toString(2).padStart(8,'0'),cut=prefixes[i];return `<code><span class="ex-prefix-bits">${str.slice(0,cut)}</span>${str.slice(cut)}</code>`;}).join('')}</div><p>色付きの先頭部分はUTF-8の形式を示します。残る部分が文字の番号のビットです。この文字は、全体のbyte位置${offsets[selected]}から${offsets[selected]+bs.length-1}に入ります。</p>`;c.completed.add(s.id);
 }
 s.on(root.querySelector('form'),'submit',e=>{e.preventDefault();text=e.target.elements.text.value;selected=0;paint();});s.on(root,'click',e=>{const b=e.target.closest('[data-utf-select]');if(b){selected=Number(b.dataset.utfSelect);paint();root.querySelector(`[data-utf-select="${selected}"]`)?.focus();}});paint();
});
X.registerWidget('float',(root,a,c)=>{
 const s=X.scope(root,c);root.innerHTML='<form class="ex-inputs"><label>保存したい値<input name="value" type="number" step="any" value="0.1" min="-1e30" max="1e30" required></label><button type="submit" class="ex-button">近くの保存可能値を調べる</button></form><div data-float-result></div><p data-ex-status role="status"></p>';
 function draw(x){const buf=new ArrayBuffer(4),dv=new DataView(buf);dv.setFloat32(0,x);const stored=dv.getFloat32(0),word=dv.getUint32(0),bits=word.toString(2).padStart(32,'0');
  const at=b=>{dv.setUint32(0,b>>>0);return dv.getFloat32(0);};const lower=stored===0?-at(1):at(word+(stored>0?-1:1)),upper=stored===0?at(1):at(word+(stored>0?1:-1));
  const f=n=>Number(n).toPrecision(17),range=upper-lower,pct=(x-lower)/range*100;
  root.querySelector('[data-float-result]').innerHTML=`<h4>この近くでは、保存できる値は飛び飛びです</h4><div class="ex-number-line"><span style="left:0%" title="${f(lower)}">●</span><span style="left:${(stored-lower)/range*100}%" title="${f(stored)}">●</span><span style="left:100%" title="${f(upper)}">●</span><i style="left:${Math.max(0,Math.min(100,pct))}%" title="入力値">▼</i></div>${T(['値','数値'],[['直前のbinary32',f(lower)],['保存されたbinary32',f(stored)],['直後のbinary32',f(upper)],['入力値',f(x)],['保存後−入力',f(stored-x)]])}<div class="ex-binary32"><span>${bits.slice(0,1)}</span><span>${bits.slice(1,9)}</span><span>${bits.slice(9)}</span></div><p>左から符号1bit、指数8bit、仮数部23bit。今回の入力自体はJavaScriptのbinary64なので、十進文字列の厳密な有理数との誤差は別です。ここではbinary64からbinary32への丸めを観察しています。</p>`;c.completed.add(s.id);
 }
 s.on(root.querySelector('form'),'submit',e=>{e.preventDefault();if(e.target.reportValidity())draw(Number(e.target.elements.value.value));});draw(.1);
});
X.registerWidget('entropy',(root,a,c)=>{
 const s=X.scope(root,c);let weights=[4,2,1,1],active=0;
 function paint(){const sum=weights.reduce((n,x)=>n+x,0),p=weights.map(w=>w/sum),info=p.map(p=>p?-Math.log2(p):0),terms=p.map((p,i)=>p*info[i]),total=terms.reduce((n,x)=>n+x,0);
  root.innerHTML=`<p>箱の札が多い記号ほど出やすいとします。これは、どの札も同じ確率で一枚選ぶ小さな情報源です。</p><div class="ex-frequency-boxes">${weights.map((n,i)=>`<section><h4>${'ABCD'[i]}</h4><div class="ex-tokens">${Array.from({length:n},()=>'<span>'+ 'ABCD'[i]+'</span>').join('')||'<small>札なし</small>'}</div><div>${B('1枚減らす',`data-count="${i}" data-delta="-1"${n===0||sum===1?' disabled':''}`)}${B('1枚増やす',`data-count="${i}" data-delta="1"${n>=12?' disabled':''}`)}</div></section>`).join('')}</div><div class="ex-contribution-list">${p.map((p,i)=>`<button type="button" data-info-row="${i}" aria-pressed="${i===active}"><strong>${'ABCD'[i]}</strong><span>確率 ${weights[i]}/${sum}</span><span>情報量 ${p?F(info[i],3):'この出来事は起きない'} bit</span><span>平均への寄与 ${F(terms[i],3)} bit</span></button>`).join('')}</div><div class="ex-why"><h4>${'ABCD'[active]}の行を読む</h4><p>${p[active]?`${sum}枚の中に${weights[active]}枚あるので、確率は${weights[active]}/${sum}です。起きたと知ったときの情報量は${F(info[active],4)} bit。その情報を得る頻度で重み付けした${F(terms[active],4)} bitを平均へ足します。`:'確率0の項は極限として0を寄与させます。実際には選ばれない札の情報量を有限の0 bitと主張するものではありません。'}</p></div>${X.html.formula('H = '+terms.map(x=>F(x,3)).join(' + ')+' = '+F(total,4)+' bit / 記号')}<div class="ex-actions">${B('全て同じ枚数にする','data-equal')}${B('Aだけの箱にする','data-certain')}</div><p data-ex-status role="status">${Math.abs(total-2)<1e-8?'4種類が等確率なので最大の2 bitです。':'総当たりで当てやすい偏りが増えると、この平均は小さくなります。'}</p>`;c.completed.add(s.id);
 }
 s.on(root,'click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-count')){const i=+b.dataset.count;weights[i]+=+b.dataset.delta;active=i;}if(b.hasAttribute('data-info-row'))active=+b.dataset.infoRow;if(b.hasAttribute('data-equal'))weights=[2,2,2,2];if(b.hasAttribute('data-certain'))weights=[8,0,0,0];paint();});paint();
});
X.registerWidget('container',(root,a,c)=>{
 const s=X.scope(root,c),kind=a.variant==='queue'?'queue':'stack';let state={items:[],output:[],history:[]};
 root.innerHTML=`<p>${kind==='queue'?'入口は右、出口は左です。先に入った値から取り出します。':'同じ入口から入れ、最後に入った値から取り出します。'}</p><form class="ex-inputs"><label>追加する値<input name="value" value="7" maxlength="16" required></label><button type="submit" class="ex-button ex-primary">${kind==='queue'?'enqueue：列の後ろへ追加':'push：一番上へ追加'}</button></form><div class="ex-actions">${B(kind==='queue'?'dequeue：先頭を取り出す':'pop：一番上を取り出す','data-container-take')}${B('最初からやり直す','data-container-reset')}</div><div data-container-state></div><p data-ex-status role="status"></p><div data-container-history></div>`;
 function paint(){root.querySelector('[data-container-state]').innerHTML=`<div class="ex-container ${kind}">${state.items.map((v,i)=>`<div><small>${kind==='queue'?(i===0?'次に取り出す':'待機中'):(i===state.items.length-1?'次に取り出す':'下で待つ')}</small><strong>${h(v)}</strong></div>`).join('')||'<p>いまは空です</p>'}</div><p>取り出した順：${h(state.output.join(' → ')||'まだありません')}</p>`;root.querySelector('[data-container-history]').innerHTML=T(['操作','値','操作後に残る値'],state.history.map(r=>[r.action,r.value??'—',r.after.join(', ')||'空']));root.querySelector('[data-ex-status]').textContent=state.history.at(-1)?.action||'最初の値を追加してください。';c.completed.add(s.id);}
 function act(action,value){try{state=X.models.container(state,action,value,kind);paint();}catch(e){s.error(e);}}
 s.on(root.querySelector('form'),'submit',e=>{e.preventDefault();if(e.target.reportValidity())act('put',e.target.elements.value.value);});s.on(root,'click',e=>{if(e.target.closest('[data-container-take]'))act('take');if(e.target.closest('[data-container-reset]')){state={items:[],output:[],history:[]};paint();}});paint();
});
X.registerWidget('race',(root,a,c)=>{
 const s=X.scope(root,c);let state;
 const reset=lock=>{state={shared:100,lock,owner:null,actors:{A:{pc:0,local:null,delta:10},B:{pc:0,local:null,delta:20}},history:[]};paint();};
 function paint(){root.innerHTML=`<p>Aは10、Bは20を、同じ値へ加えたいとします。両方終われば130になってほしい、という問題です。</p><div class="ex-shared-value">共有の値 <strong>${state.shared}</strong><span>${state.lock?'ロックの保持者：'+(state.owner||'なし'):'排他制御なし'}</span></div><div class="ex-side-by-side">${Object.entries(state.actors).map(([name,p])=>`<section><h4>処理${name}</h4><p>自分が読んだ作業用の値：<strong>${p.local??'まだ読んでいない'}</strong></p><ol>${['共有値を読む','自分の値に'+p.delta+'を足す','共有値へ書き戻す'].map((v,i)=>`<li${i===p.pc?' aria-current="step"':''}>${v}${i<p.pc?' ✓':''}</li>`).join('')}</ol>${B(p.pc<3?name+'の次の命令を実行':'終了',`data-race-actor="${name}"${p.pc>=3?' disabled':''}`)}</section>`).join('')}</div><p data-ex-status role="status">${h(state.history.at(-1)||'どちらを先に進めるか選べます。')}</p><ol class="ex-persistent-log">${state.history.map(t=>'<li>'+h(t)+'</li>').join('')}</ol><div class="ex-actions">${B('ロックなしで最初から','data-race-reset="false"')}${B('ロックを付けて最初から','data-race-reset="true"')}</div><p class="ex-counterexample">AとBを両方「読む」まで進めると、二人とも100を覚えます。その後の書込みは加算ではなく、自分の作業用の値による置換です。</p>`;c.completed.add(s.id);}
 s.on(root,'click',e=>{const actor=e.target.closest('[data-race-actor]'),r=e.target.closest('[data-race-reset]');if(actor){state=X.models.race(state,actor.dataset.raceActor);paint();}if(r)reset(r.dataset.raceReset==='true');});reset(false);
});
X.registerWidget('objects',(root,a,c)=>{
 const s=X.scope(root,c);let objects={a:{value:10},b:{value:3}},alias=false,privateValue=true,log=[];
 function paint(){root.innerHTML=`<div class="ex-class-blueprint"><h4>設計図 Counter</h4><pre>valueを持つ\nadd(n)：自分のvalueへnを足す\nread()：自分のvalueを読む</pre><p>設計図を共有しても、aとbのデータは別々です。</p></div><div class="ex-side-by-side">${Object.entries(objects).map(([name,obj])=>`<section><h4>インスタンス ${name}</h4><p>内部のvalue：<strong>${obj.value}</strong></p>${B(name+'.add(1)',`data-object="${name}" data-method="add"`)}${B(name+'.read()',`data-object="${name}" data-method="read"`)}${B(name+'.value = 99',`data-object="${name}" data-method="set"`)}</section>`).join('')}</div><div class="ex-actions">${B(alias?'bを別の個体へ戻す':'bもaと同じ個体を指す（b = a）','data-object-alias')}${B(privateValue?'publicへ変える':'privateへ変える','data-object-private')}</div><p>現在：${alias?'aとbは同じ個体への別名です。':'aとbは別の個体です。'} valueは${privateValue?'private':'public'}です。</p><p data-ex-status role="status">${h(log.at(-1)||'メソッドを呼ぶ相手を選んでください。')}</p><ol>${log.map(v=>'<li>'+h(v)+'</li>').join('')}</ol>`;c.completed.add(s.id);}
 s.on(root,'click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-object')){const name=b.dataset.object,method=b.dataset.method;if(method==='add'){objects[name].value++;log.push(name+'.add(1)で相手の値を増やしました。');}if(method==='read')log.push(name+'.read() → '+objects[name].value);if(method==='set'){if(privateValue)log.push('直接の代入は拒否。状態を変える入口をadd()へ限定しています。');else{objects[name].value=99;log.push(name+'の公開された値を直接99へ変えました。');}}}if(b.hasAttribute('data-object-alias')){alias=!alias;objects.b=alias?objects.a:{value:3};log.push(alias?'bへaの参照を代入しました。個体をコピーしたのではありません。':'bを別の個体として作り直しました。');}if(b.hasAttribute('data-object-private'))privateValue=!privateValue;paint();});paint();
});
})();
