(() => {
'use strict';
const L=CSL,A=L.app,{h,icon}=L;
const render=(body,title,nav)=>{A.setTitle(title);A.setNav(nav,title);document.getElementById('main').innerHTML=body+A.footer();};
const count=t=>L.labs.filter(l=>l.track===t).length;
const areaCards=()=>L.areas.map(a=>`<a class="area-card" href="#/catalog?area=${a.id}"><div>${icon(a.icon)}<span>${L.labs.filter(l=>l.area===a.id).length} 実験</span></div><h3>${h(a.name)}</h3><p>${h(a.description)}</p></a>`).join('');
const topicLink=(tr,i)=>`#/catalog?track=${tr}&topic=${tr==='network'?'N':'S'}${String(i+1).padStart(2,'0')}`;
const empty=()=>`<div class="empty-state panel search-empty">${icon('search',28)}<h3>条件に合う単元が見つかりません。</h3><p>「通信」「暗号」「メモリ」など短い言葉にするか、絞り込みを解除してください。</p>${A.link('#/catalog','すべての単元に戻る','reset')}</div>`;
A.views.home=()=>{
  render(`<section class="library-hero"><div class="eyebrow">VISUAL CS LAB / OPEN EXPERIMENT LIBRARY</div><h1>学びたい単元へ、<span>まっすぐ。</span></h1><p>通信の仕組みも、コンピュータの内部も。<br class="mobile-only">条件を変えて、見て、確かめる実験室。</p><form id="home-search-form" class="home-search" role="search">${icon('search',23)}<label class="sr-only" for="home-query">学びたい単元や用語</label><input id="home-query" name="q" type="search" placeholder="TCP、認証、メモリ、ソート…" autocomplete="off"><button type="submit" class="btn primary">単元を探す ${icon('arrow',17)}</button></form><div class="quick-terms"><span>よく使う入口</span>${['TCP','DNS','暗号','認証','Git','CPU'].map(q=>`<button type="button" data-action="home-query" data-query="${q}">${q}</button>`).join('')}</div></section><section id="home-results" aria-label="単元の検索結果" hidden></section><div id="home-browse"><section class="track-entry-grid" aria-label="分野別の入口">${[
 ['network','ネットワーク','パケットの流れ、アドレス、経路、通信のトラブルを操作する。'],
 ['security','セキュリティ','暗号、認証、権限、防御の条件を変えて境界を確かめる。'],
 ['core','情報科学の基礎・応用','数とコードからCPU、数学、データ、AIまで。'],
 ['missions','総合演習','仕組みを組み合わせ、構築・診断・修正を試す。']
 ].map(([tr,title,desc])=>`<a class="track-entry ${tr}" href="#/catalog?track=${tr}"><div class="track-entry-top">${icon(A.trackIcon(tr),22)}<span>${count(tr)} 実験</span></div><h2>${title}</h2><p>${desc}</p><span class="section-link">単元を見る ${icon('arrow',16)}</span></a>`).join('')}</section><section class="quick-specialization"><div class="section-title"><div><h2>専門のテーマから探す</h2><p>授業で出てきた言葉から、そのまま実験へ。</p></div>${A.link('#/curriculum','科目名から探す','book','sm ghost')}</div><div class="specialization-grid">${['network','security'].map(tr=>`<div class="panel topic-directory"><h3>${icon(A.trackIcon(tr),18)}${A.trackName(tr)}</h3><div>${L.topics[tr].slice(0,8).map((name,i)=>`<a href="${topicLink(tr,i)}">${h(name)} ${icon('chevron',12)}</a>`).join('')}</div><a href="#/catalog?track=${tr}" class="section-link">全${L.topics[tr].length}テーマを見る ${icon('arrow',14)}</a></div>`).join('')}</div></section><section><div class="section-title"><div><h2>初めてなら、ここから。</h2><p>入力を変えるだけで始められる4つの実験です。</p></div><a href="#/routes" class="section-link">おすすめの順番 ${icon('arrow',14)}</a></div><div class="lab-grid home-picks">${['n01-packet','c01-bits','n11-tcp','s08-access'].map(id=>A.labCard(A.lab(id))).join('')}</div></section><section><div class="section-title"><div><h2>情報科学の20分野</h2><p>専門を支える基礎も、気になった分野も。</p></div><a href="#/map" class="section-link">分野のつながり ${icon('arrow',14)}</a></div><div class="area-grid">${areaCards()}</div></section></div>`, '学びたいことから','home');
};
A.homeSearch=q=>{
  const results=document.getElementById('home-results'),browse=document.getElementById('home-browse'); if(!results)return;
  const active=!!q.trim(); results.hidden=!active;browse.hidden=active;
  if(!active){results.innerHTML='';return;}
  const labs=A.searchLabs(q);
  results.innerHTML=`<div class="section-title"><div><h2>「${h(q)}」の実験</h2><p role="status">${labs.length}件。選ぶとすぐに実験を開けます。</p></div><button class="btn sm ghost" type="button" data-action="home-query" data-query="">${icon('close',14)}検索をクリア</button></div><div class="lab-grid">${labs.map(A.labCard).join('')||empty()}</div>`;
};
A.catalogSelection=()=>{
  const p=A.params,track=p.get('track')||'',area=p.get('area')||'',q=p.get('q')||'',level=p.get('level')||'',topic=p.get('topic')||'';
  return A.searchLabs(q).filter(l=>(!track||l.track===track)&&(!area||l.area===area)&&(!level||l.level===+level)&&(!topic||l.topic===topic));
};
A.updateCatalogResults=()=>{
  const labs=A.catalogSelection(),el=document.getElementById('catalog-results');if(!el)return;
  document.getElementById('catalog-count').textContent=`${labs.length} 件の実験`;
  el.innerHTML=labs.map(A.labCard).join('')||empty();
};
A.catalogSearch=q=>{
  q=q.slice(0,200);if(q)A.params.set('q',q);else A.params.delete('q');
  // URL state is the current filter, not a saved learning history.
  try{history.replaceState(null,'','#/catalog'+(A.params.size?'?'+A.params.toString():''));}catch{}
  A.updateCatalogResults();
};
A.views.catalog=(_,params)=>{
 const tr=params.get('track')||'',area=params.get('area')||'',q=params.get('q')||'',level=params.get('level')||'',topic=params.get('topic')||'';
 const title=tr?A.trackName(tr):area?A.area(area)?.name||'すべての単元':'すべての単元';
 const desc=tr==='network'?'20テーマ。データの流れから、経路・性能・障害診断まで。':tr==='security'?'24テーマ。暗号・認証・防御・調査を、条件を変えて確かめます。':tr==='missions'?'複数の知識を組み合わせ、構築・判断・修正を試します。':'単元名、用語、科目名から検索できます。どの単元もすぐに開けます。';
 const topics=L.topics[tr];
 render(`${A.heading('EXPERIMENT LIBRARY',title,desc)}<div class="catalog-toolbar"><div class="tabs" aria-label="実験の種類">${[['','すべて'],['network','ネットワーク'],['security','セキュリティ'],['core','基礎・応用'],['missions','総合']].map(([v,t])=>`<button type="button" class="tab${tr===v?' active':''}" aria-pressed="${tr===v}" data-filter="track" data-value="${v}">${t}<span class="count">${v?count(v):L.labs.length}</span></button>`).join('')}</div></div><form class="inline-search catalog-search" id="catalog-search" role="search">${icon('search',20)}<label class="sr-only" for="catalog-query">単元と用語を検索</label><input id="catalog-query" name="q" aria-controls="catalog-results" placeholder="単元名・用語・科目名（例：TCP、行列、暗号理論）" type="search" value="${h(q)}" autocomplete="off"><button type="submit" class="btn icon-only ghost" aria-label="検索する">${icon('arrow',17)}</button></form><div class="filter-row"><label for="filter-area"><span>分野</span><select id="filter-area" data-filter-select="area"><option value="">すべての分野</option>${L.areas.map(a=>`<option value="${a.id}"${area===a.id?' selected':''}>${h(a.name)}</option>`).join('')}</select></label>${topics?`<label for="filter-topic"><span>専門テーマ</span><select id="filter-topic" data-filter-select="topic"><option value="">すべてのテーマ</option>${topics.map((name,i)=>{const id=(tr==='network'?'N':'S')+String(i+1).padStart(2,'0');return `<option value="${id}"${topic===id?' selected':''}>${id} · ${h(name)}</option>`;}).join('')}</select></label>`:''}<label for="filter-level"><span>段階</span><select id="filter-level" data-filter-select="level"><option value="">すべての段階</option>${[['1','入門'],['2','基礎＋'],['3','発展']].map(([v,t])=>`<option value="${v}"${level===v?' selected':''}>${t}</option>`).join('')}</select></label>${A.link('#/catalog','絞り込みを解除','close','sm ghost')}</div><div class="results-caption"><span id="catalog-count" role="status"></span><span>単元を選ぶ → 条件を変える → 結果を見る</span></div><div class="lab-grid" id="catalog-results"></div>`,title,tr||'catalog');
 A.updateCatalogResults();
};
A.filter=(key,value)=>{
 const p=new URLSearchParams(A.params);if(value)p.set(key,value);else p.delete(key);
 if(key==='track'){p.delete('area');p.delete('topic');}
 if(key==='area'){p.delete('track');p.delete('topic');}
 p.delete('favorites');
 location.hash='/catalog'+(p.size?'?'+p.toString():'');
};
A.views.routes=()=>render(`${A.heading('SUGGESTED ORDER','迷ったときの、おすすめの順番。','前提から順に触れるための案内です。履修や理解度を記録せず、どの実験からでも開けます。')}<div class="route-grid">${L.routes.map((r,i)=>`<a class="route-card panel" href="#/route/${r.id}"><div class="square-icon">${icon(r.icon||'route',22)}</div><div class="route-card-content"><div class="eyebrow">ROUTE ${String(i+1).padStart(2,'0')}</div><h3>${h(r.name)}</h3><p>${h(r.description)}</p><div class="route-meta"><span>${r.labs.length} 実験</span><span>順番と内容を見る</span>${icon('arrow',16)}</div></div></a>`).join('')}</div><div class="info-banner">${icon('info',18)}<span>サイト独自の案内です。大学の履修年次・必修条件を置き換えるものではありません。</span></div>`,'おすすめの順番','routes');
A.views.route=parts=>{
 const r=L.routes.find(x=>x.id===parts[0]);if(!r)return A.views.notfound();
 render(`${A.heading('SUGGESTED ORDER',r.name,r.description,A.link('#/lab/'+r.labs[0],'最初の単元を開く','arrow','primary'))}<div class="route-summary panel"><span>${r.labs.length}の実験をつなぐ案内</span><span>途中の単元からも自由に始められます。</span></div><div class="route-detail">${r.labs.map((id,i)=>{const lab=A.lab(id);return `<div class="route-step"><span class="step-circle">${String(i+1).padStart(2,'0')}</span><a class="route-step-card panel" href="#/lab/${id}"><div><div class="route-step-tag">${A.pill(lab.track)}</div><h3>${h(lab.unit)}</h3><p>${h(lab.summary)}</p></div><div class="route-step-end"><span>${lab.minutes} 分の目安</span>${icon('arrow',18)}</div></a></div>`;}).join('')}</div>`,r.name,'routes');
};
A.views.map=()=>{
 const groups=[{name:'情報と数学',ids:['C01','C02','C03']},{name:'コードと手順',ids:['C04','C05','C06','C07','C16']},{name:'コンピュータ内部',ids:['C08','C09','C10','C11','C12']},{name:'通信・保存・防御',ids:['C13','C14','C15']},{name:'データと実世界',ids:['C17','C18','C19','C20']}];
 render(`${A.heading('THE BIG PICTURE','知識のつながりを見つける。','ひとつの仕組みを、別の分野から見る。分野を開くと、対応する実験へ進めます。')}<div class="map-columns">${groups.map(g=>`<section class="map-column"><h3>${h(g.name)}</h3>${g.ids.map(id=>{const a=A.area(id),labs=L.labs.filter(l=>l.area===id);return `<a class="map-node" href="#/catalog?area=${id}"><div class="map-node-header">${icon(a.icon,18)}<span>${id}</span></div><h4>${h(a.name)}</h4><p class="muted">${h(a.description)}</p><div class="map-node-count">${labs.length} 実験を開く ${icon('arrow',12)}</div></a>`;}).join('')}</section>`).join('')}</div><div class="section-title"><div><h2>専門へつながる、小さな橋。</h2><p>基礎が必要になったとき、その場で戻れます。</p></div></div><div class="bridge-grid">${[
 ['0と1 → アドレス','c01-bits','n04-subnet','同じビット列を、IPアドレスとネットワークの区切りとして読む。'],['グラフ → 経路','c06-graph','n08-routing','探索の考え方を、通信するための道の選択へつなぐ。'],['確率 → 検知','c03-bayes','s17-detection','「警告が出た」と「本当に異常だった」を分けて考える。'],['メモリ → 安全性','c10-pointer','s14-buffer','値が正しいかだけでなく、参照できる場所と期間を確かめる。'],['ハッシュ → 証明','s04-hash','s04-signature','内容の変化を検知することと、作成者を検証することを分ける。'],['通信 → 信頼','n10-transport','s06-tls','接続した相手が、期待した相手かを確認する。']
 ].map(([title,a,b,desc])=>`<article class="panel bridge-card"><h3>${h(title)}</h3><p>${h(desc)}</p><div><a href="#/lab/${a}">${h(A.lab(a).unit)}</a>${icon('arrow',14)}<a href="#/lab/${b}">${h(A.lab(b).unit)}</a></div></article>`).join('')}</div>`,'学習マップ','map');
};
A.views.curriculum=()=>render(`${A.heading('COURSE CONNECTIONS','授業の言葉を、触れる実験へ。','提供された学修要覧の科目名を入口に、関連する実験をまとめました。')}<div class="info-banner">${icon('book',20)}<div><strong>学修要覧と、独自の教材設計を区別しています。</strong><br>科目名は「情報理工学部 学修要覧 2026」pp.36–37 / 40–41に基づきます。下の対応は独自の提案です。授業の実際の内容・実施順・試験範囲を保証するものではありません。</div></div><div class="course-grid">${L.courses.map(c=>`<article class="course-card panel"><div class="eyebrow">COURSE → EXPERIMENT</div><h3>${h(c.name)}</h3>${c.labs.map(id=>A.lab(id)?`<a class="course-lab" href="#/lab/${id}">${icon('flask',14)}<span>${h(A.lab(id).unit)}<small>${h(A.lab(id).summary)}</small></span>${icon('chevron',13)}</a>`:'').join('')}</article>`).join('')}</div>`,'授業から探す','curriculum');
A.views.sources=()=>render(`${A.heading('MODEL, SCOPE & SOURCES','見えているものの、前提を知る。','現実のすべてを再現するのではなく、確かめたい仕組みに焦点を当てています。')}<div class="model-grid"><article class="model-card panel"><h3>実際に計算する実験</h3><p>ソート、経路探索、ビット表現、CPU命令、メモリ配置、待ち行列などは、入力から状態を計算しています。AES-GCM・SHA-256・HMAC・ECDSA・PBKDF2はブラウザのWeb Cryptoを使用します。</p></article><article class="model-card panel"><h3>範囲を絞った概念モデル</h3><p>TLS、無線、Webの脆弱性、防御設定、クラウド、総合設計演習などは条件・手順の教材です。実際の通信・攻撃・脆弱性検査を行いません。各実験の「モデルと根拠」に範囲を表示します。</p></article><article class="model-card panel"><h3>学修要覧との関係</h3><p>資料から使用したのは、科目名と分野の対応です。実験内容・コード・問い・課題・数値はこのサイト独自のものです。特定授業のシラバスや公式教材ではありません。</p></article><article class="model-card panel"><h3>時間と、再現性</h3><p>再生速度は観察のためのものです。モデル内の時間や結果は変わりません。擬似乱数を使う実験は同じseedで計算し直せます。条件は画面を離れると初期化されます。ECDSAの鍵・署名は毎回生成されるため、値そのものは再現されません。</p></article></div><div class="section-title"><div><h2>参考資料と実装の位置づけ</h2><p>仕様の存在は、この教材の全機能が仕様準拠であることを意味しません。対象の範囲を併せて確認してください。</p></div></div><div class="source-list">${Object.entries(L.sources).map(([id,s])=>`<article class="source-card panel"><div class="eyebrow">${h(s.type||'PRIMARY REFERENCE')}</div><h3>${h(s.name)}</h3>${s.detail?`<p>${h(s.detail)}</p>`:''}${s.url?`<a href="${h(s.url)}" target="_blank" rel="noopener noreferrer">参考資料を開く ${icon('external',13)}</a>`:''}<div class="source-usage">${L.labs.filter(l=>l.sources.includes(id)).length} 件の実験で参照</div></article>`).join('')}</div><div class="info-banner">${icon('shield',19)}<span>入力と計算は端末内だけで行い、学習履歴は保存しません。外部API、アクセス解析、外部フォント、実ネットワークへのスキャンは使用しません。参考資料のリンクを自分で開く場合のみ、外部サイトへ移動します。</span></div>`,'教材と参考資料','sources');
A.views.settings=()=>render(`${A.heading('HOW TO USE','探して、変えて、確かめる。','ログインや学習記録は不要です。気になる単元を選び、その場で試してください。')}<div class="help-grid"><section class="setting-card panel"><h2>単元を探す</h2><p>トップの検索、専門分野、授業の科目名から直接開けます。検索では複数の言葉も使えます。</p>${A.link('#/','学びたいことから探す','search','primary')}</section><section class="setting-card panel"><h2>実験を動かす</h2><p>手順のある実験は「最初から再生」、途中の確認には「1ステップ進む」を使います。入力だけで結果が決まる実験には、再生バーは表示しません。</p><p>進行バーを動かすと一時停止し、任意の手順に移動します。再生速度は表示だけを変え、モデルの時間を変えません。</p></section><section class="setting-card panel"><h2>条件を比較する</h2><p>「A：初期条件」「B：別の条件」で変更前後を試せます。自分で選んだ条件は「いまの条件をAに固定」で一時的に比較できます。</p><p>比較データはこの単元を開いている間だけ有効です。別の画面に移動・再読み込みすると消えます。</p></section><section class="setting-card panel"><h2>動きを抑える</h2><p>装飾の動きとスムーズスクロールを抑えます。実験の再生は自分で操作できます。設定はこのページを閉じるまでの一時設定です。</p><label class="toggle-label"><span>動きを最小限にする</span><input type="checkbox" id="reduce-motion"${A.settings.reduceMotion?' checked':''}><span class="toggle-switch"></span></label></section><section class="setting-card panel"><h2>用語を調べる</h2><p>実験内の「用語」から説明を開けます。用語の定義と、その意味を試せる実験を一緒に表示します。</p>${A.button('用語集を開く','glossary','book')}</section><section class="setting-card panel"><h2>キーボードで操作する</h2><div class="shortcut-grid"><span><kbd>Ctrl / ⌘ K</kbd> 単元を検索</span><span><kbd>Space</kbd> 再生・一時停止</span><span><kbd>← / →</kbd> 1ステップ戻る・進む</span><span><kbd>Esc</kbd> ダイアログを閉じる</span></div><p>入力欄の操作中は実験のショートカットを使いません。進行バーは矢印キー、Home、Endでも操作できます。</p></section></div><div class="info-banner">${icon('shield',18)}<span>学習履歴・ノート・お気に入り・入力条件を保存する機能はありません。旧版が同じ保存領域に残したデータは、開いた際に削除を試みます。ブラウザが管理するURLの閲覧履歴は、このサイトの保存機能とは別です。</span></div>`,'操作ガイド・表示','settings');
A.views.notfound=()=>render(`${A.heading('NOT FOUND','この単元は見つかりません。','URLを確認するか、単元一覧から探してください。',A.link('#/catalog','すべての単元へ','arrow','primary'))}`,'見つかりません','catalog');
})();
