/* Accessible, data-driven visualizations. Only numeric coordinates enter SVG paths. */
(() => {
'use strict';
const L=CSL;
const h=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=x=>Number.isFinite(+x)?+x:0;
const fmt=x=>typeof x==='number'?(Number.isFinite(x)?Number(x.toPrecision(5)).toLocaleString('en-US'):'∞'):String(x??'—');
const colors=['#91cdbf','#9dbfe9','#beb0dd','#d7bd90','#d5a9b7','#a8c2a0'];
const icons={
 home:'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z',
 grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',
 network:'M10 3h4v4h-4zM2 17h5v4H2zM17 17h5v4h-5zM12 7v5M4.5 17v-5h15v5',
 shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6ZM8.5 12l2.5 2.5 4.5-5',
 route:'M5 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4ZM19 21a2 2 0 1 0 0-4 2 2 0 0 0 0 4ZM7 5h8a4 4 0 0 1 0 8H9a3 3 0 0 0 0 6h8',
 map:'m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2ZM9 3v16M15 5v16',
 book:'M12 6c-3-2-6-2-10-1v15c4-1 7-1 10 1 3-2 6-2 10-1V5c-4-1-7-1-10 1Zm0 0v15',
 note:'M5 3h11l4 4v14H5ZM15 3v5h5M8 12h9M8 16h6',
 flask:'M9 3h6M10 3v7l-6 9c-.5 1 .2 2 1 2h14c.8 0 1.5-1 1-2l-6-9V3M7 15h10',
 search:'M10.5 17.5a7 7 0 1 0 0-14 7 7 0 0 0 0 14ZM16 16l5 5',
 arrow:'M4 12h16M14 6l6 6-6 6',
 chevron:'m9 5 7 7-7 7',
 down:'m6 9 6 6 6-6',
 play:'m8 4 13 8-13 8Z', pause:'M8 5v14M16 5v14',
 back:'m15 6-7 6 7 6M5 5v14', next:'m9 6 7 6-7 6M19 5v14',
 reset:'M4 11a8 8 0 1 1 2 7M4 4v7h7',
 check:'m5 12 4 4L19 6',close:'m6 6 12 12M6 18 18 6',
 menu:'M4 6h16M4 12h16M4 18h16',star:'m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9Z',
 save:'M4 3h13l4 4v14H3V3ZM7 3v6h10V3M7 21v-8h10v8',download:'M12 3v12m-5-5 5 5 5-5M4 15v6h16v-6',upload:'M12 16V4m-5 5 5-5 5 5M4 15v6h16v-6',
 settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',
 info:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18ZM12 11v6M12 7v1',
 clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18ZM12 7v5l3 2',
 git:'M6 3v12m0 0a3 3 0 1 0 0 6 3 3 0 0 0 0-6Zm0-7c7 0 12 0 12-5m0 0a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z',
 cpu:'M7 7h10v10H7zM9 1v6m6-6v6M9 17v6m6-6v6M1 9h6m-6 6h6M17 9h6m-6 6h6',
 memory:'M3 6h18v11H3zM6 9h4v5H6zM14 9h4v5h-4zM6 17v4m4-4v4m4-4v4m4-4v4',
 code:'m8 5-6 7 6 7M16 5l6 7-6 7M14 3l-4 18',
 binary:'M3 5h5v14H3zM12 5h2v14m-3 0h6M20 5v14',
 math:'M3 5h18M6 2v6M3 16h7m-3-3v6M16 13l6 6m-6 0 6-6',
 logic:'M4 5h6c7 0 7 14 0 14H4M1 8h6M1 16h6M15 12h8',
 tree:'M10 2h4v4h-4ZM3 17h4v4H3ZM17 17h4v4h-4ZM12 6v5M5 17v-6h14v6',
 algorithm:'M3 19h3V9H3ZM10 19h3V3h-3ZM17 19h3V6h-3Z',
 database:'M3 6c0-4 18-4 18 0s-18 4-18 0Zm0 0v12c0 4 18 4 18 0V6M3 12c0 4 18 4 18 0',
 os:'M3 3h18v14H3zM8 21h8M12 17v4M6 7l3 2-3 2M12 12h5',
 concurrency:'M3 4h6v6H3zM15 14h6v6h-6zM6 10v7h9M9 7h9v7',
 ai:'M12 3v4M5 7h14v13H5ZM2 11h3m14 0h3M8 11h1m6 0h1M8 16h8',
 wave:'M2 12c3-12 7-12 10 0s7 12 10 0',
 control:'M3 12h4l3-8 4 16 3-8h4',
 human:'M12 3a3 3 0 1 0 0 6 3 3 0 0 0 0-6ZM5 21v-3a7 7 0 0 1 14 0v3M4 12l16 0',
 compare:'M7 3v18M17 3v18M3 7h8m-3-3 3 3-3 3M13 17h8m-3-3 3 3-3 3',
 lock:'M6 10h12v11H6ZM8 10V6a4 4 0 0 1 8 0v4M12 14v3',
 terminal:'M3 4h18v16H3ZM6 8l4 4-4 4M12 16h5',
 external:'M14 3h7v7m0-7-11 11M10 3H3v18h18v-7',
 trash:'M4 6h16M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7',
 plus:'M12 4v16M4 12h16', help:'M9 8a3 3 0 1 1 5 2c-2 1-2 2-2 4M12 17v1M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20',
 link:'m9 15 6-6M8 16l-1 1a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0M16 8l1-1a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0',
 folder:'M3 6h7l2 3h9v12H3ZM3 6V3h7l2 3h9v3', sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM12 1v3m0 16v3M1 12h3m16 0h3'
};
icons.server=icons.database;icons.radar=icons.search;icons.circuit=icons.logic;icons.compiler=icons.code;icons.branch=icons.git;
function icon(name,size=20){return `<svg class="icon" width="${n(size)}" height="${n(size)}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name]||icons.flask}"/></svg>`;}
function svg(body,w=760,height=370,label='実験の内部状態'){return `<svg viewBox="0 0 ${n(w)} ${n(height)}" role="img" aria-label="${h(label)}" xmlns="http://www.w3.org/2000/svg"><defs><marker id="arrowhead" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill="context-stroke"/></marker><pattern id="dotgrid" width="24" height="24" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".65" fill="#2a3442"/></pattern></defs><rect width="100%" height="100%" fill="url(#dotgrid)" opacity=".5"/>${body}</svg>`;}
const text=(x,y,s,cls='',anchor='start')=>`<text x="${n(x)}" y="${n(y)}" class="${h(cls)}" text-anchor="${anchor}">${h(s)}</text>`;
const line=(x1,y1,x2,y2,cls='',extra='')=>`<line x1="${n(x1)}" y1="${n(y1)}" x2="${n(x2)}" y2="${n(y2)}" class="${h(cls)}" ${extra}/>`;
const rect=(x,y,w,ht,fill='#192330',stroke='#374457',r=7)=>`<rect x="${n(x)}" y="${n(y)}" width="${Math.max(0,n(w))}" height="${Math.max(0,n(ht))}" rx="${r}" fill="${fill}" stroke="${stroke}"/>`;
const html=x=>`<div class="visual-html">${x}</div>`;
function table(t,caption='内部状態の値'){if(!t)return '<div class="empty-state">この状態の表はありません。</div>';return `<div class="table-wrap"><table class="data-table"><caption class="sr-only">${h(caption)}</caption><thead><tr>${t.headers.map(v=>`<th scope="col">${h(v)}</th>`).join('')}</tr></thead><tbody>${t.rows.map(r=>`<tr>${r.map(v=>`<td>${h(typeof v==='object'?JSON.stringify(v):v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function network(v,context={}){
 let b='';const nodes=v.nodes||[],edges=v.edges||[];
 for(let i=0;i<edges.length;i++){const e=edges[i],a=nodes.find(n=>n.id===e.a),z=nodes.find(n=>n.id===e.b);if(!a||!z)continue;const pi=(v.path||[]).indexOf(e.a),pj=(v.path||[]).indexOf(e.b),active=e.active||pi>=0&&pj>=0&&Math.abs(pi-pj)===1;const cls=`network-edge${e.off?' off':''}${active?' active':''}`;b+=`<g ${v.editable?`data-edge="${i}" role="button" tabindex="0" aria-label="${h(e.a)} と ${h(e.b)} のリンクを${e.off?'接続':'切断'}"`:''}>${v.directed?line(a.x,a.y,z.x-(z.x-a.x)/Math.max(1,Math.hypot(z.x-a.x,z.y-a.y))*45,z.y-(z.y-a.y)/Math.max(1,Math.hypot(z.x-a.x,z.y-a.y))*35,cls,'marker-end="url(#arrowhead)"'):line(a.x,a.y,z.x,z.y,cls)}${v.editable?line(a.x,a.y,z.x,z.y,'edge-hit'):''}${e.cost!==undefined?rect((a.x+z.x)/2-16,(a.y+z.y)/2-11,32,22,'#101720',e.off?'#704b50':'#2e3c4d',5)+text((a.x+z.x)/2,(a.y+z.y)/2+4,e.off?'×':e.cost,'svg-small','middle'):''}</g>`;}
 for(const nd of nodes){const active=(Array.isArray(v.active)?v.active.includes(nd.id):v.active===nd.id)||(v.path||[]).includes(nd.id);b+=`<g class="network-node${active?' active':''}${context.selected===nd.id?' selected':''}" transform="translate(${n(nd.x)},${n(nd.y)})" data-node="${h(nd.id)}" role="button" tabindex="0" aria-label="${h(nd.label||nd.id)} の情報"><rect x="-39" y="-30" width="78" height="60" rx="11"/>`;
 let symbol=nd.kind==='server'?'<rect x="-14" y="-17" width="28" height="34" rx="3"/><path d="M-10-7H10M-10 4H10M-9 11H-5"/>':nd.kind==='pc'?'<rect x="-17" y="-14" width="34" height="24" rx="2"/><path d="M0 10v7M-8 17H8"/>':nd.kind==='switch'?'<rect x="-21" y="-9" width="42" height="19" rx="3"/><path d="M-14-3v6M-5-3v6M4-3v6M13-3v6"/>':'<path d="M-18 0H18M0-17V17M-18 0l5-4m-5 4 5 4M18 0l-5-4m5 4-5 4M0-17l-4 5m4-5 4 5M0 17l-4-5m4 5 4-5"/>';
 b+=`<g class="node-symbol">${symbol}</g>${text(0,50,nd.label||nd.id,'svg-label','middle')}${nd.sub?text(0,68,nd.sub,'svg-small','middle'):text(0,66,nd.id,'svg-small','middle')}</g>`;}
 return svg(b,760,400,v.editable?'編集可能な仮想ネットワーク':'通信の経路と機器');
}
function sequence(v){const actors=v.actors||[],msgs=v.messages||[],W=760,ht=Math.max(340,130+msgs.length*49),xs=actors.map((_,i)=>70+i*(W-140)/Math.max(1,actors.length-1));let b='';actors.forEach((a,i)=>{b+=rect(xs[i]-55,20,110,38)+text(xs[i],44,a,'svg-label','middle')+line(xs[i],65,xs[i],ht-30,'gridline','stroke-dasharray="5 6"');});msgs.forEach((m,i)=>{let y=95+i*49,x1=xs[m.from],x2=xs[m.to],color=m.failed?'#e5a3a3':colors[i%3];if(x1===undefined||x2===undefined)return;if(x1===x2){b+=`<path d="M${x1} ${y}h50v22h-50" fill="none" stroke="${color}" marker-end="url(#arrowhead)"/>`+text(x1+57,y+10,m.label,'svg-small');}else b+=line(x1,y,x2,y,'',`stroke="${color}" stroke-width="1.6" marker-end="url(#arrowhead)" ${m.failed?'stroke-dasharray="5 4"':''}`)+text((x1+x2)/2,y-10,m.label,'','middle');b+=text(16,y+4,i+1,'svg-small');});return svg(b,W,ht,'通信の時系列。縦が時間、横が通信相手');}
function plot(v){const series=(v.series||[]).filter(s=>Array.isArray(s.points)&&s.points.length);const pts=series.flatMap(s=>s.points).filter(p=>Number.isFinite(+p.x)&&Number.isFinite(+p.y));if(!pts.length)return html('<p>表示する点がありません。</p>');const minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(0,...pts.map(p=>p.y)),maxY=Math.max(0,...pts.map(p=>p.y));const sx=x=>65+(x-minX)/(maxX-minX||1)*640,sy=y=>300-(y-minY)/(maxY-minY||1)*235;let b='';for(let j=0;j<=4;j++){const y=minY+(maxY-minY)*j/4,x=minX+(maxX-minX)*j/4;b+=line(65,sy(y),705,sy(y),'gridline')+text(53,sy(y)+4,fmt(y),'svg-small','end')+text(sx(x),323,fmt(x),'svg-small','middle');}b+=line(65,sy(0),705,sy(0),'axis')+line(65,55,65,300,'axis');for(const [i,s]of series.entries()){let p=s.points.filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y));b+=`<polyline points="${p.map(p=>`${sx(p.x)},${sy(p.y)}`).join(' ')}" fill="none" stroke="${colors[i%colors.length]}" stroke-width="${i?2:2.5}" stroke-linecap="round" stroke-linejoin="round"/>`;b+=line(75+i*175,23,93+i*175,23,'',`stroke="${colors[i%colors.length]}" stroke-width="2"`)+text(100+i*175,27,s.name,'svg-small');}b+=text(390,355,v.xLabel||'入力 / 時間','svg-small','middle')+text(13,30,v.yLabel||'値','svg-small');return svg(b,760,380,'入力や時間に対する値の変化');}
function bars(v){let values=v.values||[],min=Math.min(0,...values),max=Math.max(1,...values),sy=x=>300-(x-min)/(max-min)*230,w=640/Math.max(values.length,1);let b=line(60,sy(0),710,sy(0),'axis');values.forEach((a,i)=>{const act=Array.isArray(v.active)?v.active.includes(i):v.active===i;const y=Math.min(sy(a),sy(0)),ht=Math.max(2,Math.abs(sy(a)-sy(0))),done=Array.isArray(v.sorted)&&v.sorted.includes(i);const fill=act?'#d7bd90':done?'#91cdbf':'#7095b8';b+=rect(65+i*w,y,w*.74,ht,fill,'none',3)+text(65+i*w+w*.37,a>=0?y-9:y+ht+17,fmt(a),act?'svg-warning':'','middle')+text(65+i*w+w*.37,330,v.labels?.[i]??i,'svg-small','middle');});return svg(b,760,365,'各項目の値の比較');}
function flow(v){const nodes=v.nodes||[],rows=Math.ceil(nodes.length/4),ht=Math.max(340,100+rows*100),cols=Math.min(4,nodes.length),x=i=>45+(i%4)*(670/Math.max(1,cols)),y=i=>100+Math.floor(i/4)*110,w=670/Math.max(1,cols)-25;let b='';nodes.forEach((t,i)=>{if(i&&i%4)b+=line(x(i)-24,y(i)+26,x(i)-4,y(i)+26,'',`stroke="#607687" marker-end="url(#arrowhead)"`);const act=v.active===i,color=act?(v.failed?'#e5a3a3':'#91cdbf'):'#36475a';b+=rect(x(i),y(i),w,52,act?'#1d2f31':'#151e29',color,8)+text(x(i)+w/2,y(i)-13,String(i+1).padStart(2,'0'),'svg-small','middle');const str=String(t);if(str.length>17)b+=text(x(i)+w/2,y(i)+21,str.slice(0,17),'svg-label','middle')+text(x(i)+w/2,y(i)+40,str.slice(17,35)+(str.length>35?'…':''),'svg-small','middle');else b+=text(x(i)+w/2,y(i)+31,str,'svg-label','middle');});if(v.detail)b+=text(380,ht-40,v.detail,'svg-small','middle');return svg(b,760,ht,'処理の段階と現在位置');}
function tree(v){if(!v.root)return html('<p>木は空です。</p>');let leaves=0,list=[],links=[];function walk(t,depth){if(!t)return null;const children=t.children||(t.left||t.right?[t.left,t.right]:[]);let kids=children.filter(Boolean).map(c=>walk(c,depth+1)),x=kids.length?kids.reduce((s,c)=>s+c.slot,0)/kids.length:leaves++;let o={slot:x,depth,label:t.label??t.keys?.join(' | ')??t.value??'',leaf:t.leaf};list.push(o);for(const c of kids)links.push([o,c]);return o;}walk(v.root,0);let maxD=Math.max(...list.map(t=>t.depth)),ht=Math.max(360,110+maxD*82),sx=o=>75+(o.slot+.5)*600/Math.max(leaves,1),sy=o=>65+o.depth*82,b='';links.forEach(([a,z])=>b+=line(sx(a),sy(a),sx(z),sy(z),'network-edge'));for(const t of list){const wid=Math.max(44,Math.min(115,String(t.label).length*9+24));b+=rect(sx(t)-wid/2,sy(t)-20,wid,40,t.leaf?'#1d302f':'#182331',t.leaf?'#75a99c':'#6688ad',7)+text(sx(t),sy(t)+5,t.label,'svg-label','middle');}return svg(b,760,ht,'木構造。線は親子関係');}
function lanes(v){const a=v.items||[],max=Math.max(1,...a.map(x=>x.end)),ht=Math.max(345,100+a.length*37),start=95,width=600;let b='';for(let i=0;i<=5;i++){let t=max*i/5,x=start+width*i/5;b+=line(x,45,x,ht-45,'gridline')+text(x,ht-24,fmt(t),'svg-small','middle');}a.forEach((it,i)=>{let y=60+i*37,c=colors[i%colors.length];b+=text(80,y+17,it.label,'svg-small','end');let segs=it.segments;if(Array.isArray(segs)&&segs.length){segs.forEach((s,j)=>{let x=start+(it.start+j)/max*width;b+=rect(x,y,Math.max(3,width/max-2),25,s==='·'||s==='S'?'#3c3541':c,'none',3)+text(x+width/max/2,y+17,s,'svg-dark','middle');});}else b+=rect(start+it.start/max*width,y,Math.max(3,(it.end-it.start)/max*width),25,c,'none',3)+((it.end-it.start)/max*width>28?text(start+(it.start+it.end)/2/max*width,y+17,fmt(it.end-it.start),'svg-dark','middle'):'');});b+=text(710,ht-24,v.unit||'time','svg-small','end');return svg(b,760,ht,'時間軸上の処理の配置');}
function scatter(v){const pts=v.points||[],all=[...pts,...(v.line||[]),...(v.centers||[])];let minX=Math.min(0,...all.map(p=>p.x)),maxX=Math.max(1,...all.map(p=>p.x)),minY=Math.min(0,...all.map(p=>p.y)),maxY=Math.max(1,...all.map(p=>p.y),v.thresholdAxis==='y'?n(v.threshold):0),sx=x=>65+(x-minX)/(maxX-minX||1)*640,sy=y=>300-(y-minY)/(maxY-minY||1)*240,b='';for(let j=0;j<=4;j++){const xx=minX+(maxX-minX)*j/4,yy=minY+(maxY-minY)*j/4;b+=line(65,sy(yy),705,sy(yy),'gridline')+text(53,sy(yy)+4,fmt(yy),'svg-small','end')+text(sx(xx),321,fmt(xx),'svg-small','middle');}pts.forEach(p=>b+=`<circle cx="${sx(p.x)}" cy="${sy(p.y)}" r="4.5" fill="${colors[(p.cluster??p.group??(p.label?1:0))%colors.length]}" opacity=".8"/>`);if(v.line)b+=`<polyline points="${v.line.map(p=>`${sx(p.x)},${sy(p.y)}`).join(' ')}" fill="none" stroke="#d7bd90" stroke-width="2.5"/>`;if(v.centers)v.centers.forEach((p,i)=>b+=`<path d="M${sx(p.x)-7} ${sy(p.y)-7}l14 14m-14 0 14-14" stroke="${colors[i%colors.length]}" stroke-width="3"/>`);if(v.threshold!==undefined)b+=v.thresholdAxis==='y'?line(65,sy(v.threshold),705,sy(v.threshold),'',`stroke="#d7bd90" stroke-dasharray="5 4" data-threshold="y"`):line(sx(v.threshold),55,sx(v.threshold),300,'',`stroke="#d7bd90" stroke-dasharray="5 4" data-threshold="x"`);if(v.legend)v.legend.forEach((label,i)=>{b+=`<circle cx="${75+i*(630/Math.max(1,v.legend.length))}" cy="24" r="4" fill="${colors[i%colors.length]}"/>`+text(89+i*(630/Math.max(1,v.legend.length)),28,label,'svg-small');});if(v.xLabel)b+=text(390,350,v.xLabel,'svg-small','middle');if(v.yLabel)b+=text(15,48,v.yLabel,'svg-small');return svg(b,760,375,'データ点と学習した関係');}
function git(v){const s=v.state,objs=Object.values(s.objects),positions={},lanesById={};let nextLane=0;objs.forEach(o=>{let lane=0;if(o.parents.length){const par=o.parents[0];const siblings=objs.filter(q=>q.parents[0]===par);lane=siblings[0]?.id===o.id?(lanesById[par]||0):++nextLane;}lanesById[o.id]=lane;});const ht=Math.max(120,objs.length*56+55),maxLane=Math.max(...Object.values(lanesById));objs.forEach((o,i)=>positions[o.id]={x:70+lanesById[o.id]*50,y:ht-45-i*56});let b='';objs.forEach(o=>{for(const p of o.parents){let a=positions[p],z=positions[o.id];if(a)b+=`<path d="M${a.x} ${a.y}C${a.x} ${(a.y+z.y)/2} ${z.x} ${(a.y+z.y)/2} ${z.x} ${z.y}" fill="none" stroke="${colors[lanesById[o.id]%colors.length]}" stroke-width="2" ${v.reachable?.includes(o.id)?'':'stroke-dasharray="4 4" opacity=".4"'}/>`;}});objs.forEach(o=>{const p=positions[o.id],active=v.current===o.id,reachable=v.reachable?.includes(o.id),cx=125+maxLane*50,refs=Object.entries(s.refs).filter(([_,id])=>id===o.id).map(([name])=>name+(s.head===name?' ← HEAD':''));if(s.detached===o.id)refs.push('HEAD（detached）');const remote=Object.entries(s.remote).filter(([_,id])=>id===o.id).map(([name])=>'remote: '+name);let rem=Object.entries(s.tracking).filter(([_,id])=>id===o.id).map(([name])=>name);b+=`<circle cx="${p.x}" cy="${p.y}" r="${active?8:6}" fill="${reachable?'#91cdbf':'#16212e'}" stroke="${active?'#f0ece1':'#779d94'}" stroke-width="${active?2:1}"/>`+text(p.x-14,p.y+4,o.id,'svg-small','end')+text(cx,p.y+4,o.message.slice(0,39),'svg-label')+text(cx,p.y+21,[...refs,...rem,...remote].join(' · '),'svg-accent');});const cols=[['HEADのファイル',s.objects[v.current]?.tree||{}],['ステージ / index',s.index],['作業ファイル',s.work]];return `<div class="git-visual">${svg(b,760,ht,'Gitコミットの親子関係。上が新しいコミット。破線は参照から届かない履歴。')}<div class="git-state-grid">${cols.map(([name,obj])=>`<div class="git-state"><h4>${h(name)}</h4>${Object.entries(obj).map(([k,val])=>`<div class="git-file"><span>${h(k)}</span><code>${h(val)}</code></div>`).join('')||'<span class="muted">空</span>'}</div>`).join('')}</div></div>`;}
function visualize(v,ctx={}){
 switch(v.type){
 case'network':return network(v,ctx);
 case'sequence':return sequence(v);
 case'plot':return plot(v);
 case'wave':return plot({series:[{name:'送信信号（教材）',points:v.points}],xLabel:'ビット位置',yLabel:'信号'});
 case'bars':return bars(v);
 case'flow':return flow(v);
 case'tree':return tree(v);
 case'lanes':return lanes(v);
 case'scatter':return scatter(v);
 case'git':return git(v);
 case'bitrow':{let b=String(v.bits||''),cols=b.length<=8?8:b.length<=16?16:16;return html(`<div class="binary-board"><div class="visual-legend">${v.interactive?'ビットをクリックして、値を変える':'左が上位ビット → 右が下位ビット'}</div><div class="bit-grid${b.length>32?' large':''}" style="--columns:${cols}">${[...b].map((val,i)=>{const cls=`bit ${val==='1'?'one':''} ${v.split!==undefined&&i>=v.split?'host':''} ${v.changedBits?.includes(i)||v.active===i?'flipped':''}`;return v.interactive?`<button class="${cls} bit-button" data-bit="${i}" aria-label="${b.length-1-i} ビット目、現在 ${val}、切り替える"><span class="bit-index">2<sup>${b.length-1-i}</sup></span><span class="bit-num">${h(val)}</span></button>`:`<div class="${cls}"><span class="bit-index">${i}</span><span class="bit-num">${h(val)}</span></div>`;}).join('')}</div>${v.labels?`<div class="visual-legend">${h(v.labels.join(' / '))}</div>`:''}${v.segments?`<div class="visual-legend">${v.segments.map(x=>h(typeof x==='string'?x:JSON.stringify(x))).join('　')}</div>`:''}</div>`);}
 case'cells':return html((v.rows||[]).map(r=>`<div class="cells-row"><div class="cells-label">${h(r.label)}</div><div class="cells-values">${(r.values||[]).map((c,i)=>`<div class="cell${r.active===i||r.active===true?' active':''}">${h(fmt(c))}</div>`).join('')}</div></div>`).join(''));
 case'layers':return html(`<div class="layers-board">${v.layers.map((x,i)=>`<div class="layer-block" style="margin-inline:${(v.layers.length-i-1)*10}px;border-color:${colors[i%3]}"><span class="layer-order">0${i+1}</span><div><strong>${h(x.name)}</strong><p>${h(x.note)}</p></div><b>${h(x.size)} B</b></div>`).join('')}<div class="payload-box"><span>PAYLOAD</span><code>${h(v.payload)}</code></div></div>`);
 case'packets':{const a=Array.from({length:v.count},(_,i)=>i+1);return html(`<div class="packet-board"><div class="packet-endpoints"><span>${icon('os')} 送信側</span><span>${icon('server')} 受信側</span></div><div class="packet-track">${a.map(i=>{const recv=v.received.includes(i),flight=v.inflight.includes(i),lost=v.lost===i;return `<div class="packet${recv?' received':''}${flight?' flying':''}${lost?' lost':''}"><span class="packet-index">SEQ ${i}</span><b>${recv?'✓':lost?'×':flight?'→':'·'}</b><small>${recv?'到着済み':lost?'損失':flight?'転送中':'未送信'}</small></div>`;}).join('')}</div><div class="ack-line"><span>累積確認応答</span><strong>次に必要：#${h(v.ack)}</strong><span>ウィンドウ：${h(v.window)} セグメント</span></div><div class="visual-legend">受信済みのデータと、順番どおり渡せる範囲は別です。</div></div>`);}
 case'zones':return html(`<div class="zones-board">${(v.zones||[]).map((z,i)=>`${i?`<div class="zone-link">${icon(v.blocked?'lock':'arrow')}</div>`:''}<div class="zone"><h4>${h(z.name)}</h4>${(z.items||[]).map(t=>`<div class="zone-item">${h(t)}</div>`).join('')||'<p class="muted">空</p>'}</div>`).join('')}</div>`);
 case'gate':{let o=v.output;return svg(line(130,130,310,130,'',`stroke="${v.a?'#91cdbf':'#526273'}" stroke-width="3"`)+line(130,250,310,250,'',`stroke="${v.b?'#91cdbf':'#526273'}" stroke-width="3"`)+rect(310,100,150,180,'#1d2935','#7392af',20)+text(385,198,v.gate,'svg-label','middle')+line(460,190,635,190,'',`stroke="${o?'#91cdbf':'#526273'}" stroke-width="3"`)+text(105,135,`A = ${v.a}`,'svg-label','end')+text(105,255,v.gate==='NOT'?'B 未使用':`B = ${v.b}`,'svg-label','end')+text(650,195,o,'svg-label')+text(380,335,'入力スイッチを変えて、出力を確かめる','svg-small','middle'));}
 case'automaton':{let b=rect(155,110,120,120,v.state===0?'#244138':'#192330',v.state===0?'#91cdbf':'#45576a',60)+rect(465,110,120,120,v.state===1?'#244138':'#192330',v.state===1?'#91cdbf':'#45576a',60)+`<circle cx="215" cy="170" r="51" fill="none" stroke="#779a8f"/>`+text(215,165,'偶数個','svg-label','middle')+text(215,187,'受理','svg-small','middle')+text(525,173,'奇数個','svg-label','middle')+`<path d="M275 150Q370 70 465 150M465 190Q370 270 275 190" fill="none" stroke="#91cdbf" stroke-width="1.6" marker-end="url(#arrowhead)"/>`+text(370,115,'1','','middle')+text(370,236,'1','','middle')+text(215,75,'0 → 同じ状態','svg-small','middle')+text(525,75,'0 → 同じ状態','svg-small','middle');[...v.input].forEach((c,i)=>b+=text(170+i*26,313,c,i===v.index?'svg-warning':'','middle'));return svg(b,760,360,'1の個数の偶奇を受理する有限状態機械');}
 case'plane':{const all=[...v.original,...v.transformed],max=Math.max(2,...all.flatMap(p=>[Math.abs(p.x),Math.abs(p.y)])),scale=140/max,sx=x=>380+x*scale,sy=y=>185-y*scale;let b='';for(let t=-Math.ceil(max);t<=Math.ceil(max);t++){b+=line(sx(t),30,sx(t),340,'gridline')+line(210,sy(t),550,sy(t),'gridline');}b+=line(190,185,570,185,'axis','marker-end="url(#arrowhead)"')+line(380,350,380,20,'axis','marker-end="url(#arrowhead)"');[v.original,v.transformed].forEach((a,i)=>b+=`<polyline points="${a.map(p=>`${sx(p.x)},${sy(p.y)}`).join(' ')}" fill="${i?'#91cdbf22':'#9dbfe912'}" stroke="${colors[i?0:1]}" stroke-width="2" ${i?'':'stroke-dasharray="4 4"'}/>`);return svg(b+text(45,50,'点線：変換前','svg-small')+text(45,73,'実線：変換後','svg-accent'),760,375,'行列による平面図形の変換');}
 case'stack':return html(`<div class="stack-board">${(v.values||[]).map((x,i)=>`<div class="stack-item">${h(x)}<span>${i===v.values.length-1?'TOP':''}</span></div>`).join('')||'<div class="stack-item">空</div>'}</div>${v.output!==undefined?`<div class="stack-result">結果：${h(v.output)}</div>`:''}`);
 case'queues':return html(`<div class="queue-columns">${v.columns.map(c=>`<div class="queue-column"><h4>${h(c.name)}</h4>${c.items.map(x=>`<div class="queue-item">${h(x)}</div>`).join('')||'<p class="muted">空</p>'}</div>`).join('')}</div>${v.output?`<div class="output-line"><span>OUTPUT</span><code>${h(v.output.join(' → '))}</code></div>`:''}`);
 case'code':return html(`<div class="code-visual"><div class="code-list">${v.code.map((x,i)=>`<div class="code-line${v.line===i?' active':''}"><span class="line-number">${i+1}</span><code class="line-text">${h(x)}</code></div>`).join('')}</div><div class="variable-grid">${Object.entries(v.vars||{}).map(([k,x])=>`<div class="variable"><span>${h(k)}</span><b>${h(typeof x==='object'?JSON.stringify(x):fmt(x))}</b></div>`).join('')}</div>${v.output!==undefined?`<div class="output-line"><span>OUTPUT</span><code>${h(v.output)}</code></div>`:''}${v.stage?`<div class="visual-legend">${h(v.stage)}</div>`:''}</div>`);
 case'memory':return html(`<div class="memory-columns">${[['STACK',v.stack],['HEAP',v.heap]].map(([name,arr])=>`<div class="memory-box"><h4>${name}</h4>${(arr||[]).map(x=>`<div class="memory-slot${x.freed?' freed':''}"><span>${h(x.address)}</span><strong>${h(x.name)}</strong><b>${h(x.value??'—')}</b>${x.freed?'<small>解放済み</small>':''}</div>`).join('')||'<p class="muted">未使用</p>'}</div>`).join('')}</div>${v.pointer?`<div class="output-line">参照先：${h(v.pointer)}</div>`:''}`);
 case'allocation':{let cap=v.capacity||32;return html(`<div class="allocation-grid">${Array.from({length:cap},(_,i)=>{let a=(v.blocks||[]).find(b=>i>=b.start&&i<b.start+b.size),bad=Array.isArray(v.invalid)&&v.invalid.includes(i);return `<div class="allocation-cell${a?' allocated':''}${bad?' invalid':''}"><span>${i}</span><b>${a?'#'+a.id:'·'}</b></div>`;}).join('')}</div><div class="visual-legend"># は確保された領域のID、· は空き領域です。</div>`);}
 case'grid':return html(table({headers:['項目',...(v.colLabels||v.matrix[0]?.map((_,i)=>i)||[])],rows:v.matrix.map((r,i)=>[v.rowLabels?.[i]??i,...r])}));
 case'wireframe':{let sx=x=>380+x*130,sy=y=>185-y*130,b='';v.edges.forEach(([a,z],i)=>b+=line(sx(v.points[a].x),sy(v.points[a].y),sx(v.points[z].x),sy(v.points[z].y),'',`stroke="${colors[i<4?0:1]}" stroke-width="2"`));v.points.forEach((p,i)=>b+=`<circle cx="${sx(p.x)}" cy="${sy(p.y)}" r="4" fill="#d7bd90"/>`+text(sx(p.x)+10,sy(p.y),i,'svg-small'));return svg(b,760,370,'3次元の立方体を平面に投影した図');}
 case'contrast':return html(`<div class="contrast-sample" style="color:${h(v.foreground)};background:${h(v.background)};font-size:${n(v.size)}px">${h(v.text)}</div><div class="visual-legend">この枠の配色が実験対象です。サイト本体の配色は変わりません。</div>`);
 case'digest':return html(`<div class="digest-board">${[['入力A',v.original],['入力B',v.changed]].map(([label,str],r)=>`<div class="digest-row"><h4>${label} / 256 bits</h4><div class="digest-grid">${(str.match(/.{1,2}/g)||[]).map((s,i)=>`<span class="byte${r&&s!==v.original.slice(i*2,i*2+2)?' changed':''}">${h(s)}</span>`).join('')}</div></div>`).join('')}<div class="visual-legend">着色：入力Aと異なるバイト。16進数2桁が1バイトです。</div></div>`);
 case'imagegrid':return html(`<div class="image-grid" style="--image-size:${v.values[0].length}">${v.values.flatMap((r,y)=>r.map((val,x)=>{const shade=Math.max(0,Math.min(255,Math.round(val))),selected=v.selected?.[0]===x&&v.selected?.[1]===y;return `<div class="image-pixel${selected?' selected':''}" style="background:rgb(${shade} ${shade} ${shade});color:${shade>140?'#111':'#eee'}" title="(${x},${y}) = ${h(val)}">${h(val)}</div>`;})).join('')}</div><div class="visual-legend">枠は選択中の画素。数値はクリップ前の計算値です。</div>`);
 case'checks':return html(`<div class="check-list">${v.items.map(x=>`<div class="check-item${x.ok?'':' fail'}"><span class="check-symbol">${icon(x.ok?'check':'close')}</span><span>${h(x.label)}</span><b>${x.ok?'OK':'要確認'}</b></div>`).join('')}</div>`);
 case'confusion':return html(`<div class="confusion-grid">${[['正しく検知 / TP',v.tp,false],['誤って警告 / FP',v.fp,true],['見逃し / FN',v.fn,true],['正しく正常 / TN',v.tn,false]].map(([lab,num,bad])=>`<div class="confusion-cell${bad?' wrong':''}"><h4>${h(lab)}</h4><b>${h(fmt(num))}</b><span>件</span></div>`).join('')}</div><div class="visual-legend">実際の状態と、モデルの判定を分けて集計しています。</div>`);
 case'modclock':{let m=n(v.modulus),b='';for(let i=0;i<m;i++){let a=(i/m)*Math.PI*2-Math.PI/2,x=380+135*Math.cos(a),y=180+135*Math.sin(a),active=i===v.active;b+=`<circle cx="${x}" cy="${y}" r="${m>30?8:15}" fill="${active?'#91cdbf':'#1a2531'}" stroke="#486375"/>`+text(x,y+4,i,active?'svg-dark':'svg-small','middle');if(active)b+=line(380,180,x,y,'',`stroke="#91cdbf" stroke-width="2"`);}b+=text(380,174,'mod '+m,'svg-label','middle')+text(380,200,'余り '+v.active,'svg-accent','middle');return svg(b,760,370,'剰余を円上の位置として表現');}
 case'logs':return html(table({headers:['時刻 (s)','発生源','記録されたイベント'],rows:v.rows},'観測したログ'));
 default:throw new Error(`可視化が未登録です: ${v.type}`);
 }
}
function visualTable(v){if(v.type==='network')return {headers:['機器','名前','接続先'],rows:v.nodes.map(nd=>[nd.id,nd.label,v.edges.filter(e=>!e.off&&(e.a===nd.id||e.b===nd.id)).map(e=>e.a===nd.id?e.b:e.a).join(', ')])};if(v.type==='sequence')return{headers:['順番','送信側','受信側','内容'],rows:v.messages.map((m,i)=>[i+1,v.actors[m.from],v.actors[m.to],m.label])};if(v.type==='bars')return{headers:['位置 / 項目','値'],rows:v.values.map((x,i)=>[v.labels?.[i]??i,x])};if(v.type==='packets')return{headers:['番号','受信済み','転送中','損失'],rows:Array.from({length:v.count},(_,i)=>[i+1,v.received.includes(i+1)?'はい':'いいえ',v.inflight.includes(i+1)?'はい':'いいえ',v.lost===i+1?'はい':'いいえ'])};if(v.type==='plot')return{headers:['系列','x','y'],rows:v.series.flatMap(s=>s.points.map(p=>[s.name,fmt(p.x),fmt(p.y)]))};return {headers:['表示項目','値'],rows:Object.entries(v).filter(([k])=>k!=='type').map(([k,val])=>[k,typeof val==='object'?JSON.stringify(val):val])};}
Object.assign(L,{h,fmt,icon,svg,visualize,visualTable,table,colors});
})();
